### ISSUE TITLE
Crash when generate stager

### ISSUE THREAD

**Issue by Serizao** [BishopFox/sliver#100]
Hello thanks for your tool im testing but when i'am try to generate i have this issue 
i have no error and no specifique log do you know why ?

![Capture_d'écran_061819_025214_PM](https://user-images.githubusercontent.com/11671895/59683511-975e1680-91d8-11e9-9c4d-fbe0d21b4f1f.jpg)

**Comment by moloch--** [comment]
Can you provide us with the tail end of `~/.sliver/logs/sliver.log`?

**Comment by Serizao** [comment]
After i have seen log file i think that a misconfigure of my part :

`
INFO[0000] [sliver/vendor/github.com/dgraph-io/badger/logger.go:46] All 0 tables opened in 0s
INFO[0000] [sliver/vendor/github.com/dgraph-io/badger/logger.go:46] Replaying file id: 0 at offset: 0
INFO[0000] [sliver/vendor/github.com/dgraph-io/badger/logger.go:46] Replay took: 155.942µs
DEBU[0001] [sliver/server/generate/binaries.go:216] No [http https] URLs found in [mtls://10.104.0.204:8888]
DEBU[0001] [sliver/server/generate/binaries.go:216] No [dns] URLs found in [mtls://10.104.0.204:8888]
INFO[0001] [sliver/server/generate/binaries.go:359] Generating new sliver binary 'UNNECESSARY_STOOL'
DEBU[0001] [sliver/server/generate/binaries.go:216] No [http https] URLs found in [mtls://10.104.0.204:8888]
DEBU[0001] [sliver/server/generate/binaries.go:216] No [dns] URLs found in [mtls://10.104.0.204:8888]
INFO[0001] [sliver/server/certs/certs.go:156] Generating TLS certificate (ECC) for 'UNNECESSARY_STOOL' ...
INFO[0001] [sliver/server/certs/certs.go:193] Valid from 2018-09-01 15:22:06.476113848 +0200 CEST to 2021-08-31 15:22:06.476113848 +0200 CEST
INFO[0001] [sliver/server/certs/certs.go:198] Serial Number: 29440746241397956948356675802382507103
INFO[0001] [sliver/server/certs/certs.go:206] Client authentication certificate
INFO[0001] [sliver/server/certs/certs.go:212] ExtKeyUsage = [2]
INFO[0001] [sliver/server/certs/certs.go:237] Client certificate authenticates CN: UNNECESSARY_STOOL
DEBU[0001] [sliver/server/db/db.go:189] Loading db from /root/.sliver/db/buckets/5e13c25b-e65e-45ba-b24a-19dca297c15b
INFO[0001] [sliver/vendor/github.com/dgraph-io/badger/logger.go:46] All 0 tables opened in 0s
INFO[0001] [sliver/vendor/github.com/dgraph-io/badger/logger.go:46] Replaying file id: 0 at offset: 0
INFO[0001] [sliver/vendor/github.com/dgraph-io/badger/logger.go:46] Replay took: 212.577µs
INFO[0001] [sliver/server/certs/certs.go:83] Saving certificate for cn = 'UNNECESSARY_STOOL'
INFO[0001] [sliver/server/assets/assets.go:174] Creating GOPATH directory: /root/.sliver/slivers/windows/amd64/UNNECESSARY_STOOL/src
INFO[0001] [sliver/server/assets/assets.go:228] Unpacking go dependency protobuf.zip -> /root/.sliver/slivers/windows/amd64/UNNECESSARY_STOOL/src/github.com/golang
INFO[0001] [sliver/server/assets/assets.go:232] static asset not found: protobuf.zip
FATA[0001] [sliver/server/assets/assets.go:200] Failed to unzip go dependency: file does not exist
`

**Comment by moloch--** [comment]
Did you compile the server binary yourself? If so you may have forgotten to run the `go-assets.sh` script.
