### ISSUE TITLE
[!] rpc error: code = Unknown desc = exec: "payload.exe": cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by geoscrapper** [BishopFox/sliver#1003]
**Generated beacon**
 ::  generate beacon -b http://10.10.110.12:1111 -S 15 -e -t 300 -N payload -s /root

**Execute payload.exe**
got sessions but :
1. when execute other .exe file showing error : " [!] rpc error: code = Unknown desc = exec: "key.exe": cannot run executable found relative to current directory"
 
2. no download , no execute other files 

3. i'm try change folder and execute but this error too . old version beacons working but new generated not working! 

**Desktop (please complete the following information):**
 - OS: [linux debian]
 - Version [5.19.0]

![image](https://user-images.githubusercontent.com/91790678/202249916-382b9918-2399-424f-914a-8908e4a8a832.png)

**Comment by rkervella** [comment]
That's [a change in Go 1.19](https://tip.golang.org/doc/go1.19#os-exec-path) that we did not account for. As a workaround this should work: `execute /path/to/final.exe`.
