### ISSUE TITLE
rpc error: code = Internal desc = name cannot be empty

### ISSUE THREAD

**Issue by fadymarkram** [BishopFox/sliver#1016]
**Describe the bug**
when i try to backdooring the agent using backdoor --profile ***** "c:\windows\system32\calc.exe" or with single ' 
it gives me this error 
rpc error: code = Internal desc = name cannot be empty
i have checked the rpc code with the new commit it is the same as the repo 
**To Reproduce**
2. Command 1 '....'
3. Command 2 '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version [e.g. v0.0.5]

**Additional context**
![Screenshot from 2022-11-29 14-57-42](https://user-images.githubusercontent.com/37292213/204535244-2f0c500f-c599-44b0-9ba4-6176b909de9d.png)

**Comment by rkervella** [comment]
Fixed in 77148d0d312564b9b614f0dd7bd68c569b50c871. There's no release incorporating the fix yet, so I would recommend to [build from source](https://github.com/BishopFox/sliver/wiki/Compile-From-Source) in the meantime.
