### ISSUE TITLE
Logs don't get written to SLIVER_ROOT_DIR

### ISSUE THREAD

**Issue by nyanshak** [BishopFox/sliver#103]
**Describe the bug**
Logs get written to `~/.sliver/logs`, even when `SLIVER_ROOT_DIR` is overridden.

**To Reproduce**
1. `mkdir /tmp/sliver`
2. `env SLIVER_ROOT_DIR=/tmp/sliver ./sliver-server`

**Expected behavior**
All assets, logs, etc get written under `/tmp/sliver`.

**Actual behavior**
Logs still get written to ~/.sliver/logs.

**Additional context**

**Comment by moloch--** [comment]
Fixed in `master`

**Comment by nyanshak** [comment]
That was fast, thank you @moloch-- . On a similar note - generated binaries don't get written to something under the root, they get written to the working directory where sliver-server was started. I'm less sure that that's a bug, but if you think it is, I can open a separate issue for it if you'd like.

**Comment by moloch--** [comment]
That is the expected behavoir, you can specify alternate directories with `--save`. The current working directory is used because the client shares the same code.
