### ISSUE TITLE
256-character limitation warning showing even with `--in-process` execution mode

### ISSUE THREAD

**Issue by hugolebutter** [BishopFox/sliver#1036]
**Bug Description**
The `in-process` execution mode of the `rubeus` assembly has a 256 characters limitation, despite a WARNING message recommending to use that mode to run commands with long arguments (like when using a `/ticket:...` parameter)

**To Reproduce**

1. `rubeus -- s4u /user:FOOBAR /ticket:doIF...<TRUNCATED>...A== /impersonateuser:Administrator /msdsspn:cifs/corewkt002.core.cyber.local /altservice:HOST /ptt`

2. Warning:

`Arguments are limited to 256 characters when using the default fork/exec model for .NET assemblies and non-reflective PE files.
Consider using the --in-process flag to execute .NET assemblies in-process and work around this limitation.`

3. Re-running with the `--in-process` flag does not remove the warning and the process fails to be injected and run.

`rubeus --in-process -- s4u /user:FOOBAR /ticket:doIF...<TRUNCATED>...A== /impersonateuser:Administrator /msdsspn:cifs/corewkt002.core.cyber.local /altservice:HOST /ptt`
`Arguments are limited to 256 characters when using the default fork/exec model for .NET assemblies and non-reflective PE files.
Consider using the --in-process flag to execute .NET assemblies in-process and work around this limitation.`

**Expected behavior**
The `--in-process` mode should not result in that WARNING being displayed. Or the 256-character limitation should be made clear to impact any type of execution (with or without the `-i` flag)

**Desktop:**
- Sliver: Server v1.5.31 - cfb292d6d61860e31495e6554e2c98398c5303e7
- OS: Linux Kali - 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1

**Comment by moloch--** [comment]
@rkervella

**Comment by rkervella** [comment]
On it.
