### ISSUE TITLE
Something that may be useful for the GUI

### ISSUE THREAD

**Issue by whiterabb17** [BishopFox/sliver#1042]
Hey so I would have put this in the gui repo but you didnt have a section too..

So I have just built a few things in electron and got familiar with that, then went on a golang kick and wanted to make a UI for that program but and could do it in electron similar to yours (which I made some code for a dynamic context menu for electron should you want) but I wanted to make this new UI in more or less pure golang

After too much time looking around I came across go-astilectron. Which yup is essentially electron using go. All you'll need to do is write the html display page + plus whatever js you need to format entries. 
And can literally just push across the data from your already structured out golang ts 

Hope this helps you in some way 🙏
And will be happy to help with anything should you need
Thanks

**Comment by moloch--** [comment]
https://wails.io/ is also pretty cool if you've never tried it.

**Comment by whiterabb17** [comment]
Yeah, wails isn't bad! Was the first I had tried. The only reason I've ended up leaning on the electron base is that is the only one so far I have been able to fully implement winforms like context menus with inserting selected/highlighted values into the context menus when wanting to activate a module against a selected client

**Comment by whiterabb17** [comment]
The context menu code should you want to use it, works native electron as there is a required module
[electron-dynamic-context-menu.txt](https://github.com/BishopFox/sliver/files/10295453/electron-dynamic-context-menu.txt)
