### ISSUE TITLE
Logging of WATCHTOWER Threat Intel Monitoring 

### ISSUE THREAD

**Issue by aidden-laoch** [BishopFox/sliver#1069]
Requested: Documenting the setup of Watchtower and adding the alerts from a burned asset to the logs in JSON for Sliver.

Benefit: This would allow for notifications of burned assets to be sent to a SIEM such as elastic, where out of band alerting can notify the red/purple team.

**Comment by rkervella** [comment]
Added some [documentation](https://github.com/BishopFox/sliver/wiki/Watchtower).
