### ISSUE TITLE
Backup/export

### ISSUE THREAD

**Issue by realalexandergeorgiev** [BishopFox/sliver#1075]
I would like to backup and also move my sliver config to another host. I could not find information about which files and directories need to be moved. I noticed many /cache files and also a magnitude of implants (my .sliver folder was 10GB) (and also /logs was quite big).

When trying to simply run a new server the old builds wont connect - mTLS or PSK issue I guess, but I could not find information on this...

It would be great to have
a) a description which files can be deleted (cache/builds?/optional logs)
b) an export function of the current config, so i can move it to another server (which also would be kind of a backup)

Currently I copied the 10GB and it works .. but it doesnt feel right

**Comment by moloch--** [comment]
The simplest method it to copy your entire `~/.sliver` you don't need every file in this directory but it does contain all the files you need.

**Comment by rkervella** [comment]
It really depends on what you mean by "backup/export". If it's just about having another server that can generate new implants, you can avoid copying the old implant builds. However, if your new server needs to be able to answer to `regnerate` commands, then you'll need everything.

IIRC the least minimum is to copy the following files, but it's been a while so I would recommend running more tests on this:
- `certs` directory
- `sliver.db`
- `configs` directory (probably optional)

**Comment by realalexandergeorgiev** [comment]
> The simplest method it to copy your entire `~/.sliver` you don't need every file in this directory but it does contain all the files you need.

I can confirm that this works. 

Is it safe to delete these folders? They seem to contain all files related to implant generation
.sliver/builds/
.sliver/slivers/

**Comment by moloch--** [comment]
The `regenerate` command won't work if you delete `.sliver/builds` but nothing else should break for the most part. `.sliver/slivers/**` contains the old source code and isn't really needed.
