### ISSUE TITLE
custom implant for sliver

### ISSUE THREAD

**Issue by djn3m0** [BishopFox/sliver#1088]
Hi,

I wonder if its possible to write my own implant that can communicate to sliver server just like implants provided in this repository?
Is there any sample code I can refer to?

Thanks

**Comment by rkervella** [comment]
Right now there is no sample code to refer to. The way to do it would be to write an [external builder](https://github.com/BishopFox/sliver/wiki/External-Builders).

**Comment by djn3m0** [comment]
there is a  sliver-py that uses protobuf files in python to communicate the server! i image one can do that for implants as well?

**Comment by moloch--** [comment]
Yes, that's the intention. At some point we'll release a reference sliver-py builder.

**Comment by djn3m0** [comment]
great thanks
