### ISSUE TITLE
build the implant

### ISSUE THREAD

**Issue by djn3m0** [BishopFox/sliver#1095]
Hi,

I generated an implant using the sliver-client and i can see the source code under, ~/.sliver/slivers/windows/amd64/ABUNDANT_RACIST/src/github.com/bishopfox/sliver , how can i build this on my own?

i tried,
```
~/.sliver/slivers/windows/amd64/ABUNDANT_RACIST/src/github.com/bishopfox/sliver $ go build .
```

but i get the following error,
```
# github.com/bishopfox/sliver
./sliver.go:179:16: undefined: handlers.WrapperHandler
```

and i dont see that function being implemented in handlers.go file! im new to go so i might be missing something obvious here.

thanks

**Comment by moloch--** [comment]
The log files `~/.sliver/logs/sliver.log` will contain the full build commands, however it's Sliver is not really designed for you to compile the implant yourself as it requires setting certain ENV variables, but in theory it's possible.

**Comment by djn3m0** [comment]
Can you please point me where in the code the ENV variables are set, so i can have an idea?

Thanks

**Comment by moloch--** [comment]
The ENV vars are also logged in the log file.

**Comment by moloch--** [comment]
The relevant build function is here:
https://github.com/BishopFox/sliver/blob/master/server/generate/binaries.go#L405

**Comment by moloch--** [comment]
Should look something like:
```
INFO[2023-02-01T16:50:58-08:00] [sliver/server/gogo/go.go:126] garble cmd: '/Users/moloch/.sliver/go/bin/garble -seed=random -literals -tiny build -trimpath -ldflags  -o /Users/moloch/.sliver/slivers/darwin/arm64/RURAL_GINSENG/bin/RURAL_GINSENG .'
```
