### ISSUE TITLE
BOF's crashing beacon, inconsistency, lack of documentation

### ISSUE THREAD

**Issue by Octoberfest7** [BishopFox/sliver#1121]
**Describe the bug**
Some general observations: trying to use BOF's from the armory (SA bofs) in a Beacon, the first run of a BOF (ie. sa-whoami) doesn't appear to actually do anything, even though the implant calls back with "Successfully executed sa-whoami (coff-loader); there is no actual output.  The second and on runs produce output/actually run code as expected.

I am trying to port a project over for use in Sliver as an extension.  The project consists of two BOF's; one works correctly, the other crashes the Beacon. The BOF that runs successfully is fairly complex and at the end uses BeaconPrintf(CALLBACK_OUTPUT, "..."); to send data back to Sliver.  The second BOF crashes the implant. 

To try and trouble shoot the second BOF, I cut more and more things out until I decided to try and just run a simple, effectively "hello world" BOF with BeaconPrintf; this too crashes the Beacon. In x64 dbg I don't even get any kind of error or violation, it just terminates immediately.  I have no idea what to try at this point or any clue why the first BOF, being pretty complex, works while trying print a single message crashes the implant.

Both BOF's were compiled using Mingw: x86_64-w64-mingw32-gcc  -c BOF/test.c -o BOF/test/test.x64.o -Os 

I have tried without compiler optimization as well.

More documentation on Sliver Extensions and proper extension.json formatting would be welcome; for example, is there any way to set defaults for arguments, or to pre-specify arguments to a BOF that a user cannot input/change?

**To Reproduce**
extensions rm test
extensions load /root/gitlab/MemFiles_Dev/BOF/test
extensions install /root/gitlab/MemFiles_Dev/BOF/test
test

**Expected behavior**
BOF's to run reliably and not crash Beacon; in this specific test case, Beacon should call back with "ARGUMENT WAS: testing!"

**Screenshots**
![image](https://user-images.githubusercontent.com/91164728/221774086-ebbd97c0-371c-4713-baa1-805188ce413b.png)
![image](https://user-images.githubusercontent.com/91164728/221774233-6e7bcf6d-a5cb-4ce3-8e18-e3328695dae5.png)
![image](https://user-images.githubusercontent.com/91164728/221773857-4716bc2d-bccd-4792-ae13-8fcf0f402845.png)
![image](https://user-images.githubusercontent.com/91164728/221774172-00257b81-42f1-44be-ae9c-054408cf29f7.png)
![image](https://user-images.githubusercontent.com/91164728/221776594-e8a047b3-20d6-4ca0-88fc-5b347da267af.png)

**Desktop (please complete the following information):**
Running Sliver on Kali using latest binary release v1.5.34

Beacon's on Windows 11 10.0.22000

**Additional context**

**Comment by rkervella** [comment]
Looks like you could be hitting the same issue as in #679 (should probably rename this issue, this looks like a race condition), that we have not found the time to fix yet.

>  the other crashes the Beacon

Having a stack trace of that happening would be super helpful. Help us help you.

> More documentation on Sliver Extensions and proper extension.json formatting would be welcome[...]

Do you have a list of things you'd need that is not covered on the wiki already?

> [...] to pre-specify arguments to a BOF that a user cannot input/change?

Not at the moment, at some point we'll get around and implement that.

**Comment by Octoberfest7** [comment]
x64dbg didn't offer me anything, windbg has the following call stack:

![image](https://user-images.githubusercontent.com/91164728/221926436-86e74e1e-4d3b-4b27-a7fa-99799ecfe55a.png)

It appears to be exiting as opposed to crashing?

I created a Beacon with the --debug flag, and with debug output the test BOF works...

I also switched to a session, in which case I had inconsistent results in which the test command worked or not; but it didn't crash/exit the beacon when it failed.

![image](https://user-images.githubusercontent.com/91164728/221926777-2cdc971c-75a3-4159-b413-469372912473.png)

In reference to things not covered by the wiki concerning BOF's, it took me a while and experimentation to figure out how/why some arguments show up as they do; for example, when specifying an int argument type a note appears in sliver that says (Default: 0); perhaps just because I was looking for a way to specify default values for arguments in general, this was confusing as this behavior appears to be a built-in default for the int type, as looking at the corresponding extension.json file doesn't show or mention anything about default values.

**Comment by rkervella** [comment]
> It appears to be exiting as opposed to crashing?

Well that's annoying. I'll try to have a look.

> for example, when specifying an int argument type a note appears in sliver that says (Default: 0)

That is mainly due to how we're parsing the `extension.json` file and how the CLI lib we're using (grumble) works. Grumble requires strongly typed arguments default values, and specifying whether an argument is mandatory or optional so we're setting them when we parse the `extension.json` file. It can't be controlled by the end-user at the moment though. The code is all [here](https://github.com/BishopFox/sliver/blob/master/client/command/extensions/load.go#L172-L221) if you're curious.

**Comment by Octoberfest7** [comment]
I tested and am successfully able to run my BOF's now. Thank you for your work on resolving this issue.

I don't know that I actually mentioned it, but the project I was working on porting over to Sliver was my MemFiles project (https://github.com/Octoberfest7/MemFiles) which can capture files that are written to the target machine by the beacon process and hold them in memory for download.  I have the project successfully able to catch the files written by Sliver beacons, but have to work out an issue relating to downloading them back to the Sliver server. Seems to be a complication in how Go performs some file i/o things, as I have it working with Havoc.  When I get around to fixing it, I will release Sliver-compatible MemFiles which will hopefully be a useful addition to people's toolkits.

**Comment by rkervella** [comment]
Yeah I looked at your projects and figured it was the one you were trying to port :)
Glad this issue is solved, all credits go to @DominicBreuker.
