### ISSUE TITLE
Stuck and unresponsive when using shell command

### ISSUE THREAD

**Issue by 1n7erface** [BishopFox/sliver#1146]
When I use the shell command on the Windows machine, there is no response
<img width="643" alt="image" src="https://user-images.githubusercontent.com/52184829/224726351-0c8f6125-29d3-4101-a7f3-3c37849be2b0.png">

<img width="974" alt="image" src="https://user-images.githubusercontent.com/52184829/224725820-597eba0e-da44-4f8f-9e45-d92c368a975f.png">

**Comment by moloch--** [comment]
What are the local/remote operating systems?

**Comment by 1n7erface** [comment]
the remote operating system.

**Comment by moloch--** [comment]
Try `shell --no-pty`

**Comment by 1n7erface** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/52184829/224734827-a739f2f2-22a1-4a94-a2a0-f1c0f23fb3d8.png">
Still can't

**Comment by moloch--** [comment]
Does `/bin/bash` exist on the remote machine? You may need specify an alternative path if it doesn't, e.g. `shell --no-pty --shell-path /bin/sh`

**Comment by 1n7erface** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/52184829/224744381-9a230996-7190-4255-b466-734c50a710df.png">
It still seems impossible

**Comment by moloch--** [comment]
You'll probably have to stick with `execute`

**Comment by 1n7erface** [comment]
The execute module does not support many commands.
<img width="909" alt="image" src="https://user-images.githubusercontent.com/52184829/224747115-0a26c7ef-d22e-4a2f-bd43-6b5c35f6ff61.png">

**Comment by 1n7erface** [comment]
Maybe I'm not familiar with the execute module?

**Comment by moloch--** [comment]
`execute C:\\Windows\\System32\\cmd.exe /c dir`

**Comment by 1n7erface** [comment]
OK, there is no problem with this module. Thank you. But there are problems with shell modules. Thank you for your reply

**Comment by 1n7erface** [comment]
Let me redefine this issue. The environment is as follows:
1. Implant is a Windows 10 machine or Linux
2. The C2 server is Linux
3. If the player is Windows, this feature is fine, but using the Mac m1 feature will get stuck.

**Comment by 1n7erface** [comment]
This issue has been resolved when upgrading to version 1.5.6
