### ISSUE TITLE
First DNS Query Fails on Windows Server

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#116]
**Describe the bug**

The first DNS-C2 query on Windows Server operating system consistently fails, however subsequent attempts to establish a session are successful. This only seems to affect Windows Server-based operating systems

**To Reproduce**
1. Deploy DNS C2 implant on Windows Server

**Expected behavior**
Establishes session on first attempt.

**Desktop (please complete the following information):**
 - OS: Windows Server 2k8, and Server 2016
 - Version: v0.0.7 (master)

**Comment by digital-shokunin** [comment]
Not sure if this is related, but after fixing the last issue in #135 I was able to build an implant and test out C2 communications. It seems the implant is reaching the C2 but communication seems to be broken:

![image](https://user-images.githubusercontent.com/913856/69397584-ceb77e80-0cb4-11ea-847c-f634867a5b5e.png)

**Comment by moloch--** [comment]
Yea, I've been trying to find sometime to look into more details as to why this is so unreliable. It somewhat related to Windows' Go ( https://github.com/golang/go/issues/33097#issuecomment-540094648 ). The current DNS implementation also lacks redundancy in send/recv/ack, which isn't helping the situation. In my experience if you let the implant sit for a little bit the handshake will eventually go thru.
