### ISSUE TITLE
Noob Playing with Something He Doesn't Understand

### ISSUE THREAD

**Issue by wamsan** [BishopFox/sliver#1167]
Hello, 

I found out about Sliver through this blog: https://blog.ecapuano.com/p/so-you-want-to-be-a-soc-analyst-part-ea2

I was trying to generate an implant but receive this error during the process:

    [*] Generating new windows/amd64 implant binary

    [*] Symbol obfuscation is enabled

    [!] rpc error: code = Unknown desc = exit status 1

When I checked sliver.log, I see this:

    RRO[2023-03-26T21:53:12-04:00] [sliver/server/gogo/go.go:133] --- stdout ---

 

    ERRO[2023-03-26T21:53:12-04:00] [sliver/server/gogo/go.go:134] --- stderr ---

    # github.com/bishopfox/sliver

    cannot get modified linker: exec: "git": executable file not found in $PATH

    exit status 1

 

    ERRO[2023-03-26T21:53:12-04:00] [sliver/server/gogo/go.go:135] exit status 1 

    ERRO[2023-03-26T21:53:12-04:00] [github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/options.go:224] 
    finished unary call with code Unknown

I am not going to pretend that I know what that means - I am hoping to get some guidance in setting up the server on my VM Lab so I can practice with Lima Charlie. 

Any help is appreciated - thank you!

Sorry, I'll add:

OS: Ubuntu 22.04.2 LTS VM in VirtualBox 7.06

**Comment by moloch--** [comment]
You need to install mingw to cross-compile Windows payloads from Linux, see https://github.com/BishopFox/sliver/wiki/Cross-Compiling-Implants

**Comment by wamsan** [comment]
your advice worked! thanks so much! i downloaded a release. the version i'm running is 1.5.34. When I ran the curl command i think that is what downloaded. I know there is now a .36 version but i think i will follow the guide for now and explore the newer version later. 

thank you again for your help! :)
