### ISSUE TITLE
Kali arm64 - Executables only compile with debug flag

### ISSUE THREAD

**Issue by bosox0912** [BishopFox/sliver#1176]
When trying to generate binaries, I am only able to successfully compile them when enabling the --debug flag. I am running sliver-server on Macbook Pro M1 within a Kali VM utilizing the sliver apt repo for arm64. If i try running without --debug flag, I get the error:
rpc error: code = Unknown desc = fork/exec /home/###/.sliver/go/bin/garble: exec format error
Any fixes for this?
 
![image](https://user-images.githubusercontent.com/52496261/229178251-eddadb17-2816-4742-b1a1-670d3aa88afb.png)

![Screenshot_2023-03-31_12-27-42](https://user-images.githubusercontent.com/52496261/229177215-8989e8b3-1111-41e3-bb1c-9886416d136a.png)

**Comment by rkervella** [comment]
We're not responsible for packaging binaries for Kali. We recommend using the [release versions](https://github.com/BishopFox/sliver/releases) from GitHub. This issue has been fixed months ago if I remember correctly.

**Comment by bosox0912** [comment]
Hi thanks will try to download from releases instead.

**Comment by bosox0912** [comment]
Hi this was indeed the issue. Working fine now - thank you!
