### ISSUE TITLE
Golang not properly installed

### ISSUE THREAD

**Issue by thehackerish** [BishopFox/sliver#1219]
**Describe the bug**
The latest version of sliver-server does not install go properly. Therefore, it is no longer possible to generate an implant.

**To Reproduce**
1. Download the latest version of sliver-server release, I am using 1.5.38
2. Install Sliver using `sliver-server unpack --force`
3. Connect to your sliver and run `generate beacon -b https://hostna.me -S 5 -J 30 -l -d`
4. See error `fork/exec /root/.sliver/go/bin/go: no such file or directory` in the following sliver log

```
WARN[2023-05-05T08:17:27Z] [sliver/server/generate/binaries.go:208] Name cannot be blank!
INFO[2023-05-05T08:17:27Z] [sliver/server/certs/certs.go:140] Generating TLS certificate (ECC) for 'REGULAR_LYRE' ...
INFO[2023-05-05T08:17:27Z] [sliver/server/certs/certs.go:65] Saving certificate for cn = 'REGULAR_LYRE'
INFO[2023-05-05T08:17:27Z] [sliver/server/configs/server.go:46] Loading config from /root/.sliver/configs/server.json
INFO[2023-05-05T08:17:27Z] [sliver/server/configs/server.go:46] Loading config from /root/.sliver/configs/server.json
INFO[2023-05-05T08:17:27Z] [sliver/server/configs/server.go:153] Saving config to /root/.sliver/configs/server.json
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:164] go cmd: '/root/.sliver/go/bin/go tool dist list'
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:167] --- env ---
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] CC=
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] CGO_ENABLED=0
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] GOOS=windows
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] GOARCH=amd64
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] GOPATH=
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] GOCACHE=/root/.sliver/go/cache
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] GOMODCACHE=/root/.sliver/go/modcache
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] GOPROXY=off
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] HTTP_PROXY=
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] HTTPS_PROXY=
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:169] PATH=/root/.sliver/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:171] --- stdout ---

INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:172] --- stderr ---

INFO[2023-05-05T08:17:27Z] [sliver/server/gogo/go.go:173] fork/exec /root/.sliver/go/bin/go: no such file or directory
ERRO[2023-05-05T08:17:27Z] [github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/options.go:224] finished unary call with code Unknown
```

**Expected behavior**
An implant should be compiled.

**Screenshots**
N/A. See logs above

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.2 LTS

**Additional context**
I am using ansible to fetch the latest version everytime. Previous versions did not have this problem. I had to manually download go and place its installation under ~/.sliver/go/ for the implant compilation to work.

**Comment by moloch--** [comment]
Not able to immediately reproduce, any other environment specific things that may affect this?

**Comment by smeukinou** [comment]
I think I witnessed the exact same problem on the windows version of the server two releases ago (I didn't tried since), where the go compiler was just absent. I tried to install it manually bu it diodn't go very far either.
I thought it was just because the windows version is not-so-maintained.

**Comment by moloch--** [comment]
Hurm, I wonder if it's a bug in the asset upgrade code, in each case were you updating from a previous version of Sliver?

**Comment by smeukinou** [comment]
When I got the problem on windows, it was a first fresh install, no update. And ran without any options.

**Comment by thehackerish** [comment]
It seems like I don't have the issue anymore! Tried with a fresh ubuntu as well as another one with Sliver already installed. Therefore, I am closing this.
