### ISSUE TITLE
CTRL+C Handling

### ISSUE THREAD

**Issue by leaustinwile** [BishopFox/sliver#122]
Hello, when you drop into an interactive powershell session from an implant listener, CTRL+C kills both the interactive session and the sliver connection. You should implement CTRL+C handling that only kills the shell session and keeps the other connection alive. Additionally, CTRL+C exits the handler if you try to quit an upload, or any other feature in the app. If there is another way to terminate commands without quitting the session that'd be great.

**Comment by rkervella** [comment]
Related to #105

**Comment by moloch--** [comment]
If anyone has thoughts on solving this cross-platform lmk

**Comment by rkervella** [comment]
Fixed in 34ec2a4
