### ISSUE TITLE
askcreds sending text in chinese

### ISSUE THREAD

**Issue by p3tr0v** [BishopFox/sliver#1230]
**Describe the bug**
Askcreds armory displaying message in Chinese

**To Reproduce**
1. Once you have a session with your implant load armory and install "c2tc-askcreds"
 `armory`
 `armory install c2tc-askcreds`
2. After installing, ask for a credential
`c2tc-askcreds "java update"`
4. In the implant I see the message written in Chinese, but the Windows language is english.

**Expected behavior**
See the message in the exact way the user typed in Sliver side. Doesn't matter what language is.

**Screenshots**
![2023-05-13_18-57](https://github.com/BishopFox/sliver/assets/28512249/437f6017-7fa0-43e3-85e6-018d44086c33)

**Desktop (please complete the following information):**
 - OS: Parrot 5.3
 - Sliver Version:  1.5.38

**Comment by iilegacyyii** [comment]
Can second this, have had it occur on kali etc. My guess is CHAR to WCHAR conversion but unsure.

**Comment by moloch--** [comment]
Yea that's my guess as well just haven't had time to go hunt it down.

**Comment by FluffMe** [comment]
Tracked it down and PR'd in the appropriate [sliverarmory repo](https://github.com/sliverarmory/C2-Tool-Collection).

Cheers!
