### ISSUE TITLE
Add UI Warning if MSF Isn't Installed

### ISSUE THREAD

**Issue by sevagas** [BishopFox/sliver#1236]
**Describe the bug**
I cannot generate a stager using the "--protocol http" option.

**To Reproduce**
The error occur when attempting to generate a non TCP stager 
```
sliver > generate stager --lhost 192.168.15.23 --lport 8091 --protocol http --save .
[!] Error: rpc error: code = Unknown desc = exit status 2

sliver > generate stager --lhost 192.168.15.23 --lport 8091 --protocol https --save .
[!] Error: rpc error: code = Unknown desc = exit status 2
```
Note that if I use --protocol tcp it works fine.

**Expected behavior**
`[*] Sliver implant stager saved to: ...`

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.5.38

**Comment by moloch--** [comment]
You'll need to install Metasploit and ensure it's the correct version (6.2. or later):

https://github.com/BishopFox/sliver/wiki/Getting-Started#metasploit-setup-optional

**Comment by sevagas** [comment]
Maybe the documentation should mention Metasploit is mandatory for this usecase.

**Comment by rkervella** [comment]
> Maybe the documentation should mention Metasploit is mandatory for this usecase.

Well it kinda [does already](https://github.com/BishopFox/sliver/wiki/Stagers#metasploit-bring-your-own-stager).

**Comment by moloch--** [comment]
We should add a UI warning, its easy enough to detect if it's installed or not rather than returning a generic error message.
