### ISSUE TITLE
After install sliver from Kali repository sliver giving errors.

### ISSUE THREAD

**Issue by salihozanal** [BishopFox/sliver#1240]
**Describe the bug**
After install sliver from Kali repository sliver giving errors.

1. sudo apt install sliver
2. sliver-server
Sliver  Copyright (C) 2022  Bishop Fox
This program comes with ABSOLUTELY NO WARRANTY; for details type 'licenses'.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'licenses' for details.

Unpacking assets ...
panic: runtime error: index out of range [1] with length 1

goroutine 136 [running]:
github.com/bishopfox/sliver/server/rpc.(*Server).GetVersion(0xdf8e7f5d81?, {0x19551b2?, 0x6?}, 0x196775a?)
        github.com/bishopfox/sliver/server/rpc/rpc.go:90 +0x165
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler.func1({0x9629490, 0xc01b7da900}, {0x17d7720?, 0xc01b7da4e0})
        github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:2113 +0x7b
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.PayloadUnaryServerInterceptor.func1({0x9629490, 0xc01b7da900}, {0x17d7720, 0xc01b7da4e0}, 0x0?, 0xc01b7d6120)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/payload_interceptors.go:29 +0x17d
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc01b7da900}, {0x17d7720, 0xc01b7da4e0})
        google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1({0x9629490, 0xc01b7da810}, {0x17d7720, 0xc01b7da4e0}, 0xc01b7dc080, 0xc0002be900)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/logging/logrus/server_interceptors.go:31 +0x102
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc01b7da810}, {0x17d7720, 0xc01b7da4e0})
        google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1({0x9629490?, 0xc01b7da540?}, {0x17d7720, 0xc01b7da4e0}, 0xc01b7dc080, 0xc0002be8c0)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/tags/interceptors.go:23 +0xa6
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc01b7da540}, {0x17d7720, 0xc01b7da4e0})
        google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/bishopfox/sliver/server/transport.auditLogUnaryServerInterceptor.func1({0x9629490, 0xc01b7da540}, {0x17d7720, 0xc01b7da4e0}, 0xc01b7dc080, 0xc0002be800)
        github.com/bishopfox/sliver/server/transport/middleware.go:223 +0x395
google.golang.org/grpc.getChainUnaryHandler.func1({0x9629490, 0xc01b7da540}, {0x17d7720, 0xc01b7da4e0})
        google.golang.org/grpc@v1.54.0/server.go:1164 +0xb9
github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1({0x9629490, 0xc01b7da4b0}, {0x17d7720, 0xc01b7da4e0}, 0xc01b7dc080, 0xc0002be780)
        github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/auth/auth.go:47 +0xba
google.golang.org/grpc.chainUnaryInterceptors.func1({0x9629490, 0xc01b7da4b0}, {0x17d7720, 0xc01b7da4e0}, 0xc00007da20?, 0x173d400?)
        google.golang.org/grpc@v1.54.0/server.go:1155 +0x8f
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler({0x1946a20?, 0xa27bad0}, {0x9629490, 0xc01b7da4b0}, 0xc01b7e2310, 0xc007361cc0)
        github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:2115 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003d9a40, {0x9632f80, 0xc00846a1a0}, 0xc0096e0c60, 0xc007f586f0, 0xa1a7a60, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0003d9a40, {0x9632f80, 0xc00846a1a0}, 0xc0096e0c60, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

**Desktop**
 - OS: [Kali-Linux]
 - Version [v2023.1]

when I install with curl https://sliver.sh/install|sudo bash it works but I prefer using apt.

is it something that with golang, Any idea why this happens and how to fix it?

**Comment by rkervella** [comment]
We're not responsible for packaging Sliver for Kali, which is why we recommend installing from the GitHub releases or the install script we provide.
My best bet from this stack trace is that the kali build forgot to set the `version` via `--ldflags`, but that's just a guess.

I'd recommend filing an issue on Kali's bug tracker [here](https://bugs.kali.org/my_view_page.php).

**Comment by moloch--** [comment]
Weird bug though, we've not changed anything afaik recently related to the version/Makefile

**Comment by rkervella** [comment]
As expected, the `version` info is weird (this is on kali rolling):

```shell
kali@kali:~$ sliver-server version
 - kali
```
