### ISSUE TITLE
Timeout on binary generation running in cloud VM

### ISSUE THREAD

**Issue by csgee** [BishopFox/sliver#125]
I am using a cloud based Linux VM to run sliver-server. When trying to generate a sliver, I am getting a timeout message, after about 20-30 minutes of compiling.

Generation works fine on a desktop computer using the same parameters, and runs quicker than 15 minutes.

However, I would like to test the framework using my cloud-based VMs, which are low on CPU. Is there a way to enable compilation on slower CPUs?

**Comment by moloch--** [comment]
You'll want to use `--skip-symbols` when generating the binary. The symbol obfuscation process does require a decent amount of CPU and RAM

**Comment by csgee** [comment]
Right. But what if I actually need to use obfuscation?
Is there a way to increase the timeout timer? Or does it have some critical functionality?

**Comment by moloch--** [comment]
It may still OOM if you don't have enough memory, but you can increase the timeout with `--timeout` but I think this flag is only in the `master` branch so until we mint a new version you'll need to compile from source to get the functionality.

**Comment by moloch--** [comment]
All commands have `--timeout` in `grpc`
