### ISSUE TITLE
generate stager bug

### ISSUE THREAD

**Issue by p1d3er** [BishopFox/sliver#1252]
After modifying the  /root/.sliver/configs/http-c2.json  stager_file_ext 
generate stager Msfvenom  LURI is still the woff suffix.

INFO[2023-05-27T10:03:28+08:00] [sliver/server/msf/msf.go:201] msfvenom [--platform windows --arch x64 --format raw --payload windows/x64/custom/reverse_winhttp LHOST=127.0.0.1 LPORT=8080 EXITFUNC=thread LURI=locales/assets/Inter-Regular.woff]

**Comment by rkervella** [comment]
Closed in #1257
