### ISSUE TITLE
Multiplayer and operator commands are not available anymore

### ISSUE THREAD

**Issue by kernelpanic-bf** [BishopFox/sliver#1263]
**Describe the bug**
Seems that the `multiplayer` and `operator` commands are not available anymore when running the sliver server.
The code that adds these commands is here:
https://github.com/BishopFox/sliver/blob/master/server/console/console.go#L71
But don't think this is actually called or used anywhere, unless I did not notice something.

Will investigate a bit further tomorrow.

**To Reproduce**
1. Clone main branch 
2. Do a `make`
3. Run ./sliver-server
4. Type `multiplayer` or `operator`

**Expected behavior**
Multiplayer should run and enable the operator listener and operator the ability to add operators.

**Screenshots**
```
./sliver-server
[!] Error in HTTP C2 config: implant config must specify at least one stager_files value

    ███████╗██╗     ██╗██╗   ██╗███████╗██████╗
    ██╔════╝██║     ██║██║   ██║██╔════╝██╔══██╗
    ███████╗██║     ██║██║   ██║█████╗  ██████╔╝
    ╚════██║██║     ██║╚██╗ ██╔╝██╔══╝  ██╔══██╗
    ███████║███████╗██║ ╚████╔╝ ███████╗██║  ██║
    ╚══════╝╚══════╝╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝

All hackers gain miracle
[*] Server v1.5.39 - cd9740996aaacb356ed8aca4a94e2a7b5ac753c7
[*] Welcome to the sliver shell, please type 'help' for options

sliver > multiplayer

Error: unknown command "multiplayer" for ""
Run ' --help' for usage.

sliver > operator

Error: unknown command "operator" for ""

Did you mean this?
        operators

Run ' --help' for usage.

sliver > 
```

**Desktop:**
 - OS: Tested on MacOS and Linux
 - Version: Latest commit https://github.com/BishopFox/sliver/commit/cd9740996aaacb356ed8aca4a94e2a7b5ac753c7

**Comment by kernelpanic-bf** [comment]
Pinging @maxlandon in case you would have any feedback on this.

**Comment by maxlandon** [comment]
Looking at it.

**Comment by maxlandon** [comment]
Fixed in this PR: https://github.com/BishopFox/sliver/pull/1264

**Comment by kernelpanic-bf** [comment]
Thanks @maxlandon !
