### ISSUE TITLE
Default prcess spawning easily spotted by EDR

### ISSUE THREAD

**Issue by smeukinou** [BishopFox/sliver#1280]
**Is your feature request related to a problem? Please describe.**
Not a problem, but most probably an oversight when running processes where an extra quote is added to the command line:
https://twitter.com/SBousseaden/status/1665694331116683267?s=20

**Describe the solution you'd like**
Remove that easily identifyable artigact.

**Comment by moloch--** [comment]
Use `--in-process` to bypass, or alternatively anything other than `notepad.exe` tends to not be detected.

**Comment by smeukinou** [comment]
The problem in the tweet is not abaout notepad.exe but about aditional quotes "" added to the command line of notepad.
c:\windows\system32\notepad.exe ""
and that's a clear Sliver ioc.

The problem seems to tome from the arg parsing of prcoess-arguments with GetString that returns "" when no parameter is defined.
eg in execute-assembly.go
        assemblyArgs := args[1:]
	process, _ := cmd.Flags().GetString("process")
	processArgsStr, _ := cmd.Flags().GetString("process-arguments")
	processArgs := strings.Split(processArgsStr, " ")
	inProcess, _ := cmd.Flags().GetBool("in-process")

And then this is passed to startProcess in task_windows.exe and ends up showing in the process command line

func (f *FlagSet) GetString(name string) (string, error) {
	val, err := f.getFlagType(name, "string", stringConv)
	if err != nil {
		return "", err
	}
	return val.(string), nil
}

I did not test that as I don't have acces to a dev env right now, but I think that would kill one of the detection method highlighted by the tweet
