### ISSUE TITLE
Sliver crypto-related stacktrace/panic on update to 1.5.40

### ISSUE THREAD

**Issue by dougthegreat** [BishopFox/sliver#1310]
**Describe the bug**
Sliver crypto-related stacktrace/panic on update to 1.5.40 from 1.5.38

**To Reproduce**
1. Run "update" from 1.5.38
2. Replace old sliver server binary with new one
3. Run sliver-server
4. stacktrace/panic

**Expected behavior**
Sliver-server to start without stacktrace/panic

**Screenshots**
![image](https://github.com/BishopFox/sliver/assets/71608036/71ea7e9e-1ce2-4a9d-833a-363d2237913d)

`root@ip:~# sha256sum sliver-server
20185a48e061bc197cedc3f86910f51a97e9ab054c16b7dc2442a462d7222650  sliver-server`
`root@ip:~# ./sliver-server
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/bishopfox/sliver/server/cli.glob..func4.1()
        github.com/bishopfox/sliver/server/cli/cli.go:119 +0x72
panic({0x17d41e0, 0xc0004132c0})
        runtime/panic.go:884 +0x213
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
        github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xe5
github.com/bishopfox/sliver/server/cli.glob..func4(0xa424ce0?, {0x1a244c9?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/server/cli/cli.go:127 +0x7a
github.com/spf13/cobra.(*Command).execute(0xa424ce0, {0xc000052290, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xa424ce0)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
        github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25
main.main()
`

**Desktop (please complete the following information):**
 - OS: ~20.04.1-Ubuntu SMP
 - Version 5.15.0-1038-aws

**Additional context**

**Comment by moloch--** [comment]
v1.5.40 is unfortunately not backwards compatible due to the need to implement security fixes, remove the old directory `rm -rf ~/.sliver` and then run again.

**Comment by moloch--** [comment]
Yes, not ideal heh.
