### ISSUE TITLE
Update Stagers Wiki for Encrypted Stagers

### ISSUE THREAD

**Issue by LivingInSyn** [BishopFox/sliver#1317]
**Describe the bug**
The information on the encrypted stagers is incorrect. It states that payloads are encrypted with `AES-CBC-128` when the block size is actually determined by the key size. 

**To Reproduce**
1. View: https://github.com/BishopFox/sliver/wiki/Stagers#encrypted-stage-example
2. Check against: https://github.com/BishopFox/sliver/blob/master/util/cryptography.go#L30

**Expected behavior**
Update docs

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Github Wiki
 - Version: Current

**Additional context**
Recommended language to fix:

```
Sliver supports encryption and compression when serving stages. Compression options are `zlib`, `gzip`, and `deflate` (level 9). Encryption is done via AES-CBC with block size determined by the length of the key. Payloads a padded with PKCS7. Since this encryption is primarily for obfuscation we don't really need a more secure cipher mode. 
```

**Comment by moloch--** [comment]
Block size in AES is always 128-bits regardless of key size.

**Comment by moloch--** [comment]
Oh okay it looks like the key size is wrong on the wiki

**Comment by LivingInSyn** [comment]
@moloch-- I don't think you're correct here. It is not always 128 bits:

* https://pkg.go.dev/crypto/aes#NewCipher
* https://github.com/BishopFox/sliver/blob/master/util/cryptography.go#L35 

>>> NewCipher creates and returns a new cipher.Block. The key argument should be the AES key, either 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256.

**Comment by moloch--** [comment]
I think you're confusing block size with key size, the key size can vary, but per the AES specification the block size is always 128-bits.

**Comment by moloch--** [comment]
https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/crypto/aes/cipher.go;l=15

**Comment by moloch--** [comment]
Yeap i've updated the wiki!

**Comment by LivingInSyn** [comment]
hey sorry, not trying to be a pain in the butt but the key in the `stage-listener` command doesn't match the one in the c# sample, and I still think the line "Encryption is done via AES-CBC-128" is not correct

Thanks for bearing with me

**Comment by moloch--** [comment]
Not at all, good catch!
