### ISSUE TITLE
Instance taking forever to compile

### ISSUE THREAD

**Issue by TGH75972** [BishopFox/sliver#1329]
generate --http https://c2f6-2401-4900-1c67-7e*****-29ff-fe60-e********p --save ./instance.exe --os Windows

I have generated an http instance or atleast tried to but it's taking forever to compile and it's been 2 hours or so  but still , any ideas?
I have used ngrok to port forward to port 8888 so that it can work over wan as well

**Comment by moloch--** [comment]
The code obfuscator is typically what requires the most CPU/memory, disabling obfuscation should improve build times, alternatively [external builders](https://github.com/BishopFox/sliver/wiki/External-Builders) can also be used to speed up build times.

**Comment by TGH75972** [comment]
Yes it did it
