### ISSUE TITLE
Please make sure Metasploit Framework >= v6.2 Error

### ISSUE THREAD

**Issue by atanu2679** [BishopFox/sliver#1330]
Please make sure Metasploit Framework >= v6.2....How can i fix this error..

my metasploit version is 6.3

![capture2](https://github.com/BishopFox/sliver/assets/75174754/155245cf-7103-4900-9272-e56b8c17141c)

and why im stuck here can anyone help me
![Capture](https://github.com/BishopFox/sliver/assets/75174754/22c32613-8e16-48dd-8121-cd588232526c)

any solution??

**Comment by rkervella** [comment]
There are some issues with msfvenom recently, I haven't had time to figure it out. See #1289

**Comment by n3rada** [comment]
If you want any help for investigation, tell us what could we do

**Comment by atanu2679** [comment]
> If you want any help for investigation, tell us what could we do

is anyone here to help.....how to fix this man

**Comment by cris-m** [comment]
I am facing the same issue in kali linux. I have the following kali linux VM:
```
Linux kali 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux
```
<img width="1786" alt="Screenshot 2023-08-28 at 20 18 45" src="https://github.com/BishopFox/sliver/assets/29815096/088b7c10-bc6e-4d0a-b3d2-1addd8d0ed4d">

I noticed it takes a lot of memory to start a stager listener (it took me 3 minutes).

**Comment by sohelahmed786** [comment]
Hi, I'm also facing this error, i guess from 1.5 months. It gets stuck in generate stager command and at last gives rpc error. Any fixes yet?

**Comment by atanu2679** [comment]
I fixed this issue

**Comment by Moondog85** [comment]
How did you fix the problem? I'm having the same problem occur when I go to generate stager.

**Comment by n3rada** [comment]
I never fixed it. I developed my own dropper and because Sliver uses the `msfvenom` generation, I use this as step one.
