### ISSUE TITLE
Migrate doesn't take SGN into account

### ISSUE THREAD

**Issue by n3rada** [BishopFox/sliver#1334]
-🖥️`Linux version 6.1.0-kali9-amd64 (devel@kali.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12)`
-🐍`Server v1.5.39 - af46878f8520c0c65bbb1e80d813a9658ba09188`
-🪟`Microsoft Windows 11 Pro - 10.0.22621 N/A Build 22621`

I may not be the most slippery of penguins, but even after 20 minutes I still can't figure out how to use the `migrate` command.

Once I have got a beacon on a lab machine, I wanted to test to migrate from my `.exe` to `firefox.exe` process. Here a stripped output of `ps` command:
```
 3080    1268    DESKTOP-4MU2FO9\TestUser   x86_64   SystemSettings.exe
 3652    1268    DESKTOP-4MU2FO9\TestUser   x86_64   UserOOBEBroker.exe
 5764    10248   DESKTOP-4MU2FO9\TestUser   x86_64   Notepad.exe
 8500    5764    DESKTOP-4MU2FO9\TestUser   x86_64   Notepad.exe
 12532   1268    DESKTOP-4MU2FO9\TestUser   x86_64   dllhost.exe
 8968    1124    DESKTOP-4MU2FO9\TestUser   x86_64   svchost.exe
 7788    6380    DESKTOP-4MU2FO9\TestUser   x86_64   virus.exe
 16488   1980    DESKTOP-4MU2FO9\TestUser   x86_64   firefox.exe
 17032   1268    DESKTOP-4MU2FO9\TestUser   x86_64   backgroundTaskHost.exe
 12656   1980    DESKTOP-4MU2FO9\TestUser   x86_64   firefox.exe
 16976   1980    DESKTOP-4MU2FO9\TestUser   x86_64   firefox.exe
 14964   3476                               x86_64   audiodg.exe
 17176   1980    DESKTOP-4MU2FO9\TestUser   x86_64   firefox.exe
 15056   1980    DESKTOP-4MU2FO9\TestUser   x86_64   firefox.exe
 2304    1980    DESKTOP-4MU2FO9\TestUser   x86_64   firefox.exe
```

And my tries:
![image](https://github.com/BishopFox/sliver/assets/72791564/afd38a0b-c3d4-4692-8e50-702d1fc306ef)

Since I couldn't find any explanations on the Internet, I decided to open this issue so that the next people could understand how to use `migrate`. 

I'm sure I must be missing something rather simple. I look forward to hearing from you, and thank you in advance for your time.

**Comment by n3rada** [comment]
@rkervella any idea?

**Comment by rkervella** [comment]
Try with `-S`.

**Comment by n3rada** [comment]
Both don't work. Here's a screenshot to test the name:
![image](https://github.com/BishopFox/sliver/assets/72791564/1d467444-f622-4833-98c9-935c87872213)

And the logs doesn't even mention it's execution:

````shell
> sudo tail -f /root/.sliver/logs/sliver.log
ERRO[2023-07-10T22:02:17+02:00] [sliver/server/c2/mtls.go:103] Socket read error EOF
INFO[2023-07-10T22:02:21+02:00] [sliver/server/c2/mtls.go:85] Accepted incoming connection: 192.168.1.75:54450
INFO[2023-07-10T22:02:21+02:00] [sliver/server/handlers/beacons.go:147] Beacon 00a52561-4073-4f49-aa3d-dde373ee177b requested pending task(s)
INFO[2023-07-10T22:02:21+02:00] [sliver/server/handlers/beacons.go:179] Sending 0 task(s) to beacon 00a52561-4073-4f49-aa3d-dde373ee177b
ERRO[2023-07-10T22:02:22+02:00] [sliver/server/c2/mtls.go:165] Socket error (read msg-length): EOF
ERRO[2023-07-10T22:02:22+02:00] [sliver/server/c2/mtls.go:103] Socket read error EOF
INFO[2023-07-10T22:02:27+02:00] [sliver/server/c2/mtls.go:85] Accepted incoming connection: 192.168.1.75:54451
INFO[2023-07-10T22:02:27+02:00] [sliver/server/handlers/beacons.go:147] Beacon 00a52561-4073-4f49-aa3d-dde373ee177b requested pending task(s)
INFO[2023-07-10T22:02:27+02:00] [sliver/server/handlers/beacons.go:179] Sending 0 task(s) to beacon 00a52561-4073-4f49-aa3d-dde373ee177b
ERRO[2023-07-10T22:02:28+02:00] [sliver/server/c2/mtls.go:165] Socket error (read msg-length): EOF
ERRO[2023-07-10T22:02:28+02:00] [sliver/server/c2/mtls.go:103] Socket read error EOF
INFO[2023-07-10T22:02:32+02:00] [sliver/server/c2/mtls.go:85] Accepted incoming connection: 192.168.1.75:54452
INFO[2023-07-10T22:02:32+02:00] [sliver/server/handlers/beacons.go:147] Beacon 00a52561-4073-4f49-aa3d-dde373ee177b requested pending task(s)
INFO[2023-07-10T22:02:32+02:00] [sliver/server/handlers/beacons.go:179] Sending 0 task(s) to beacon 00a52561-4073-4f49-aa3d-dde373ee177b
ERRO[2023-07-10T22:02:33+02:00] [sliver/server/c2/mtls.go:165] Socket error (read msg-length): EOF
ERRO[2023-07-10T22:02:33+02:00] [sliver/server/c2/mtls.go:103] Socket read error EOF
INFO[2023-07-10T22:02:38+02:00] [sliver/server/c2/mtls.go:85] Accepted incoming connection: 192.168.1.75:54453
INFO[2023-07-10T22:02:38+02:00] [sliver/server/handlers/beacons.go:147] Beacon 00a52561-4073-4f49-aa3d-dde373ee177b requested pending task(s)
INFO[2023-07-10T22:02:38+02:00] [sliver/server/handlers/beacons.go:179] Sending 0 task(s) to beacon 00a52561-4073-4f49-aa3d-dde373ee177b
ERRO[2023-07-10T22:02:39+02:00] [sliver/server/c2/mtls.go:165] Socket error (read msg-length): EOF
ERRO[2023-07-10T22:02:39+02:00] [sliver/server/c2/mtls.go:103] Socket read error EOF
```

Am I using `migrate` with the proper way?

**Comment by rkervella** [comment]
I just realized you're running it from a beacon, not a session. Looks like we have not implemented `migrate` for beacons yet. Try with a session and let me know if that doesn't work. Note that you'll probably need to pass `--disable-sgn/-S` for it to work.

**Comment by n3rada** [comment]
Session implants are noisier, aren't they? Why isn't it possible to send the command implied behind `migrate` as a task to the beacon?

Especially since it's impossible to switch from session to beacon. Once you've got a beacon, how do you migrate processes then? I thought that it could be possible to send an inject command to the beacon.

**Comment by rkervella** [comment]
> Session implants are noisier, aren't they? Why isn't it possible to send the command implied behind migrate as a task to the beacon?

Because it's not implemented in the client yet (an oversight that's all), simple as that. We'll get to it eventually :)
In the meantime you can switch from beacon to session using `interactive`, do your stuff and then use `close` to stop the session and go back to your session.
