### ISSUE TITLE
Error while running the new release v1.5.41

### ISSUE THREAD

**Issue by DrorDvash** [BishopFox/sliver#1347]
**Describe the bug**
Hey, just downloaded the new release version of Sliver - v1.5.41.
While running the server i got an error in "Unpacking assets ..." 
I tried v1.5.39, and it worked properly

 - OS: Ubuntu 22.04.01

```
Unpacking assets ...
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/bishopfox/sliver/server/cli.glob..func4.1()
	github.com/bishopfox/sliver/server/cli/cli.go:119 +0x72
panic({0x17d41e0, 0xc01bc9b400})
	runtime/panic.go:884 +0x213
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
	github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xe5
github.com/bishopfox/sliver/server/cli.glob..func4(0xa424ce0?, {0x1a244c9?, 0x0?, 0x0?})
	github.com/bishopfox/sliver/server/cli/cli.go:127 +0x7a
github.com/spf13/cobra.(*Command).execute(0xa424ce0, {0xc000112250, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xa424ce0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
	github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25
main.main()
	github.com/bishopfox/sliver/server/main.go:43 +0x17
```

**Screenshots**
![image](https://github.com/BishopFox/sliver/assets/8413651/80be6c28-c03f-4df9-8219-01f651aa00a5)

**Comment by rkervella** [comment]
v1.5.40 introduced breaking change, you'll need to delete your old `$HOME/.sliver` directory first before using v1.5.40 or above.

**Comment by sevagas** [comment]
The fix did not work for me I still have the stacktrace. Did it fix your problem @DrorDvash  ?

**Comment by DrorDvash** [comment]
> The fix did not work for me I still have the stacktrace. Did it fix your problem @DrorDvash ?

Yes, it worked for me. I ran with sudo so deleted for both user & root sliver folders:
`rm -rf /home/ubuntu/.sliver*`
`rm -rf /root/.sliver*`

**Comment by sevagas** [comment]
Thank you it works for me too I had forgotten to remove the one in /root
