### ISSUE TITLE
Obfuscation fails for `shared` format

### ISSUE THREAD

**Issue by digital-shokunin** [BishopFox/sliver#135]
**Describe the bug**
This C2 is very buggy if you try following the instructions even the cloning of the project into $GOPATH/src etc doesn't fix things, you have to copy files from src/github.com/BishopFox/sliver/sliver back one directory and manually do a go install for it to find what it needs. Also despite installing mingw when I try to build a binary for windows it fails. (this works with the release version but not the build version).

**To Reproduce**
Generate windows sliver
![image](https://user-images.githubusercontent.com/913856/69285981-22946b80-0bc0-11ea-80da-f27cef063eac.png)

windows.h is in a few locations:
/usr/share/mingw-65/include/windows.h
/usr/x86_64_w64-mingw32/include/windows.h

Despite that it's not looking in the library path provided by the package.

**Comment by rkervella** [comment]
@digital-shokunin please fill out the full bug report template next time. Especially, please provide the full commands used to start and generate the implant.

That being said, there's an open issue (#133 ) which breaks the symbol obfuscation. Please retry with the `--skip-symbols` flag and see if that solves your issue.

One last thing: if you followed the instruction [here](https://github.com/BishopFox/sliver/wiki/Compile-From-Source#from-scratch-no-docker), you would have noticed that you should clone the project into `$GOPATH/src/github.com/bishopfox/sliver` and not `$GOPATH/src/github.com/BishopFox/sliver` (the case matters for Go).

**Comment by digital-shokunin** [comment]
I got it to generate with the skip-symbols. My issue now is the DNS listener is listening on IPv6 only.

**Comment by rkervella** [comment]
I'll close this one when #133 will be fixed

**Comment by moloch--** [comment]
@digital-shokunin if you're looking for a slightly more stable version checkout [releases](https://github.com/BishopFox/sliver/releases), as stated in the main readme this project is currently considered 'alpha' so bugs are to be expected, though we appreciate bug reports especially from `master`.

**Comment by moloch--** [comment]
Temp fix in `master` until we port the build process to modules.
