### ISSUE TITLE
The COFF Loader fails to load BOF in obj format.

### ISSUE THREAD

**Issue by Arks7** [BishopFox/sliver#1355]
Problem:
The COFF Loader fails to load BOF in obj format.

Test environment:
MacOS

Test process:
Using the loader.exe compiled from [https://github.com/trustedsec/COFFLoader ↗](https://github.com/trustedsec/COFFLoader) to load BOF in obj format was successful. However, loading failed in Sliver.
<img width="562" alt="image" src="https://github.com/BishopFox/sliver/assets/82130343/203b6a5e-f6e6-4aca-bbb9-e25999bd7f4a">

Sliver loade err
MAC
<img width="1174" alt="image" src="https://github.com/BishopFox/sliver/assets/82130343/f1c28c39-9960-490b-a190-0a2b546789cf">

<img width="602" alt="image" src="https://github.com/BishopFox/sliver/assets/82130343/6b5ad1c1-14de-4377-b36d-170996c4eab9">

Windows
<img width="1131" alt="image" src="https://github.com/BishopFox/sliver/assets/82130343/2d666498-2a9e-4a0d-a6ea-3e479143d50e">

**Comment by rkervella** [comment]
Looks like it's undocumented, but the extension file name needs to be `.o`, not `.obj`, for the client to understand it's a COFF file and apply the argument parsing logic (even if, in your case, there's no arguments).

**Comment by rkervella** [comment]
I updated the documentation so people don't make the mistake in the future: https://github.com/BishopFox/sliver/wiki/BOF-&-COFF-Support

**Comment by Arks7** [comment]
Thank you
