### ISSUE TITLE
Docker build is failing

### ISSUE THREAD

**Issue by lu4p** [BishopFox/sliver#136]
**Describe the bug**
I cannot build the docker image.

**To Reproduce**
1. `git clone https://github.com/BishopFox/sliver.git`
2. `cd sliver`
3. `sudo ./build.py`
```
...
INFO[0211] [sliver/server/gogo/go.go:101] go cmd: '/root/.sliver/go/bin/go build -trimpath -tags netgo -ldflags -s -w -buildid= -o /root/.sliver/slivers/darwin/amd64/INFORMAL_SPUME/obfuscated/bin/INFORMAL_SPUME .' 
INFO[0219] [sliver/server/generate/slivers.go:117] Saved 'INFORMAL_SPUME' file to database 8774128 byte(s) 
INFO[0219] [sliver/server/generate/slivers.go:96] Saved config for 'INFORMAL_SPUME' 
INFO[0219] [sliver/server/db/db.go:156] No bucket for name "profiles" 
INFO[0219] [sliver/server/db/db.go:163] Created new bucket with name "profiles" (f330ca87-b637-4b09-8883-4adc1230dbec) 
DEBU[0219] [sliver/server/db/db.go:187] Loading db from /root/.sliver/db/buckets/f330ca87-b637-4b09-8883-4adc1230dbec 
INFO[0219] [/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/logger.go:46] All 0 tables opened in 0s 
The command '/bin/sh -c ls -lah && /opt/sliver-server -unpack   && /go/src/github.com/bishopfox/sliver/go-tests.sh' returned a non-zero code: 1

[!] Command did not exit cleanly (256) 
```

**Expected behavior**
The image should build.

**Desktop:**
 - OS: Manjaro Linux
 - Version 18.1.3

**Additional context**
Also tried `sudo docker build . -t sliver` lead to the same result.

**Comment by rkervella** [comment]
Probably `go-tests.sh` failing due to #133

**Comment by lu4p** [comment]
Fixes the issue for me. Maybe setup automated builds via docker hub / github actions to catch when the image doesn't build anymore.

**Comment by rkervella** [comment]
That's the ultimate plan, although in this case we've already identified the issue. Still haven't found the time to fix it =/

**Comment by rkervella** [comment]
Gonna leave this one open until #133 is solved.
