### ISSUE TITLE
Change port to mtls implant

### ISSUE THREAD

**Issue by Ilan-sec** [BishopFox/sliver#138]
Hello,
Very cool app!!! way to go!
I saw that there is a --lport for changing the mtls listener port but I didn't find any way to change the mtls implant port so using 8888 port over firewalls is not working in the most of the cases.

any suggestion how to change it?

Thanks'

Ilan-sec.

**Comment by Ilan-sec** [comment]
I found a work around to change the default mtls 8888 port on client/command/bind-commands.go and on server/generate/binaries.go to the port I want and compile the project again. It works.

**Comment by rkervella** [comment]
@Ilan-sec not sure I got the question right, but you can change the port by specifying it when using the `generate` command, like this:

```
generate --mtls ab.cd:1234
```

**Comment by Ilan-sec** [comment]
great! I looked for --port or something like this and didn't thought this way. thanks!
