### ISSUE TITLE
Can't generate shared (dll) implant - Build failed, no file data

### ISSUE THREAD

**Issue by Ilan-sec** [BishopFox/sliver#139]
generate --format shared --http 1.1.1.21 or  generate --format shared --mtls 1.1.1.21 or generate --format shared --http a.b.com and any version of shard returns: Build failed, no file data.

Idea anyone?

**Comment by lesnuages** [comment]
Add `--skip-symbols`, full obfuscation is broken in the latest versions

**Comment by Ilan-sec** [comment]
> Add `--skip-symbols`, full obfuscation is broken in the latest versions. Related to #133

Sorry, this is answer for other issue.
 btw, I'm doing obfuscation on the latest version. simply move the binary file outside the compilation folder.

**Comment by rkervella** [comment]
Well we're going to need a bit more information than that.
Please provide the following so we can investigate:

- the exact version / commit version of sliver-server you're using
- the log file parts at the time of the error (located at `$HOME/.sliver/logs/sliver.log` by default)
- the exact command line you typed and output from the UI

Also, please fill out the issue template next time. It's really not that complicated and helps us a lot to troubleshoot issues like that.

**Comment by Ilan-sec** [comment]
You are right. It was lake of mingw. I didn't see it on the prequisities. 
apt-get install mingw-w64 did the job.
As for the obfuscation, yes, as I said, you only need to copy the sliver-server binary to another folder and run it from the new location. From this point it makes a long a excellant obfuscation.
