### ISSUE TITLE
Successfully installed sliver c2c tool but i cant connect its server

### ISSUE THREAD

**Issue by ARJUN0601** [BishopFox/sliver#1390]
┌─[✗]─[root@drevello]─[/home/drevello/Desktop]
└──╼ #./install
Installing dependencies using apt...
binutils-mingw-w64 is already the newest version (2.35-2+8.11).
build-essential is already the newest version (12.9).
g++-mingw-w64 is already the newest version (10.2.1-6+24.2).
gpg is already the newest version (2.2.27-2+deb11u2).
mingw-w64 is already the newest version (8.0.0-1).
curl is already the newest version (7.88.1-7~bpo11+2).
git is already the newest version (1:2.39.2-1~bpo11+1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Running from /root
Importing GPG key...
gpg: key 7DF912404449039C: "Sliver <sliver@bishopfox.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Fetching latest Sliver release URLs...
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.41/sliver-client_linux
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.41/sliver-client_linux.sig
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.41/sliver-server_linux
Downloading https://github.com/BishopFox/sliver/releases/download/v1.5.41/sliver-server_linux.sig
Verifying signatures ...
gpg: Signature made Wednesday 12 July 2023 03:11:18 AM IST
gpg:                using RSA key 0ED3900D296CFA0283A4E4667DF912404449039C
gpg: Good signature from "Sliver <sliver@bishopfox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0ED3 900D 296C FA02 83A4  E466 7DF9 1240 4449 039C
gpg: Signature made Wednesday 12 July 2023 03:11:18 AM IST
gpg:                using RSA key 0ED3900D296CFA0283A4E4667DF912404449039C
gpg: Good signature from "Sliver <sliver@bishopfox.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 0ED3 900D 296C FA02 83A4  E466 7DF9 1240 4449 039C
Moving the Sliver server executable to /root/sliver-server...
Setting permissions for the Sliver server executable...
Unpacking the Sliver server...

Sliver  Copyright (C) 2022  Bishop Fox
This program comes with ABSOLUTELY NO WARRANTY; for details type 'licenses'.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'licenses' for details.

Unpacking assets ...
Setting permissions for the Sliver client executable...
Copying the Sliver client executable to /usr/local/bin/sliver-client...
'/root/sliver-client_linux' -> '/usr/local/bin/sliver-client'
Creating a symbolic link for sliver-client at /usr/local/bin/sliver...
Setting permissions for the symbolic link /usr/local/bin/sliver...
Configuring systemd service ...
Starting the Sliver service...
Generating local configs ...
Generating operator configs ...
Generating operator configs for user drevello...
┌─[root@drevello]─[/home/drevello/Desktop]
└──╼ #menuexec "systemctl start sliver"

Executing systemctl start sliver
┌─[root@drevello]─[/home/drevello/Desktop]
└──╼ #sliver
Connecting to localhost:31337 ...
Connection to server failed context deadline exceeded┌─[root@drevello]─[/home/drevello/Desktop]
└──╼ #sliver
Connecting to localhost:31337 ...
Connection to server failed context deadline exceeded┌─[root@drevello]─[/home/drevello/Desktop]
└──╼ #

another problem i noticed that in old version while updating using update cmd while running sliver session it downloads but suddenly it doesnt complete downloading it directly jumps to next step
so i deleted it then i run single liner and here we are it messed up 

OS: PARROT SEC
UNAME:Linux drevello 6.1.0-1parrot1-amd64 #1 SMP PREEMPT_DYNAMIC Parrot 6.1.15-1parrot1 (2023-04-25) x86_64 GNU/Linux

**Comment by ARJUN0601** [comment]
it is saying enabled still it is getting same error

**Comment by ARJUN0601** [comment]
> Seems like the server did not properly start. What does `systemctl status sliver` say?

it is saying enabled still it is getting same error

**Comment by n3rada** [comment]
-🖥️ `Linux version 6.3.0-kali1-amd64 (devel@kali.org) (gcc-12 (Debian 12.3.0-4) 12.3.0, GNU ld (GNU Binutils for Debian) 2.40.50.20230611) #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29)`

I'm joining this thread to say that I have the same problem: sliver won't start.

- `sudo systemctl status sliver`
```shell
● sliver.service - Sliver
     Loaded: loaded (/etc/systemd/system/sliver.service; disabled; preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-08-31 11:44:57 CEST; 1s ago
    Process: 84338 ExecStart=/root/sliver-server daemon (code=exited, status=99)
   Main PID: 84338 (code=exited, status=99)
        CPU: 36ms
```
- `sudo /root/sliver-server daemon`
```shell
stacktrace from panic:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/bishopfox/sliver/server/cli.glob..func5.1()
        github.com/bishopfox/sliver/server/cli/daemon.go:46 +0x72
panic({0x17d41e0, 0xc000422140})
        runtime/panic.go:884 +0x213
github.com/bishopfox/sliver/server/cryptography.ECCServerKeyPair()
        github.com/bishopfox/sliver/server/cryptography/cryptography.go:303 +0xe5
github.com/bishopfox/sliver/server/cli.glob..func5(0xa424fc0?, {0x1a244c9?, 0x0?, 0x0?})
        github.com/bishopfox/sliver/server/cli/daemon.go:54 +0x298
github.com/spf13/cobra.(*Command).execute(0xa424fc0, {0xa50b620, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xa424ce0)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bishopfox/sliver/server/cli.Execute()
        github.com/bishopfox/sliver/server/cli/cli.go:145 +0x25
main.main()
        github.com/bishopfox/sliver/server/main.go:43 +0x17
```

That'll help you better I think. Given the nature of the panic, there may be an issue with a cryptography library or related package, no?

**Comment by n3rada** [comment]
I `rm -rf` every sliver things before running the install script again. 😢

**Comment by n3rada** [comment]
Shouldn't it be asked to the user to clean everything before tho'?

**Comment by chromefinch** [comment]
> $HOME/.sliver

yep! 
that was magic

**Comment by LongWayHomie** [comment]
> I `rm -rf` every `sliver` thing before running the install script again. 😢 Shouldn't the user be asked to clean everything up first? And do it automatically.

Yeah, I think that sliver installer from `https://sliver.sh/install` should ask user to remove .sliver folder from home directory of the user running the script. This issue blocked me from updating server with some stacktrace spewing after manually starting server in terminal. This problem appeared since 1.5.40 version, while all the lower were working without an issue. Removing .sliver directory caused issue to disappear.

**Comment by moloch--** [comment]
That's probably a good idea, we should also add an option to auto-start on boot. I think some folks don't realize the server daemon by default doesn't start on boot.

**Comment by n3rada** [comment]
> @LongWayHomie That's probably a good idea, we should also add an option to auto-start on boot. I think some folks don't realize the server daemon by default doesn't start on boot.

Why not adding a `systemctl enable sliver`?

**Comment by ARJUN0601** [comment]
I prefer manually doing for security reasons and resources reason

**Comment by moloch--** [comment]
Yea I'll probably keep the default as-is and add a flag to auto-start, or prompt the user for their preference.
