### ISSUE TITLE
Domain Fronting

### ISSUE THREAD

**Issue by Ilan-sec** [BishopFox/sliver#140]
Hello,
I have noticed that Domain Fronting ain't works on http/s connections. Although the communication can get from the front domain, e.g AWS to the C&C server but it can't actually fire up the sliver connection.
This feature is top required in penetration testings because going to unknown ip on vps is very suspicious over time.
I thing I represents a lot of people when I'm asking for this important feature. 

Thanks!

**Comment by moloch--** [comment]
Correct the current implementation doesn't really allow for fronting, but it's for sure on our list of features to add in the near future.

**Comment by r00t0v3rr1d3** [comment]
Was discussing today in the Slack, but in the golang http library - you need to specifically reference request.Host when attempting to override the Host field for domain fronting. 

Merlin implemented it here: https://github.com/Ne0nd0g/merlin/commit/4835ac3fa73acd963f578428d1d3e75d5cbb1bab

It was suggested that this could probably be done via the advanced http options.

**Comment by moloch--** [comment]
Ah okay, we should be able to accommodate this via the advanced c2 options.
