### ISSUE TITLE
armory failed

### ISSUE THREAD

**Issue by z0sen** [BishopFox/sliver#1401]
**Describe the bug**
just run `armory` then the sliver-client exit with errors

**Error**

```bash
armory

[*] Fetching 1 armory index(es) ... done!
[*] Fetching package information ... panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1005db8a6]

goroutine 215 [running]:
github.com/bishopfox/sliver/client/command/armory.downloadRequest({0x0, 0x0, 0xc00010be60, 0xd18c2e2800, 0x0}, {0xc000bfc770, 0x69}, 0xc0005e6a70?)
	github.com/bishopfox/sliver/client/command/armory/parsers.go:439 +0x166
github.com/bishopfox/sliver/client/command/armory.GithubArmoryPackageParser(0x10111e2c0?, 0xc000181270, 0x1, {0x0, 0x0, 0xc00010be60, 0xd18c2e2800, 0x0})
	github.com/bishopfox/sliver/client/command/armory/parsers.go:318 +0x325
github.com/bishopfox/sliver/client/command/armory.fetchPackageSignature(0xc0007b34a0?, 0x1022276c0, 0xc000181270, {0x0, 0x0, 0xc00010be60, 0xd18c2e2800, 0x0})
	github.com/bishopfox/sliver/client/command/armory/armory.go:487 +0x410
created by github.com/bishopfox/sliver/client/command/armory.fetchPackageSignatures
	github.com/bishopfox/sliver/client/command/armory/armory.go:445 +0x113
```

**Desktop**
 - OS: macOS
 - Version v1.5.41

**Comment by moloch--** [comment]
Interesting, I'd guess its likely a problem with the machine's internet connection, or your IP may be hitting the GitHub rate limits. However, this shouldn't crash just produce an error.

**Comment by yuunaka1** [comment]
I have faced the same issue today. My workaround to avoid this SEGV issue was to disable concurrency on fetching signatures. 
Below is my quick and dirty workaround:
```
diff --git a/client/command/armory/armory.go b/client/command/armory/armory.go
index bb79fa4..1cc1e2c 100644
--- a/client/command/armory/armory.go
+++ b/client/command/armory/armory.go
@@ -443,14 +443,16 @@ func fetchPackageSignatures(indexes []ArmoryIndex, clientConfig ArmoryHTTPConfig
                        wg.Add(1)
                        armoryPkg.IsAlias = false
                        go fetchPackageSignature(wg, index.ArmoryConfig, armoryPkg, clientConfig)
+                       wg.Wait()
                }
                for _, armoryPkg := range index.Aliases {
                        wg.Add(1)
                        armoryPkg.IsAlias = true
                        go fetchPackageSignature(wg, index.ArmoryConfig, armoryPkg, clientConfig)
+                       wg.Wait()
                }
        }
-       wg.Wait()
+       //wg.Wait()
 }
```
As this workaround significantly slows down signature download speed,
It would be great if we had a proper option to adjust concurrency for poor server environments.

**Comment by kmahyyg** [comment]
Same problem here. Trying to diagnose and RCA.

**Comment by kmahyyg** [comment]
- in client/command/armory/armory.go:439 , `fetchPackageSignatures` function fetches indexes and extensions from github, since this package signatures are stored in a JSON and contain multiple extensions. It would be better if here's some throttle, instead of blindly add worker to WaitGroup. Even though, Go programs run with GOMAXPROCS set to the number of cores available; in prior releases it defaulted to 1.
- As you may see from OP's panic stack trace, in client/command/armory/parsers.go:439, if `err` is not nil, then directly access `resp` will lead to access to a null pointer, so SIGSEGV happened.

@moloch--

**Comment by kmahyyg** [comment]
By the way, I see client/command/armory/parsers.go:400 , 

```
func httpClient(config ArmoryHTTPConfig) *http.Client {
	return &http.Client{
<SNIP>
			Proxy:               http.ProxyURL(config.ProxyURL),
<SNIP>
}
```

If this is set for private armories repository that may need to be accessed via proxy, I totally understand. However, this will make general request to general public armories repository proxy not working, since it's overridden by `nil`.

**Comment by kmahyyg** [comment]
> Interesting, I'd guess its likely a problem with the machine's internet connection, or your IP may be hitting the GitHub rate limits. However, this shouldn't crash just produce an error.

After some diagnose, I suppose this may related to compiler, `-gcflags "all=-l"` add this param when build seems solved issue for me.

**Comment by cybertuxh4xor** [comment]
![Capture](https://github.com/BishopFox/sliver/assets/88122300/6055f5ea-c8e0-4b8e-a44c-41cabdfd2276)
I am running to this issues in kali linux. As some of you probably have not heard Sliver is now being taught in the Certified Red Team Professional course.I do not know how to fix this error, even with the work around i dont how to get "diff --git a/client/command/armory/armory.go b/client/command/armory/armory.go" to work it just errors out and gives me this "diff: unrecognized option '--git'
diff: Try 'diff --help' for more information."

**Comment by moloch--** [comment]
@cybertuxh4xor does it use the version from the Kali package manager, or the version from GitHub?

**Comment by cybertuxh4xor** [comment]
The one liner from GitHub

**Comment by h8handles** [comment]
I have the same issue using Kalie repo, build from source and the oneliner. This is when trying to install any armory program. 

`sliver > armory install rubeus

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9d86a6]

goroutine 14 [running]:
github.com/bishopfox/sliver/client/command/armory.downloadRequest({0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, {0xc0007d2050, 0x4a}, 0x26d9480?)
	github.com/bishopfox/sliver/client/command/armory/parsers.go:439 +0x166
github.com/bishopfox/sliver/client/command/armory.GithubAPIArmoryIndexParser(0x26d9480, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0})
	github.com/bishopfox/sliver/client/command/armory/parsers.go:219 +0x45d
github.com/bishopfox/sliver/client/command/armory.fetchIndex(0x26d9480, {0x0, 0x0, 0x0, 0xd18c2e2800, 0x0}, 0x0?)
	github.com/bishopfox/sliver/client/command/armory/armory.go:427 +0x34e
created by github.com/bishopfox/sliver/client/command/armory.fetchIndexes
	github.com/bishopfox/sliver/client/command/armory/armory.go:382 +0x78
`

same error on any armory install

**Comment by RafBishopFox** [comment]
I wrote a fix that should _hopefully_ address this issue by limiting concurrent fetches from the armory for indexes and package signatures to 10 requests at a time. I picked that number arbitrarily, so we may need to tweak it if we continue to see issues. It slows down fetching signatures from Github a little, but it is still relatively quick. We could also make that number configurable.

In addition to that, I wrote a check to make sure the response we get from Github is not `nil` which should stop the panic.

The fix is currently in the branch with all of the other improvements to the armory functionality in the client that I am making (`v1.6.0/private-armories`), but I could submit a PR for it into `master` and backport it to v1.5.x if this needs to be urgently fixed.

**Comment by h8handles** [comment]
> I wrote a fix that should _hopefully_ address this issue by limiting concurrent fetches from the armory for indexes and package signatures to 10 requests at a time. I picked that number arbitrarily, so we may need to tweak it if we continue to see issues. It slows down fetching signatures from Github a little, but it is still relatively quick. We could also make that number configurable.
> 
> In addition to that, I wrote a check to make sure the response we get from Github is not `nil` which should stop the panic.
> 
> The fix is currently in the branch with all of the other improvements to the armory functionality in the client that I am making (`v1.6.0/private-armories`), but I could submit a PR for it into `master` and backport it to v1.5.x if this needs to be urgently fixed.

did a git pull and can confirm i can now download rubeus!

**Comment by mateuszismyname** [comment]
I had the same issue and running  `armory update` first fixed the problem.

**Comment by PatxaSec** [comment]
Armory panic on Kali Linux on both apt binaries and github ones.   

<img width="954" height="319" alt="Image" src="https://github.com/user-attachments/assets/5d334747-045a-4ffa-82c5-4542600ed28f" />
