### ISSUE TITLE
Crack Command

### ISSUE THREAD

**Issue by runesage** [BishopFox/sliver#1408]
**Describe the bug**
I noticed there is a crack command in the codebase but it does not seem to appear in the client/server as an option. I also didn't see any wiki pages on it so was unsure if this was an active feature or not. When I try running it via "crack" it just throws an unknown command error. This is on the most recent version. Is this feature actually active in the server/client or is this some phantom code not active/ready yet?

[*] Client v1.5.41 - f2a3915c79b31ab31c0c2f0428bbd53d9e93c54b - linux/amd64
    Compiled at 2023-07-11 21:31:10 +0000 UTC
    Compiled with go version go1.20.5 linux/amd64

[*] Server v1.5.41 - f2a3915c79b31ab31c0c2f0428bbd53d9e93c54b - linux/amd64
    Compiled at 2023-07-11 21:31:10 +0000 UTC

**Comment by moloch--** [comment]
This is an unreleased/incomplete feature, it will part of the v1.6 release (note: the default branch is the dev branch, use release branches for documented/stable features).

But it's the GPU/hashcat cracking integration feature that can automatically queue dumped hashes/etc. for cracking.

**Comment by runesage** [comment]
Ah apologies then. I came across it because I was looking into writing up a similar thing with the gRPC library you provided to tie into a Hashtopolis cluster using the Hashtopolis api. I regularly do CTF events and we normally use Hashtopolis to cluster everyone’s computers together for the event so was trying to automate my laziness away. I completely overlooked which branch I was looking at because of how intrigued I was. I will be curious to see how this works out then as you all work on it!

**Comment by moloch--** [comment]
We're hoping to have an official release in the fall, but depends on external factors like work load from the day job, etc.
