### ISSUE TITLE
Post callback actions

### ISSUE THREAD

**Issue by EdwardDali** [BishopFox/sliver#1412]
Is there any way to automate some actions after obtaining a callback from a beacon? Maybe blue will catch the connection in 15 minutes but doing some stuff automatically could still be considered successful actions on objectives.
For instance to upload some files (red team was here.txt) or maybe execute an implant for persistence? Or maybe to obtain automatically some info such as whoami, pwd, ipconfig ?

**Comment by moloch--** [comment]
Also https://github.com/moloch--/sliver-py
