### ISSUE TITLE
rpc error: code = Unknown desc = exit status 1

### ISSUE THREAD

**Issue by rfarah21** [BishopFox/sliver#1417]
I have modified the source code of the implant to add some tricksy av evasion techniques built directly into the implant. I compile the server with the provided make file. I launch the server and all is fine until i go to generate an implant. It returns the above error but does not crash the program. Did i miss something while compiling ?
Update:
 I comment out my changes and the recompile and it all works fine. Instead i add a harmless printf statement and i get the error again
 
![Screenshot from 2023-09-29 19-54-14](https://github.com/BishopFox/sliver/assets/98347396/e80ed0d1-926f-4501-a56e-e523fd261d3c)

**Comment by rkervella** [comment]
> Did i miss something while compiling ?

Probably? Check the server logs to see what the error actually is. We can't really help if you don't share info on what you modified and where. This kind of error usually happens when the implant code is rendered, so you probably missed something in the implant code. It can go from an unused variable to missing importing a package, or on non-used import.

**Comment by rfarah21** [comment]
It did generate a implant when i added the debug flag strangely enough. I am compiling it under Linux though could that possibly be the source of all this shenanigans ?

**Comment by rkervella** [comment]
Check your screenshot, the error is pretty clear: you forgot to import `log`.

**Comment by rfarah21** [comment]
Sorry I didnt get back to you sooner but I am working on a fresh build and everything works smoothly now. Yeah I figued I axed one of those comments and everything went south. Go isn't my main programming language so its a bit of struggle. Much thanks anyways !
