### ISSUE TITLE
[Enhancement] Sliver klist BOF

### ISSUE THREAD

**Issue by Cyb3rC3lt** [BishopFox/sliver#1433]
I noticed that Sliver didn't have a klist BOF and every time I ran `execute -o klist` Defender killed my session.

To rectify this I ported OutflankNL's Cobalt Strike BOF to Sliver.

Source code including json and Makefile can be found here:

https://github.com/Cyb3rC3lt/SliveryArmory/tree/main/klist/source

Screenshots here:

https://github.com/Cyb3rC3lt/SliveryArmory/tree/main/klist

Hope this helps

**Comment by c2biz** [comment]
`klist` has been added in [C2-Tool-Collection v0.0.8](https://github.com/sliverarmory/C2-Tool-Collection/releases/tag/v0.0.8)

**Comment by Cyb3rC3lt** [comment]
Thank you, will close this
