### ISSUE TITLE
Generating a linux implant tries to include windows.h

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#144]
**Describe the bug**
Using master, when trying to generate a linux/amd64 sliver implant, it attempts to import windows.h, which obviously results in a compiler error.  Disabling obfuscation does avoid the error, so it does seem to be related to obfuscation.

I acknowledge this might be #133 or #135, but it doesn't seem to be exactly the same, and it's not clear to me how the obfuscation results in this compile error.  #135 deals with a shared windows format, not an exe on linux, and #133 is a different error.

MingW is listed as an *optional* dependency, so I don't think should be required for a Linux implant.

**To Reproduce**
1. Build sliver-server from master on Debian Testing
2. Run `generate -t localhost:9999 -o linux`
3. Receive compiler error:

```
./dllmain.h:1:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
```

**Expected behavior**
Linux implants should not depend on windows.h.

**Screenshots**
```
sliver > generate -t localhost:9999 -o linux

[*] Generating new linux/amd64 Sliver binary
[*] Symbol obfuscation is enabled.
[*] This process can take awhile, and consumes significant amounts of CPU/Memory
 ⠼  Compiling, please wait ...In file included from /home/user/.sliver/slivers/linux/amd64/SLEEPY_FOUNTAIN/obfuscated/src/github.com/bishopfox/sliver/s5.go:3:0:
./dllmain.h:1:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
cgo failed: [go tool cgo -objdir /tmp/github.com_bishopfox_sliver_C812431175 -- -I /tmp/github.com_bishopfox_sliver_C812431175 s5.go]: exit status 1
[*] Build completed in 00:00:05
[!] Build failed, no file data
```

**Desktop (please complete the following information):**
 - OS: Debian Testing

**Additional context**

**Comment by Matir** [comment]
The error persists even with the `mingw-w64` package installed.  (Unsurprisingly, as `gcc` would not be looking for this in the include paths for a linux build.)

**Comment by lesnuages** [comment]
Surely related to #133. Try with `--skip-symbols`.

**Comment by Matir** [comment]
It does work with `--skip-symbols`, so if it's purely a duplicate of #133, feel free to close, just wanted to raise the issue in case it was different, since the error message is different.

**Comment by rkervella** [comment]
It's not really a duplicate, just a side effect sadly. There's a bunch of open issues related to that, which I'd like to close once we get #133 closed.

**Comment by rkervella** [comment]
@moloch-- proposed patch:
```
diff --git a/server/generate/binaries.go b/server/generate/binaries.go
index 1fd6a3b..f296fe2 100644
--- a/server/generate/binaries.go
+++ b/server/generate/binaries.go
@@ -432,6 +432,9 @@ func renderSliverGoCode(config *SliverConfig, goConfig *gogo.GoConfig) (string,
                var sliverCodePath string
                dirName := filepath.Dir(boxName)
                var fileName string
+               if !config.IsSharedLib && config.GOOS != "windows" && boxName == "dllmain.go" {
+                       continue
+               }
                if config.Debug || strings.HasSuffix(boxName, ".c") || strings.HasSuffix(boxName, ".h") {
                        fileName = filepath.Base(boxName)
                } else {
```
