### ISSUE TITLE
Implement asynchronous communication model

### ISSUE THREAD

**Issue by cha0tic87** [BishopFox/sliver#146]
**Is your feature request related to a problem? Please describe.**
The generic beacon home isn't ideal and could trip security systems that are configured to watch for this sort of regular behavior.

**Describe the solution you'd like**
Asynchronous communications model akin to Cobalt Strike whereby commands are stored, fetched and executed according to a predetermined timeout period.

**Describe alternatives you've considered**
Sleep and execute - its bulky and ugly.

**Additional context**
N/A

**Comment by hayasec** [comment]
Is your feature request related to a problem? Please describe.
The generic beacon home isn't ideal and could trip security systems that are configured to watch for this sort of regular behavior.

Describe the solution you'd like
Asynchronous communications model akin to Cobalt Strike whereby commands are stored, fetched and executed according to a predetermined timeout period.

Describe alternatives you've considered
Sleep and execute - its bulky and ugly.

Additional context
N/A

Same Issue :)

**Comment by moloch--** [comment]
This will be a feature in v1.5.0
