### ISSUE TITLE
Request function description about ioc

### ISSUE THREAD

**Issue by zezezez** [BishopFox/sliver#1491]
can' you  give me a description  about commands "upload --ioc" and "hosts ioc"?

I just want to know when and how they can be used . Can you give me a sample example, thanks .

![1](https://github.com/BishopFox/sliver/assets/52458706/278df07f-4b22-48d4-9c1b-76d21f03c4ac)
![2](https://github.com/BishopFox/sliver/assets/52458706/ef3b3830-f96e-4689-89b5-8d051680cf76)

**Comment by moloch--** [comment]
When uploading a file to a remote host you can have Sliver track it as an "IOC"

```
upload --ioc ./foo.exe C:\\Users\\Target\\foo.exe
```

This will add the `foo.exe` path and file hash into the Sliver server's database, current entries can be listed using `hosts ioc`. At the end of an engagement this can be helpful to ensure proper cleanup is performed.

**Comment by zezezez** [comment]
Are these functions not yet implemented or will it be implemented ?
I hava a try，but I don't get an expected  result.

![3](https://github.com/BishopFox/sliver/assets/52458706/57731435-e88d-4b0a-bfe4-de92e78b59da)

**Comment by moloch--** [comment]
Yea, that looks like a bug.

**Comment by moloch--** [comment]
Merged into `master`
