### ISSUE TITLE
Obfuscation broken on master

### ISSUE THREAD

**Issue by rkervella** [BishopFox/sliver#152]
**Describe the bug**
Both the obfuscation processes (symbols obfuscation and string obfuscation) are broken as of 9cb3dbcd.

**To Reproduce**
1. clone the latest master code
2. run `./sliver-server`
3. run `generate --mtls 1.2.3.4` or `generate --skip-symbols --mtls 1.2.3.4`

**Expected behavior**
Sliver implant generated

**Output and Logs**
```
All hackers gain persist
[*] v0.0.7 - c8d2a7b9b2ad490da8d579ca2f3caab050f15a23 - Dirty
[*] Welcome to the sliver shell, please type 'help' for options

sliver > generate --save /tmp --skip-symbols --mtls 172.16.241.1

[*] Generating new windows/amd64 Sliver binary
[!] Symbol obfuscation is disabled
[*] Build completed in 00:00:00
[!] Build failed, no file data

sliver >  
```

```
...
INFO[0016] [/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314] PATH=/root/.sliver/go/bin
INFO[0016] [/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314] --- stdout ---

INFO[0016] [/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314] --- stderr ---
can't load package: package github.com/bishopfox/sliver:
s70.go:1:1: expected 'package', found 'EOF'

INFO[0016] [/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:285] exit status 1
...
```
**Desktop (please complete the following information):**
 - OS: Linux
 - Version: c8d2a7b9b2ad490da8d579ca2f3caab050f15a23
 - Go Version: 1.14

**Comment by rkervella** [comment]
Works well with 9e0523ad, stops working on 4d105b1.

**Comment by moloch--** [comment]
Fixed in https://github.com/BishopFox/sliver/commit/f1d537c2cc39626bc306990baa150e333cbc9cd1
