### ISSUE TITLE
Sliver DNS C2

### ISSUE THREAD

**Issue by haha150** [BishopFox/sliver#1521]
**Describe the bug**
When i follow the wiki on usage of DNS C2, i seem to not get a session working, it gives me "refused". Am i missing something?

https://sliver.sh/docs?name=HTTPS+C2

12:13:30.789333 IP ns3.**.net.60725 > 172.**.**.159.domain: 43443 TXT? 1BD5t1aczSfpGeP7jTiK4WaNZNgBYEcQKdv9hd4VEnfS5JH56uMnhHd7HEArrxW.GujeXh74KyxtnDcw9ZKwtMFjtgY8WxZ94qSwvt4wFCRBFmHKZQc3y3Lih7Y3Rqe.RTKKpiHmQUy6hXEzrpkFqrhaq23oxyBiGiZTVRsYh5RghCwpA4NqvZNeATpgPkj.zA9hSHDe49DLyQPyZV7xuarWH5pt53MVwNXjixdmMkoH3X.1.*******.net. (270)
12:13:30.789926 IP 172.**.**.159.domain > ns3.**.net.60725: 43443 Refused*- 0/0/0 (270)

**To Reproduce**
1. dns --domains 1.*******.net.
2. generate beacon --dns 1.*******.net. -d
3. run beacon

**Expected behavior**
I would like a C2 channel established

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.5.41

**Additional context**

**Comment by moloch--** [comment]
There's a bug in the most recent version, use v1.5.39

**Comment by miszr** [comment]
@haha150: This issue should be resolved in the recent 1.5.42 release.

@moloch--: This issue probably needs closing.
