### ISSUE TITLE
Generate error on Windows server

### ISSUE THREAD

**Issue by greyworm11** [BishopFox/sliver#1564]
When trying to create an implant with the generate command, an error occurs: rpc error: code = Unknown desc = invalid compiler target: windows/amd64.

I run the following command:
generate --mtls 192.168.56.1 --os windows --arch amd64
And get the error, what should i do? Server runs using cmd with administration privelleges. 

**Expected behavior**
No error, generating implant.

**Screenshots**
![изображение](https://github.com/BishopFox/sliver/assets/86468565/0b8c2d2b-fa54-4ddb-8ba3-cff9abd0866e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 x64

**Comment by moloch--** [comment]
The Windows server isn't well tested, strongly recommend using Linux or WSL, that said this is a bug in the compiler compatibility checks and we'll get it fixed.

**Comment by greyworm11** [comment]
> The Windows server isn't well tested, strongly recommend using Linux or WSL, that said this is a bug in the compiler compatibility checks and we'll get it fixed.

ty, works perfectly in kali.

**Comment by Ly4j** [comment]
The error still occurs on the server under Windows. When will it be resolved? Thank you very much.
