### ISSUE TITLE
Readline lib eats backslash characters

### ISSUE THREAD

**Issue by rkervella** [BishopFox/sliver#1567]
The readline lib we're using in `master` prevents users to input `\` characters. They don't get displayed but a non-printable character seems to be inserted instead.

**Comment by RafBishopFox** [comment]
@rkervella I think I identified the issue and submitted a [PR upstream](https://github.com/reeflective/readline/pull/61). I tested my fix with Sliver, and it seems to restore the behavior back to what we have in the current release version:
![image](https://github.com/BishopFox/sliver/assets/84349012/3b4c9be8-2b7f-464a-9fd9-224146b83a2d)
![image](https://github.com/BishopFox/sliver/assets/84349012/9772f428-7d55-4b2a-8b38-cb4a8432845e)

**Comment by rkervella** [comment]
Thanks I'll have a look today.
