### ISSUE TITLE
Implement kick-player functionality

### ISSUE THREAD

**Issue by hypnoticpattern** [BishopFox/sliver#157]
**Is your feature request related to a problem? Please describe.**
The `kick-player` command is not implemented.

**Describe the solution you'd like**
When I run `kick-player` the server should remove the certificate from the DB. Further attempts made by the operator to reconnect to the server should be denied. 
Since the client certificate will remain valid the server should also check the DB and verify the operator public certificate is still present before granting access. At the moment the verification is made checking the certificate chain and extracting the operator name from the certificate property `CommonName`.

**Describe alternatives you've considered**
An alternative would be to revoke the operator certificate when the operator is kicked out from the server.

**Additional context**
NA

**Comment by moloch--** [comment]
We are planning this, I'm in the middle of porting everything to gRPC so we'll likely hold off on implementing this until that work is completed since the cert validation/revocation will need to be altered slightly.

**Comment by hypnoticpattern** [comment]
I implemented the function for my own instance and I was thinking to contribute. Should I hold on that?

**Comment by moloch--** [comment]
If you have a working implementation feel free to send us a PR, that would be greatly appreciated! There's still a ways to go on the gRPC port still, so it would be nice to have a functional `kick-player` until that is compelted!
