### ISSUE TITLE
i am facing armory extension installation error in linux

### ISSUE THREAD

**Issue by secretredhacker** [BishopFox/sliver#1574]
[server] sliver > armory install remote-adduser

[!] 
Failed to install file: archive path './addusertogroup.x64.o' is empty
[!] Failed to install extension 'remote-adduser': failed to install extension

**Comment by c2biz** [comment]
This has been fixed in [CS-Remote-OPs-BOF v0.0.7](https://github.com/sliverarmory/CS-Remote-OPs-BOF/releases/tag/v0.0.7)
