### ISSUE TITLE
Multiplayer Mode not functioning (context deadline exceeded)

### ISSUE THREAD

**Issue by l4rm4nd** [BishopFox/sliver#1600]
**Describe the bug**
I've installed the latest sliver c2 (v1.5.42) on a Debian 12.5 (6.1.76-1) as well as Ubuntu 22.04 LTS (5.15.0-97-generic) Linux machine.

Followed the documentation, used the bash install script and created a systemd service, which successfully runs and works. On the sliver server, I can successfully use `sliver` and `sliver-server` to access sliver or create operator profiles.

The multiplayer mode does not work though. Operaters always get a `Connection to server failed context deadline exceeded` error message when trying to connect. I've validated the sliver C2 IP address and default port 31337.

The sliver.service is up and running:

````
me@sliver-c2:~/.sliver/configs$ sudo systemctl status sliver.service
● sliver.service - Sliver
     Loaded: loaded (/etc/systemd/system/sliver.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-03-15 17:38:32 UTC; 2min 7s ago
   Main PID: 55167 (sliver-server)
      Tasks: 7 (limit: 4558)
     Memory: 7.9M
        CPU: 139ms
     CGroup: /system.slice/sliver.service
             └─55167 /root/sliver-server daemon

Mar 15 17:38:32 sliver-c2 systemd[1]: Started Sliver.
````

The 31337 multiplayer port is opened and available on IPv4 and IPv6 (netstat shows ipv6 only but ipv4 also binded):

````
me@sliver-c2:~/.sliver/configs$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::31337                :::*                    LISTEN      55167/sliver-server
````

The TCP port is available when port scanning with nmap from the operator machine:

````
╰─○ nmap -sS -Pn 192.168.178.250 -p 31337                                    
Starting Nmap 7.94SVN ( https://nmap.org ) at 2024-03-15 18:27 CET
Nmap scan report for 192.168.178.250
Host is up (0.011s latency).

PORT      STATE SERVICE
31337/tcp open  Elite
MAC Address: EE:2F:F6:2D:68:74 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 0.23 seconds
````

Already tried:
- restarting the sliver.service via `sudo systemctl restart sliver.service`. No success.
- creating new operator profiles. No success.
- deleting the ~/.sliver directory and reinstall or unpack data via `sliver-server`. No success.
- changed the sliver.service to use another port via `ExecStart=/root/sliver-server daemon --lport 9999`. No success.

Is this a bug or what am I doing wrong?

**Comment by moloch--** [comment]
I'm fairly confident it's not a bug, and its something with your setup though I'm not exactly sure what's wrong. The `Connection to server failed context deadline exceeded` error means that the TCP connection cannot be established, since nmap reports the port is open maybe double check application firewalls on the client that may be preventing the egress connection to the server.

**Comment by rkervella** [comment]
How did you generate the multiplayer credentials for your operators?

**Comment by l4rm4nd** [comment]
> How did you generate the multiplayer credentials for your operators?

I've used the following commands on the sliver c2 server:

````
sliver-server operator --name operator1 --lhost 192.168.178.250 --save /tmp/operator1.cfg
````

Then copied the operator1.cfg to the operator machine (kali linux):

````
# download the sliver client binary
sudo wget -O /usr/local/bin/sliver https://github.com/BishopFox/sliver/releases/download/v1.5.42/sliver-client_linux && sudo chmod 755 /usr/local/bin/sliver
 
# create new dirs for sliver configs
mkdir -p ~/.sliver-client/configs
# paste the operator config
subl ~/.sliver-client/configs/operator1.cfg
````

Then connect:

````
╰─○ sliver
Connecting to 192.168.178.250:31337 ...
Connection to server failed context deadline exceeded
````

I will try using another operater machine (kali). Maybe VMWare behaves strange.

**Comment by l4rm4nd** [comment]
> > How did you generate the multiplayer credentials for your operators?
> 
> I've used the following commands on the sliver c2 server:
> 
> ```
> sliver-server operator --name operator1 --lhost 192.168.178.250 --save /tmp/operator1.cfg
> ```
> 
> Then copied the operator1.cfg to the operator machine (kali linux):
> 
> ```
> # download the sliver client binary
> sudo wget -O /usr/local/bin/sliver https://github.com/BishopFox/sliver/releases/download/v1.5.42/sliver-client_linux && sudo chmod 755 /usr/local/bin/sliver
>  
> # create new dirs for sliver configs
> mkdir -p ~/.sliver-client/configs
> # paste the operator config
> subl ~/.sliver-client/configs/operator1.cfg
> ```
> 
> Then connect:
> 
> ```
> ╰─○ sliver
> Connecting to 192.168.178.250:31337 ...
> Connection to server failed context deadline exceeded
> ```
> 
> I will try using another operater machine (kali). Maybe VMWare behaves strange.

I've used a different operator machine (blackbuntu VM on a proxmox server) and get the same behaviour. I can successfully nmap the 31337 tcp port but connecting yields the context deadline exceeded again.

This error message occurs on two separate sliver c2 server installations. One on Ubuntu and another on Debian. Both latest versions. That's really strange. 

Just installed sliver via:

````
curl https://sliver.sh/install | sudo bash
`````

and the systemd service looks like this:

````
[Unit]
Description=Sliver
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=on-failure
RestartSec=3
User=root
ExecStart=/root/sliver-server daemon

[Install]
WantedBy=multi-user.target
````

**Comment by rkervella** [comment]
Can you check the server logs in `~/.root/sliver/logs/sliver.log` on the machine running the sliver server? If the packets make it to the server and it's refusing the connection you should see something in there.

**Comment by rkervella** [comment]
Well here you go:
```
"ServerHandshake(\"192.168.178.82:45770\") failed: remote error: tls: bad certificate"
```

This means your credentials are not valid. Couple of possible reasons, the most plausible one being the `sliver-server` binary that created the credentials was ran under a different user and used a different `SLIVER_ROOT_DIR`.

**Comment by l4rm4nd** [comment]
> Well here you go:
> 
> ```
> "ServerHandshake(\"192.168.178.82:45770\") failed: remote error: tls: bad certificate"
> ```
> 
> This means your credentials are not valid. Couple of possible reasons, the most plausible one being the `sliver-server` binary that created the credentials was ran under a different user and used a different `SLIVER_ROOT_DIR`.
> 
> If your `sliver-server` is running as `root`, you should run the `sliver-server operator --name operator1 --lhost 192.168.178.250 --save /tmp/operator1.cfg` command as `root` too.

Wow, that's the issue!

Once using sudo to create the operator config, the connection works flawlessly. 

````
sudo sliver-server operator --name operator1 --lhost 192.168.178.250 --save /tmp/operator1.cfg
````

Sorry for the inconvenience guys. Many thanks for the fast help!
