### ISSUE TITLE
`armory install` drives me crazy with repetition of `? Overwrite current install (y/N)`

### ISSUE THREAD

**Issue by n3rada** [BishopFox/sliver#1609]
Hi maintainers,

Using the `./sliver-server` version `Server v1.5.39 - 6443aaba3ddfc896ff5eb1bf0f2e5339064afe32` and simply wanting to either download all with a `armory install all` or just one bundle with `armory install windows credentials` leads to a repetitive and incisive request for confirmation:
```shell
sliver > armory install windows-credentials

? Overwrite current install? No
? Overwrite current install? No
? Overwrite current install? No
? Overwrite current install? Yes
[*] Installing extension 'credman' (v1.0.7) ...
? Overwrite current install? No
[*] Installing extension 'chromiumkeydump' (v0.0.2) ...
? Overwrite current install? (y/N)
```

I haven't found a way to make a `-y` like with `apt`. I don't think it's that complicated to implement, is it?

**Comment by moloch--** [comment]
Yeap we're aware of this bug, it's very annoying. We have a bunch of updates coming to armory soon though and this should get fixed as part of that!

**Comment by n3rada** [comment]
I feel relieved, thanks!

**Comment by moloch--** [comment]
https://github.com/BishopFox/sliver/pull/1633
