### ISSUE TITLE
Exec format error on install

### ISSUE THREAD

**Issue by HughMungis** [BishopFox/sliver#1618]
Got this error attempting to install
```
Setting permissions for the Sliver server executable...
Unpacking the Sliver server...
bash: line 129: /root/sliver-server: cannot execute binary file: Exec format error
```

Running kali on a NanoPi NEOPLUS 2. Fresh install.

**Comment by rkervella** [comment]
I assume the NanoPI is an ARM board. Looks like you're trying to run the amd64 build on it, which results in this error. We don't currently provide releases for Linux ARM, so you'll have to build the server yourself if you want to run it on this platform. You can build from the `master` branch to get ARM support for the client and server, but keep in mind it's a development branch, so expect some bugs here and there.
