### ISSUE TITLE
'ls' does not report info on root directory '/'

### ISSUE THREAD

**Issue by spenceradolph** [BishopFox/sliver#1629]
**Describe the bug**
Doing an `ls` on a directory only shows properties on the child files/dirs. Normally, you could run `ls` on the parent directory if you really wanted that data on it, but for the '/' directory this is impossible. Perhaps '.' and '..' are being filtered.

**To Reproduce**
1. `use <session>`
2. `ls /`
4. Unable to see permissions or modified time on '/'

**Expected behavior**
It should be possible to see modified time of '/' directory using `ls` and not relying on something like `execute`.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**
Here is a listing of a file. Note that the header shows <parent_dir> (1 item, size of file)
```
sliver (FUNNY_DRIVEWAY) > ls /etc/rsyslog.d/20-ufw.conf

/etc/rsyslog.d (1 item, 314 B)
==============================
-rw-r--r--  root:root  20-ufw.conf  314 B  Sun Sep 19 00:07:33 -0500 2021
```
Here is a listing of a non-root directory. Note that the header shows <parent_dir> (# item(s), size of combined files)
```
sliver (FUNNY_DRIVEWAY) > ls /etc/rsyslog.d

/etc/rsyslog.d (2 items, 1.4 KiB)
=================================
-rw-r--r--  root:root  20-ufw.conf      314 B    Sun Sep 19 00:07:33 -0500 2021
-rw-r--r--  root:root  50-default.conf  1.1 KiB  Tue Nov 16 04:08:34 -0500 2021
```
Here is a listing of the root `/` directory. 
```
sliver (FUNNY_DRIVEWAY) > ls /

/ (25 items, 2.0 GiB)
=====================
Lrwxrwxrwx   root:root  bin -> /usr/bin        7 B      Mon Mar 25 16:44:20 -0500 2024
drwxr-xr-x   root:root  boot                   <dir>    Wed Apr 10 08:15:26 -0500 2024
drwxrwxr-x   root:root  cdrom                  <dir>    Mon Mar 25 16:46:32 -0500 2024
drwxr-xr-x   root:root  dev                    <dir>    Fri Apr 12 17:00:36 -0500 2024
drwxr-xr-x   root:root  etc                    <dir>    Thu Apr 11 19:04:16 -0500 2024
<snip>
```

Usually, I'd be ok with doing an additional `ls` to get the parent dir properties, but I have run into a use-case which makes it very helpful to have that data.

**Comment by spenceradolph** [comment]
What is missing is the permissions and modified time of the ‘/‘ directory itself. Not the things inside it. 

For example, it’s not currently known if ‘/‘ is world writable.

**Comment by rkervella** [comment]
Ok I get it now, I was confused by the additional info not showing any difference between the two examples (`/` vs `/etc/rsyslog.d`). Right now we're calling `os.ReadDir()` on the provided path (well, when it's a directory), which doesn't return anything for the root element of the path itself.
For a quick sanity check, I just tested with `/bin/ls` on MacOS and `/usr/bin/ls` on an Ubuntu 22.04 box and I'm not getting any details about the root element either when doing `/bin/ls /`. So at least we seem to be consistent with the system's `ls` binary, unless once again I'm missing some context here.

When you say:

> It should be possible to see modified time of '/' directory using ls and not relying on something like execute.

Do you have an example of the command you're using with `execute` to get a different result than what the built-in `ls` command does?

**Comment by rkervella** [comment]
A potential solution could be to add a `.` entry on Unix/Linux systems that fetches the info of the inode matching the requested directory entry (top/root level).

**Comment by spenceradolph** [comment]
Adding the '.' entry would be awesome! It would prevent needing additional runs of 'ls' and should be easy to parse.
