### ISSUE TITLE
Closing sliver client terminate all the `socks` started before

### ISSUE THREAD

**Issue by n3rada** [BishopFox/sliver#1642]
If you start a `socks` in an implant (e.g., `sliver (PLASTIC_SECURITY) > socks5 start -H 127.0.0.1 -P 1081`) and quit a job which is blocking your terminal with "Ctrl + C", this will necessarily disconnect the sliver client, but if you reconnect, you keep the jobs because they are server-side, but you lose the `socks` started before.

Any reason why?

PS: I also tried to have two sliver clients opened-up but same issue when one is closed.

**Comment by rkervella** [comment]
Because `socks` is partly a client-side feature. So if the client is dead, the tunnel is closed.

**Comment by rkervella** [comment]
> Do I miss something?

No that's about right, in the current state of things, if you don't want to kill the client, you'll need to wait for the timeout to expire (1 minute by default).

**Comment by rkervella** [comment]
Closing this one because this is by design: socks tunnels should be closed if the client dies / exits.

**Comment by n3rada** [comment]
Totally understandable, thanks a lot for the promptness.
