### ISSUE TITLE
Client doesn't handle network interruptions gracefully

### ISSUE THREAD

**Issue by C-Sto** [BishopFox/sliver#1668]
**Describe the bug**
When the underlying transport for the client dies, the client hangs and requires a process kill.

**To Reproduce**
1. Start client
2. Kill TCP connection (eg. `tcpkill -i eth0 port 8888`)
3. Restore TCP connection (stop `tcpkill` process)
4. Attempt to use client

**Expected behavior**
Client should either crash, exit gracefully, or restore the underlying connection.

**Desktop (please complete the following information):**
 - OS: linux
 - Version: master

**Additional context**
Not super familiar with the console flows, but I had a poke around in the console code and couldn't see a way to easily restore disconnected transports. There also doesn't appear to be an easy way to kill the console gracefully.

Immediate options look like:
 - https://github.com/BishopFox/sliver/blob/335797e66178aa8cc0e55d60675457ec1270f28b/client/core/tunnel.go#L34 - this could instead be an os.exit/panic. Not exactly elegant, but better than a hung console.
- https://github.com/BishopFox/sliver/blob/master/client/console/console.go#L185 this could be wrapped in a function that calls os.exit when the transport dies

**Comment by rkervella** [comment]
I've noticed that one too, forgot to open an issue about it.

**Comment by rkervella** [comment]
I have a solution that will exit the client gracefully. I'm trying to find a good way to handle auto-reconnect.

**Comment by rkervella** [comment]
#1679 will implement a graceful exit when merged.
