### ISSUE TITLE
switch protobuf repository from googlesource to github

### ISSUE THREAD

**Issue by movonow** [BishopFox/sliver#167]
## suggestion
[go-assets.sh](https://github.com/BishopFox/sliver/blob/master/go-assets.sh) will download `protobuf` from google source which is not always accessible for someone. Is it an option to switch the repository from [go.googlesource.com/sys](https://go.googlesource.com/sys/+archive/master.tar.gz) to [github.com/golang/sys](https://github.com/golang/sys/archive/master.tar.gz).

I am happy to send a PR if it's accepted.

Thanks

**Comment by moloch--** [comment]
Please send a PR
