### ISSUE TITLE
sliver-client console 

### ISSUE THREAD

**Issue by Luoooio** [BishopFox/sliver#1678]
**Describe the bug**
After compiling the sliver-client.exe using the master branch code, some display issues have occurred on the Windows system.

The cursor has become strange: The shape and behavior of the cursor are different from the normal situation, and may have become abnormal.
It sometimes swallows other displays: In some cases, the cursor covers or overlaps the display content of other applications or interface elements, causing these contents to fail to display normally.

**To Reproduce**
2. Command 1 '....'
3. Command 2 '....'

**Expected behavior**

**Screenshots**
![image](https://github.com/BishopFox/sliver/assets/26653157/ec4a46ca-cfd9-4a61-8f03-232ca61f5278)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Version [e.g. v0.0.5]

**Additional context**

**Comment by rkervella** [comment]
It's a known issue, `master` uses a new console package that has some issues on Windows.
