### ISSUE TITLE
Install one liner doesn't work on Arch Linux

### ISSUE THREAD

**Issue by R0ttCyph3r** [BishopFox/sliver#1680]
![image](https://github.com/BishopFox/sliver/assets/146866845/94d953fe-2097-4cfa-89de-98aeadd88ad6)

i even tried it on a fresh install it doesn't work

i tried installing with yay too that also didn't work

**Comment by RafBishopFox** [comment]
@R0ttCyph3r - Thanks for bringing this to our attention. It should be fixed by #1686. Once the fix is live, please test and let us know if the issue still occurs.

**Comment by R0ttCyph3r** [comment]
The script is working completely fine i just tested it 🎉
