### ISSUE TITLE
How can I remove rportfwd? 

### ISSUE THREAD

**Issue by kamikazejunk** [BishopFox/sliver#1715]
May I know how can I remove rportfwd? Help command is useless as it doesn't teach how to use command or doesn't show example command

----------------------------------

sliver (RELEVANT_TATAMI) > rportfwd 2
error: invalid usage of command 'rportfwd' (unconsumed input '2'), try 'help'
sliver (RELEVANT_TATAMI) > rportfwd 

 ID   Remote Address   Bind Address 
==== ================ ==============
  1   127.0.0.1:8081   :8081        
  2   127.0.0.1:8111   :8111        
  3   127.0.0.1:4445   :4445        

sliver (RELEVANT_TATAMI) > rportfwd rm 2 127.0.0.1:4445
error: invalid usage of command 'rm' (unconsumed input '2 127.0.0.1:4445'), try 'help'

**Comment by kamikazejunk** [comment]
I requested improvement for help at #1205, but developer isn't interested.... so I am asking here...

**Comment by TimBF** [comment]
You can see the help with -h. In this case 'rportfwd rm -h'. The correct way to remove it is using 'rportfwd rm -i 2'.

**Comment by ddeatrich** [comment]
I also used the -h. Nowhere does it specify at all to use portfwd rm -i

Luckily I found this page or I never would have known to use -i
