### ISSUE TITLE
compile it with make and run . /sliver-server，it says: zsh: exec format error: . /sliver-server.

### ISSUE THREAD

**Issue by worklitao** [BishopFox/sliver#1721]
After downloading the source code, compile it with make and run . /sliver-server, it says: zsh: exec format error: . /sliver-server.
kali running version: Linux version 6.6.15-amd64 (devel@kali.org) (gcc-13 (Debian 13.2.0-24) 13.2.0, GNU ld (GNU Binutils for Debian) 2.42) #1 SMP PREEMPT_ DYNAMIC Kali 6.6.15-2kali1 (2024-05-17)

**Comment by worklitao** [comment]
The runtime version of go is: 
kali-$ go version
go version go1.22.3 linux/amd64

**Comment by moloch--** [comment]
Try `make linux-amd64`

**Comment by worklitao** [comment]
Thanks. Problem solved.
