### ISSUE TITLE
 Wg connectivity issues

### ISSUE THREAD

**Issue by fullstcat** [BishopFox/sliver#1732]
The problem I encountered is that on some cloud platforms, the wg implant cannot connect (at this time, other protocols can be used to connect normally). After running the wg implant on the target host, a handshake packet is sent out without a reply, and listening is normal. I can receive this packet on the server, but will not respond. Similarly, I can deploy it on other platforms normally and cannot confirm the reason.

Target host
![image](https://github.com/BishopFox/sliver/assets/54357723/bf1ff7cf-4cf4-4e5d-b0d2-e19300b386f4)

The server received a handshake packet and there are no network issues
![image](https://github.com/BishopFox/sliver/assets/54357723/01210048-b8c8-43ae-9b4a-a682592910e8)

Monitoring is normal
![image](https://github.com/BishopFox/sliver/assets/54357723/5aced185-1673-480d-ae31-bc9c60ed5070)

![image](https://github.com/BishopFox/sliver/assets/54357723/0830783e-87cd-46a9-b062-e5fd8007b08c)

![image](https://github.com/BishopFox/sliver/assets/54357723/5985be6f-bcee-4f60-b968-83e3b0c821cf)

**Comment by rkervella** [comment]
Can you name the "cloud platforms" where this happens? If we're not in a position to reproduce, we won't be able to help much.
