### ISSUE TITLE
sliver v1.5.39 without DNS listener

### ISSUE THREAD

**Issue by thekulu** [BishopFox/sliver#1754]
Well,i try to start dns listener and find there shows  'unknown command "dns" for ""'. I check -h and find no dns in Network. What's the problem? 
![image](https://github.com/user-attachments/assets/d49ed68c-c89f-4e2a-bbb1-51515eacd877)
![image](https://github.com/user-attachments/assets/84382fc9-84cf-4874-ba05-37485d9364ac)

**Comment by moloch--** [comment]
If you compiled from source this is from the unreleased v1.6 branch, the DNS C2 in this version of the code currently doesn't work (though I'm working on a fix, but I have a demanding day job so progress is slow). Use a release branch and the command should exit.

**Comment by thekulu** [comment]
I switch to the latest version and find dns command. Thank you!
