### ISSUE TITLE
Job stopped (udp/dns)

### ISSUE THREAD

**Issue by BlueTeamByDay** [BishopFox/sliver#177]
Hey there,

I tried this from a cloud environment and from a local Kali as well and getting the same error. I am able to establish a connection with mtls but not DNS. 

The executable gets generate using:
generate --dns mysubdomain.mydomain.net

But when I try to star the listener this happens:
sliver > dns --domains mysubdomain.mydomain.net
[*]  Starting DNS listener with parent domain(s) [mysubdomain.mydomain.net] ...
[*] Successfully started job #X

[!] Job #X stopped (udp/dns)

I tried adding a . (period) after the .net like .net. based on a related issue but that didn't help either. Can someone please help?

sliver version: tried on both v0.0.6 and v0.07

**Comment by BlueTeamByDay** [comment]
Thank you for quickly getting back to me. Here is the log:
INFO[0001] [sliver/vendor/github.com/dgraph-io/badger/logger.go:46] All 0 tables opened in 0s 
INFO[0001] [sliver/server/assets/assets.go:87] No version detected open /home/slingshot/.sliver/version: no such file or directory 
INFO[0001] [sliver/server/assets/assets.go:105] Version mismatch  != 23cc4206acd841b030ef62d1e80d6839478dfb6a 
INFO[0001] [sliver/server/assets/assets.go:127] Unpacking to '/home/slingshot/.sliver' 
INFO[0001] [sliver/server/assets/assets.go:129] GOPATH = /home/slingshot/.sliver/go 
INFO[0005] [sliver/server/assets/assets.go:215] Creating data directory: /home/slingshot/.sliver/data 
INFO[0005] [sliver/server/assets/assets.go:220] failed to find the dll 
INFO[0005] [sliver/server/certs/ca.go:62] Generating certificate authority for 'server' 
INFO[0005] [sliver/server/certs/certs.go:156] Generating TLS certificate (ECC) for '' ... 
INFO[0005] [sliver/server/certs/certs.go:193] Valid from 2020-03-28 14:40:21.042108386 +0000 UTC to 2023-03-28 14:40:21.042108386 +0000 UTC 
INFO[0005] [sliver/server/certs/certs.go:198] Serial Number: 70282465939757895372477895247708216960 
INFO[0005] [sliver/server/certs/certs.go:203] Authority certificate 
INFO[0005] [sliver/server/certs/certs.go:212] ExtKeyUsage = [0] 
INFO[0005] [sliver/server/certs/certs.go:233] Certificate authenticates host:  
INFO[0005] [sliver/server/certs/certs.go:245] Ceritificate is an AUTHORITY 
INFO[0005] [sliver/server/certs/ca.go:62] Generating certificate authority for 'sliver' 
INFO[0005] [sliver/server/certs/certs.go:156] Generating TLS certificate (ECC) for '' ... 
INFO[0005] [sliver/server/certs/certs.go:193] Valid from 2019-04-28 14:40:21.059439161 +0000 UTC to 2022-04-27 14:40:21.059439161 +0000 UTC 
INFO[0005] [sliver/server/certs/certs.go:198] Serial Number: 213773692471965717983217358272122844186 
INFO[0005] [sliver/server/certs/certs.go:203] Authority certificate 
INFO[0005] [sliver/server/certs/certs.go:212] ExtKeyUsage = [0] 
INFO[0005] [sliver/server/certs/certs.go:233] Certificate authenticates host:  
INFO[0005] [sliver/server/certs/certs.go:245] Ceritificate is an AUTHORITY 
INFO[0005] [sliver/server/certs/ca.go:62] Generating certificate authority for 'operator' 
INFO[0005] [sliver/server/certs/certs.go:156] Generating TLS certificate (ECC) for '' ... 
INFO[0005] [sliver/server/certs/certs.go:193] Valid from 2019-08-08 14:40:21.074863499 +0000 UTC to 2022-08-07 14:40:21.074863499 +0000 UTC 
INFO[0005] [sliver/server/certs/certs.go:198] Serial Number: 97308294892143409187384675267224288077 
INFO[0005] [sliver/server/certs/certs.go:203] Authority certificate 
INFO[0005] [sliver/server/certs/certs.go:212] ExtKeyUsage = [0] 
INFO[0005] [sliver/server/certs/certs.go:233] Certificate authenticates host:  
INFO[0005] [sliver/server/certs/certs.go:245] Ceritificate is an AUTHORITY 
INFO[0005] [sliver/server/certs/ca.go:62] Generating certificate authority for 'https' 
INFO[0005] [sliver/server/certs/certs.go:156] Generating TLS certificate (ECC) for '' ... 
INFO[0005] [sliver/server/certs/certs.go:193] Valid from 2019-07-27 14:40:21.086374959 +0000 UTC to 2022-07-26 14:40:21.086374959 +0000 UTC 
INFO[0005] [sliver/server/certs/certs.go:198] Serial Number: 46445202931991413887570028224532738094 
INFO[0005] [sliver/server/certs/certs.go:203] Authority certificate 
INFO[0005] [sliver/server/certs/certs.go:212] ExtKeyUsage = [0] 
INFO[0005] [sliver/server/certs/certs.go:233] Certificate authenticates host:  
INFO[0005] [sliver/server/certs/certs.go:245] Ceritificate is an AUTHORITY

**Comment by moloch--** [comment]
Did Kali add `resolved` or something? I know on Ubuntu `resolved` binds to `:53` and creates problems like this.

**Comment by BlueTeamByDay** [comment]
resolved is not running and there is nothing else binding to :53 besides `tcp on 127.0.0.53:53`

**Comment by BlueTeamByDay** [comment]
You were right. I had to stop systemd-resolve
Now it took the domain without an error and I was able to setup the listener as such:
`sliver > dns --domains mysubdomain.mydomain.net`

But sliver is not catching it. I verified the DNS settings based on your wiki. I see the outgoing DNS queries and responses too but the connection doesn't show up in Sliver. Am I missing something?
![dnstraffic](https://user-images.githubusercontent.com/56196267/80000007-98ac3f80-848a-11ea-938c-f1e3f1a32384.png)

**Comment by moloch--** [comment]
Let it sit for about 60 seconds, there's some instability in the initial key exchange so it needs to try it a few times. It also looks like your name servers may be misconfigured, [double check the wiki](https://github.com/BishopFox/sliver/wiki/DNS-C2) to ensure your NS records are setup correctly.

**Comment by BlueTeamByDay** [comment]
So I waited for a long time. Went back to my domain registrar to verify all the settings and they are correct. I regenerated the listener and I am still not getting a callback. 

How can I find the missing piece? I know I am screwing something up

pcap shows: Standard query response 0xb020 Server failure TXT _qa438.so_called_cap._domainkey.[subdomain.mydomain.com]

**Comment by moloch--** [comment]
Can you pull the logs from `~/.sliver/logs/sliver.log`? It should recording all incoming DNS requests, even failed ones.

**Comment by BlueTeamByDay** [comment]
Here you go and thank you. 

[sliver.log](https://github.com/BishopFox/sliver/files/4525380/sliver.log)

**Comment by moloch--** [comment]
Looks like you're getting permission denied, to bind to port `:53` you'll need to either run the server as root or use port redirection since this is a privileged port.

**Comment by BlueTeamByDay** [comment]
it's not a port bind problem and I ran it as root. I did these steps below. I ran nc -nvlup 53 and it worked without any error... obviously not when sliver was running. 

systemctl disable systemd-resolved.service
systemctl stop systemd-resolved
rm -f /etc/resolv.conf
vim /etc/resolv.conf

Add a normal resolv.conf:

nameserver 1.1.1.1
nameserver 8.8.8.8

**Comment by moloch--** [comment]
The sliver log you posted just indicates it's not getting any DNS packets.

**Comment by BlueTeamByDay** [comment]
Found the solution. I opened the firewall on the cloud vm and captured all traffic and did the same from the victim. There was clearly no connection.. hence the conclusion was that the domain setting are not accurate. I went back to the registrar's support and their first guy gave wrong instructions. Issue was corrected. It works like charm. Thank you
