### ISSUE TITLE
websites rm doesn't work

### ISSUE THREAD

**Issue by clhefton** [BishopFox/sliver#179]
**Describe the bug**
I've tried everything I can think of to delete website content but the command doesn't work. I misconfigured a site due to a misunderstanding of the help description of what web-path does. I thought it would give a default file to serve and "web-path" is prefixed with the --content dir.

This would be easier if we could just delete a whole website, but I can't figure that out either. Adding that feature would be nice.

**To Reproduce**
1. `websites -w nginx -c /usr/share/nginx/html/ --recursive -p index.html` add
2. it adds everything with --web-path prefixed in front of it, so nothing is correct. All have `/index.html/` prefix
3. 
```
websites -w nginx rm
websites -w nginx -p index.html rm
websites -w nginx -p /index.html rm
websites -w nginx -p index.html/ rm
websites -w nginx -p /index.html/ rm
websites -w nginx -p /index.html/* rm
websites -w nginx -p index.html/* rm
websites -w nginx -c /usr/share/nginx/html --recursive rm
websites -w nginx -c /usr/share/nginx/html/ --recursive rm
websites -w nginx -c /usr/share/nginx/html/* --recursive rm
websites -w nginx -c /usr/share/nginx/html/* --recursive -p index.html rm
```
4. `websites -w nginx ls` still shows all the files there

**Expected behavior**
At least one of these should delete the content. With no arguments, `rm` should remove the website

**Desktop (please complete the following information):**
 - OS: linux 19.10
 - Version: 0.0.6

**Additional context**

**Comment by moloch--** [comment]
Yea i kinda hacked this feature in quickly for a specific goal so it's not feature rich, but I can fix this it should more or less work as you expect it to.

**Comment by moloch--** [comment]
This has been addressed in the `grpc` branch, specifically https://github.com/BishopFox/sliver/commit/69e0a7774fdf80ccb903aa9f57f93c15b01372bd but will leave this issue open until that branch gets merged into `master`
