### ISSUE TITLE
How to modify ja3/ja3s/jarm fingerprint of sliver?

### ISSUE THREAD

**Issue by uziking1** [BishopFox/sliver#1809]
How to modify ja3/ja3s/jarm fingerprint of sliver?

**Comment by moloch--** [comment]
The server-side HTTPS signatures are randomized by default but cannot be specified. mTLS' are fixed Golang fingerprints and we don't recommend using this C2 protocol in contexts which require stealth. 

We don't have any feature to modify the client fingerprints other than on Windows you can specify the use of `wininet` which should give you the default Windows fingerprint.
