### ISSUE TITLE
Give alias to each generated agent

### ISSUE THREAD

**Issue by viencokhi** [BishopFox/sliver#190]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Set custom alias to each generated agent

**Comment by lesnuages** [comment]
Do you have a specific implementation in mind?

**Comment by moloch--** [comment]
I think we can just add it to the `generate` command as an additional flag. We probably also want to limit names to alphanumerics, even though i think we could support arbitrary UTF8, just to avoid any weird issues with the console display.

**Comment by guervild** [comment]
Hey, I am working on the issue
Two improvements in my work could be :
- More than alphanumeric (only alphanumeric is allowed for the moment) ?
- I also added an error message if the user generates an agent with a name already taken. Another idea could be to ask the user as for the option --save?

@lesnuages suggested me to add the option for current sessions, I'll work on that

**Comment by moloch--** [comment]
I think we should stick to ascii alphanumerics, the implant names get used in various ways where symbols/etc. could be problematic or require specialized encoding (e.g. the Common Name in X.509), everything else sounds great!

**Comment by moloch--** [comment]
Fixed in PR.
