### ISSUE TITLE
SharpHound3.exe via Execute-Assembly Timesout

### ISSUE THREAD

**Issue by mubix** [BishopFox/sliver#198]
Even with the timeout set to 9999 SharpHound.exe times out after 60 seconds or so.

**Comment by rkervella** [comment]
Got some info about the size of the domain / AD entries? I haven't run long running processes so far with `execute-assembly`, I'll have a look.

**Comment by moloch--** [comment]
@rkervella I think there's an underlying bug I ran into with sliver-script recently too. gRPC has it's own timeout, and I don't think we sync the `--timeout` flag (how long we wait for the implant to run the command) with the underlying gRPC timeout.

**Comment by rkervella** [comment]
That would make sense in that case. That's gonna be a problem for async comms too.

**Comment by moloch--** [comment]
Yeap, my interim solution in sliver-script was to set the gPRC timeout to `--timeout` + 1 second, which should work here. We'll have to solve the async case separately.

**Comment by rkervella** [comment]
I'll have a look in the morning tomorrow.

**Comment by rkervella** [comment]
@mubix can you paste the exact command you typed? Here's what I get in my small lab:

```
sliver (ANNOYED_GOLF) > execute-assembly /home/lesnuages/code/SharpHound.exe '-c All'

[*] Assembly output:
-----------------------------------------------
Initializing SharpHound at 12:23 AM on 6/3/2020
-----------------------------------------------

Resolved Collection Methods: Group, Sessions, LoggedOn, Trusts, ACL, ObjectProps, LocalGroups, SPNTargets, Container

[+] Creating Schema map for domain CENTRALLAB.LOCAL using path CN=Schema,CN=Configuration,DC=CENTRALLAB,DC=LOCAL
[+] Cache File Found! Loaded 116 Objects in cache

[+] Pre-populating Domain Controller SIDS
Status: 0 objects finished (+0) -- Using 40 MB RAM
Status: 76 objects finished (+76 76)/s -- Using 47 MB RAM
Enumeration finished in 00:00:01.1466528
Compressing data to .\20200603002359_BloodHound.zip
You can upload this file directly to the UI

SharpHound Enumeration Completed at 12:24 AM on 6/3/2020! Happy Graphing!
```

Be aware that there are often some quirks related to argument passing for the `sideload` / `spawndll` and `execute-assembly` command, especially when you pass no arguments whereas the assembly / DLL expect you to pass some. I usually pass an "empty" argument on the command line for those.
It's not an ideal solution, but it works so far.

**Comment by mubix** [comment]
I tested with arguments and I wasn't getting any output back at all. I have a couple other C# scripts that result in the same. My test domain has 1000 users and 1000 computers. Maybe thats why? On the command line SharpHound only takes about a minute to finish

**Comment by rkervella** [comment]
One minute should not be an issue (just need to increase the timeout).
What commit number / sliver-server version are you on?

**Comment by mubix** [comment]
I just tested again. Times out after 30 seconds, just like the download does. Not sure why.

**Comment by mubix** [comment]
Sorry, didn't answer your question. I'm using latest release from github. I think that' 1.0.0.0 or something like that

**Comment by rkervella** [comment]
Any chance you could post the command you typed (you can redacted any sensitive parameters)

**Comment by rkervella** [comment]
@mubix can you pull the latest master and see if the issue is still present?

**Comment by mubix** [comment]
Will do. Thanks!

**Comment by mubix** [comment]
Sorry for the delay, I did test this recently and it was working. Thanks!
