### ISSUE TITLE
Feature Request: Make Token

### ISSUE THREAD

**Issue by mubix** [BishopFox/sliver#202]
It would be nice to be able to make a token with a password in the cases where you have a shell on a box without a forwardable token (like WMI, WinRM and such)

**Comment by rkervella** [comment]
Hm that should be doable. I guess the easy way would be to [CreateProcessWithLogonW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithlogonw) and then use `impersonate` to steal the token.

I'm gonna put that on the backlog, I'll have a look at it later.

**Comment by rkervella** [comment]
Closed in #245
