### ISSUE TITLE
Download of large files fails

### ISSUE THREAD

**Issue by mubix** [BishopFox/sliver#204]
Attempted to download a 100 meg file. with a timeout of 
`download -t 3000 bigfile.bin`

And it times out after 30 seconds each time.

**Comment by moloch--** [comment]
This is likely related to the gRPC timeout bug too, will have a fix shortly. I will note though gRPC messages are currently limited to ~4Gb (which we need to document) so files larger than that will need to be chunked by the user (until we add auto-chunking to the `download` command).

**Comment by moloch--** [comment]
Okay, I sorted this out there's a fix in `stage` it wasn't that we weren't sync'ing the gRPC timeout and the implant timeouts; we weren't calculating the implant timeouts correctly resulting in the default timeout always being used for any `--timeout` flag value under 1e+9.

**Comment by mubix** [comment]
Thanks!

**Comment by rkervella** [comment]
FYI I just merged it into master.
