### ISSUE TITLE
I don't need this stress in my life...

### ISSUE THREAD

**Issue by mubix** [BishopFox/sliver#205]
SO I was trying to terminate a process which had the PID of 1400... and when I ran the command to do so it Sliver tells me it terminated PID 0.... It actually killed the right PID but killing PID 0 would have crashed the box hard. Not an awesome feeling.
```
sliver (CODE_NAME) > terminate 1400 
[*] Process 0 has been terminated
```

**Comment by rkervella** [comment]
Good catch, I've seen this a few times, the culprit is [here](https://github.com/BishopFox/sliver/blob/master/sliver/handlers/generic-rpc-handlers.go#L124-L128). We forgot to set the `Pid` in the `sliverpb.Terminate` protobuf message, so it takes the default value of 0.
Should be a quick fix.

**Comment by moloch--** [comment]
Oof, that's a bad bug

**Comment by lesnuages** [comment]
To be clear, we kill the correct process, it's just that in the user interface we report that `terminated.Pid` was killd (see [here](https://github.com/BishopFox/sliver/blob/master/client/command/proc.go#L200)) and this values comes from the RPC response. But we never actually set it, so it takes the default value of 0 (which can be confusing).

Anyway, preventing killing PID 0 is also something we can implement.

**Comment by moloch--** [comment]
Yea, I was just thinking of a scenario where we forget to set it in the request instead of the response (this is actually fairly likely in something like sliver-script), and I can't think of a legitimate scenario were we'd want to kill PID 0.

**Comment by lesnuages** [comment]
I mean it's the same as `rm -rf /`, we don't really safeguard against that (and maybe we should?).

**Comment by moloch--** [comment]
We should probably at least require some type of `--force` bool flag that defaults to false? Similar to `--no-preserve-root`, but for both?

**Comment by moloch--** [comment]
<img width="940" alt="Screen Shot 2020-06-06 at 12 53 07 PM" src="https://user-images.githubusercontent.com/875022/83951068-b80dea80-a7f4-11ea-8593-02e3ecc380eb.png">

**Comment by mubix** [comment]
Thanks for the fix! ;-)
