### ISSUE TITLE
Add example client configuration to Wiki / allow for client setup via sliver-client

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [BishopFox/sliver#206]
**Is your feature request related to a problem? Please describe.**
I am running sliver-server in daemon mode via systemd, but connecting to the server requires a client config that is not generated

https://github.com/BishopFox/sliver/wiki/Configuration-Files does not include an example client configuration

**Describe the solution you'd like**
1) Example client config in Wiki
2) Allow connecting a client without a config, instead allow both command line options and step by step "wizard" input when running sliver-client

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by moloch--** [comment]
I'll go ahead and do (1) now, but I'll leave the ticket open for (2), which will require some code changes in the client.

**Comment by rkervella** [comment]
I believe this one has been solved, right @moloch-- ?

**Comment by moloch--** [comment]
Yes.
