### ISSUE TITLE
Evasion breaks Windows Injection

### ISSUE THREAD

**Issue by C-Sto** [BishopFox/sliver#222]
**Describe the bug**
Refreshing NTDLL/system32.dll in memory appears to break stuff on some versions of Windows. I'm not entirely sure why.

**To Reproduce**
Perform any task that requires process injection (anything that calls RefreshPE essentially) with debug enabled, observe catastrophic failure. Tested on win2012R2, but presumably other Windows versions might have similar fails.

**Expected behavior**
No catastrophic failure (or an option to disable/enable evasion like this). I've

**Screenshots**
<img width="640" alt="image" src="https://user-images.githubusercontent.com/7466346/87118666-88984500-c2ae-11ea-81e2-74bb11ee3b96.png">

**Desktop (please complete the following information):**
 Server version 1.0.6 (compiled from main)

**Additional context**
I've seen this happen with some EDR when refreshing ntdll in memory also - it appears to mess up the offsets for the expected function pointers for syscalls etc. I think it would make sense to have evasion as an opt-in, with a warning flag that it may kill your agent.

**Comment by C-Sto** [comment]
This could actually also be the cause of https://github.com/BishopFox/sliver/issues/198, since in the client the behavior you see is in line with that (agent just appears to time out, despite being totally dead, and check in time being updated)

**Comment by rkervella** [comment]
Fixed on master
