### ISSUE TITLE
Health Check for Session Management

### ISSUE THREAD

**Issue by 3ndG4me** [BishopFox/sliver#238]
**Is your feature request related to a problem? Please describe.**
It is nearly impossible to know when a sliver session has died for any given reason. There is no status indicator server-side other than manually calculating the difference in the "Last Check-in" timestamp

**Describe the solution you'd like**
It would be beneficial to have a "Health" status for any sessions to know when shells may have died. In addition it would be useful to extend the `kill` command to clean up any "dead" sessions as they occur.

**Describe alternatives you've considered**
Outside of manually checking the session, or calculating the check-in timestamp there are no alternative solutions that I am aware of for this issue.

**Additional context**
When handling a lot of sessions it would be nice to know if a connection has potentially died. Most C2's have something for this, even a simple comparison between the implant's reconnect interval and last check-in would likely suffice.

**Comment by moloch--** [comment]
This has been on my TODO list for a little while but I've been distracted with work :)

**Comment by 3ndG4me** [comment]
Hopefully my proposed solution is sufficient. 

If not let me know if there's anything I can do to improve it, happy to take this one off your plate 😉.

**Comment by moloch--** [comment]
Yes, it's nearly identical to the solution I had in mind (reusing the existing `ping` message, which is the smallest C2 message). I actually ran into this exact problem at National CCDC where we had 100+ shells and they kept going up and down. My quick hack at the time was to write a [sliver-script](https://github.com/moloch--/sliver-script) that periodically ran `ping` and killed stale sessions, but of course this is a less than ideal solution.

I'm currently working on improvements to the build system but after that I'm going to revisit aspects of the C2 (including this, DNS stability, and some type of beacon mode) but all in good time!

**Comment by moloch--** [comment]
If you want to work on this by all means please send us a PR! I think my short term solution would be to reuse `ping` and to indicate stale sessions by changing the color (to probably orange) similar to how we indicate the active session with green.

**Comment by 3ndG4me** [comment]
I've actually got a PR referencing this (Submitted the issue and PR at the same time. I don't like calling out "issues" I haven't at least tried to solve. 😅).

It's here:
https://github.com/BishopFox/sliver/pull/239

My solution is slightly different. Rather than using ping, I send along whatever the ReconnectInterval is of a given implant and check that against the Last Check-In time.

This way the implant effectively updates its own status during the connection lifecycle. Of course reusing `ping` during this cycle could achieve the same sort of result, I just didn't think of that approach.

I'd of course love feedback on this when you have time, even if it's not as ideal of a solution.😄

**Comment by moloch--** [comment]
Oh lol I'm blind haha.

**Comment by moloch--** [comment]
Merged, thanks for the PR! Like I said this is something I've been meaning to address!

**Comment by 3ndG4me** [comment]
Awesome! Glad I could help contribute this feature 😄
