### ISSUE TITLE
ARM Implant support

### ISSUE THREAD

**Issue by 1F0X1** [BishopFox/sliver#247]
ARM based processors are taking a larger role in both Consumer and Enterprise spaces. There is a capability gap for implants with a robust C2 framework to operate in engagements both in Pivot gear and client equipment.  

Unless I missed something implant generation only supports x86/amd64 arch.  Adding ARM would be a nice low power engagement alternative.

**Comment by moloch--** [comment]
If you're adventurous it is possible to compile for ARM right now, but requires a few hacks in the code to get it working. We're working on a more official way to support any Golang target but it's not ready just yet.

**Comment by 1F0X1** [comment]
Looks like I would need to go mucking about in sliver/server/generate/binaries.go. Add a ARM within func getCCompiler. Then ensure that we have the proper GCC in the vars path? Looks like you are using MiniGW for the CC aspects?

**Comment by moloch--** [comment]
Only if you want to use GCC, the Go compiler does support ARM via GOARCH, which is still handled in `sliver/server/generate/binaries.go`

**Comment by moloch--** [comment]
The [v1.16](https://github.com/BishopFox/sliver/tree/go/v1.16beta1) branch now has (at least limited) support for all Golang compiler targets including `linux/arm`, etc.
