### ISSUE TITLE
Support Starting Implant Listeners Automatically

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#254]
**Is your feature request related to a problem? Please describe.**
Should my host or sliver itself crash/restart, I'd like my listeners to come back automatically.

**Describe the solution you'd like**
(Optionally) Store listeners in server.json and start them on startup of the daemon.

**Describe alternatives you've considered**
I'm sure this can be done with sliver-script, but it seems such an obvious use case that I think it should be considered in the core (and not require operators to write typescript for it)

**Comment by rkervella** [comment]
We could probably use the database for that

**Comment by Matir** [comment]
Oh that's probably also a sensible approach.  I'd be happy to contribute a patch for it if you all want.

Thinking it would be something like:

- Add a bool flag to the commands that create listeners (maybe `--persist`?  not sure it's the best name) to have them saved/restored
- Save configuration for each listener to the DB (single table?  need to figure out storage of different flags)
- On startup, read configuration, start listeners

If reviewing my design & code is more work than implementing it yourselves, feel free to say so, I want to do what is easiest for you all for providing this great tool.

**Comment by rkervella** [comment]
I like that approach. The other one I was thinking about would involve more commands, which might complicate things:

- Store listeners config by default
- Add a `restore-listener` command that can either take the `--all` flag or `--id LISTENER_ID` flag to restore either all listeners or only the selected ones
- Add an `autorestore` config option to automatically run `restore-listener --all` on startup
- Add a command to list saved listeners and output their ID

I'm totally fine with you working on a PR, as I probably won't have time (and neither @moloch-- ) to work on that in the near future.

**Comment by moloch--** [comment]
So I am sort of mid swing on moving to SQLite for the database, which would be my only concern about using the DB for storing this as it's not really ready yet.

**Comment by Matir** [comment]
I've only used [upper.io/db](https://upper.io/v4/) as an ORM.

Unless there's a plan to move all config to the DB, it seems like persistent listeners is a configuration that might make sense in the file?

**Comment by moloch--** [comment]
Yea I agree, i think the config file is the place to put them.
