### ISSUE TITLE
util.CopyFileContents is unused

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#256]
**Describe the bug**
Not really a bug per se, but the only use of util.CopyFileContents is in its own test.

I noticed this when looking at the code, as the current implementation of the function is terribly inefficient (copying the entire file to RAM at once)

**Comment by rkervella** [comment]
Agreed that's dead code right now.

**Comment by moloch--** [comment]
Let's just remove it.

**Comment by moloch--** [comment]
Fixed in `stage`
