### ISSUE TITLE
Unnecessary Pointers

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#267]
This isn't really a big deal for anyone but developers, but there's a number of things that are pointers but don't need to be.  For example, in `server/core/jobs.go`:

- Both the map and the mutex elements of the `jobs` struct
- The jobID global

Not a big issue, but the code would read a little bit more clearly, such as replacing `(*j.active)[jobID]` with just `j.active[jobID]`.

I'm happy to send some clean up PRs, but wanted to make sure that there wasn't a design decision to do this for some reason I've overlooked.

**Comment by moloch--** [comment]
Yea a lot of this is due to legacy code / changes to core, feel free to clean it up!

**Comment by moloch--** [comment]
I think I've removed the last of these in the v1.5.0 branch.
