### ISSUE TITLE
Docker image doesn't build

### ISSUE THREAD

**Issue by crashingstatic** [BishopFox/sliver#268]
**Describe the bug**
Love Sliver, really great tool. I wanted to update to the latest version. I was having some difficulty building from source on Debian (not your fault, just weird dependencies with protoc) so I figured I'd skip the frustration and just build the container. Currently, the dockerfile doesn't build the image correctly. Exits with
  
```
client/version/version.go:4:7: GitDirty redeclared in this block
            previous declaration at client/version/sliver.go:41:2
make:  ***  [Makefile:83: static-linux] Error 2

The command '/bin/sh -c make static-linux && cp -vv sliver-server /opt/sliver-server' returned a non-zero code: 2
```
  
**To Reproduce**
1. `git clone https://github.com/BishopFox/sliver`
2. `cd sliver`
3. `sudo ./build.py`

**Expected behavior**
Docker container should build without error

**Desktop (please complete the following information):**
 - OS: Debian 10.5
  
  
Am I doing something wrong? Is there a way for me to fix this?

**Comment by Matir** [comment]
Not a fix for your Docker issue, but...

I'm on Debian for my development on sliver and it builds fine.  The Debian package `protobuf-compiler` should give you a usable protoc.

**Comment by Matir** [comment]
In your source directory, what files do you have in `sliver/client/version`?  I have `sliver-version.go`, neither `sliver.go` nor `version.go`.

**Comment by moloch--** [comment]
@crashingstatic We recently updated how the version package works, previously the`Makefile` would generate some files that are no longer needed (we now use `-X` to insert variables at build time). I'm guessing the directory you're building from still has some of those old files (did you `git pull` from an older version?).

To fix you should be able to delete those files (I think its just`version.go`), alternatively re-clone `master` and then build from there.
