### ISSUE TITLE
Build server for current platform by default

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#269]
It's a trivial thing, but when running a plain `make`, having it build for the current platform would be nice.

**Comment by rkervella** [comment]
You're damn right, I always thought it was just @moloch--'s plan to force me into switching to MacOS.

**Comment by Matir** [comment]
Yeah, I'm embarrassed by the number of times I've seen:

```
zsh: exec format error: ./sliver-server
```

**Comment by moloch--** [comment]
> You're damn right, I always thought it was just @moloch--'s plan to force me into switching to MacOS.

:)
