### ISSUE TITLE
Cannot run Sliver Server and Client on the same host with the same user

### ISSUE THREAD

**Issue by mubix** [BishopFox/sliver#278]
Version 1.0.8-beta

When trying to run the client and server on the same host with the same user you get this:
```
# sliver-client
[!] Cannot acquire directory lock on "/root/.sliver/db/root".  Another process is using this Badger database.: resource temporarily unavailable
Is there another server instance running?
```

This can be solved (thanks to @C-Sto ) by setting the environmental variable for the Sliver root to another directory, as so:
```
SLIVER_ROOT_DIR=/root/.sliver-client/ sliver-client
```

**Comment by rkervella** [comment]
I just had a quick look, and this is a regression from #258. @guervild included server code in the agent code, which results in the `db` package to be included by the agent, where it has no business doing so.
I'll work on a fix.
