### ISSUE TITLE
Execute: show output even on non-zero exit code.

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#294]
**Describe the bug**
If a command executed returns a non-zero exit code (failure) then we get no output on the console.

**To Reproduce**
1. Run `execute ls /this/path/does/not/exist`.
2. Notice it fails, but the error from ls is not displayed to tell you why.  (Yes, I know about the ls builtin, this is just a simple test case.)

**Expected behavior**
Notify failure and display the output.

**Comment by moloch--** [comment]
Probably be a good idea to return `stderr`

**Comment by Matir** [comment]
Yep, I had opened #293 about that as well.  I'm working on a fix for both, but haven't had enough time to test thoroughly.

**Comment by Matir** [comment]
It looks like this will need to be done by not using an RPC-layer error when the exit status is non-zero.  If an RPC error is passed, gRPC drops the response message as far as I can tell.

**Comment by moloch--** [comment]
Yea we probably just want to expand the [Execute](https://github.com/BishopFox/sliver/blob/master/protobuf/sliverpb/sliver.proto#L322) protobuf response.

**Comment by Matir** [comment]
This should be fixed by #303
