### ISSUE TITLE
Feature Request - Auto Load SharpCollection

### ISSUE THREAD

**Issue by mubix** [BishopFox/sliver#298]
It would be nice to have the SharpCollection suite automatically available in Sliver. 
https://github.com/Flangvik/SharpCollection

One small hiccup might be that SharpCollection may go away some day as it's a repo out of the hands of Sliver devs, but it would be good to have some way to "import" a collection of binaries into the sliver server to be used on sessions without having to dig around for them on the file system.

**Comment by rkervella** [comment]
The best way to deal with that would be to use extensions, and modify the client to auto load them from a directory. Another way would be to port the extension system server-side.

I'll have a look at the first solution.

**Comment by moloch--** [comment]
We've not ported all of them but the new `armory` pkg manager should address this problem.
