### ISSUE TITLE
Short `-n` parameter used for both the name of the agent and DNS setting

### ISSUE THREAD

**Issue by hippich** [BishopFox/sliver#321]
1) https://github.com/BishopFox/sliver/blob/922862cc2b6f8a48e035ab459739d3225892f200/client/command/bind-commands.go#L363

2) https://github.com/BishopFox/sliver/blob/922862cc2b6f8a48e035ab459739d3225892f200/client/command/bind-commands.go#L372

**Comment by moloch--** [comment]
Fixed in `stage` branch.

**Comment by moloch--** [comment]
Merged https://github.com/BishopFox/sliver/pull/334
