### ISSUE TITLE
Sliver generation fails on a non-static build.

### ISSUE THREAD

**Issue by usiegl00** [BishopFox/sliver#326]
**Describe the bug**
Generating a sliver fails on a non-static build.

**To Reproduce**
1. ./sliver-server
2. generate -o linux -m 127.0.0.1 (--skip-symbols optional)
4. See error: [!] rpc error: code = Unknown desc = Failed to copy GOPATH

**Expected behavior**
The server generates a sliver.

**Screenshots**
My terminal contrast is bad.
Here is the text output.
```text
[*] Welcome to the sliver shell, please type 'help' for options

sliver > generate -o linux -m 127.0.0.1 --skip-symbols

[*] Generating new linux/amd64 implant binary
[!] Symbol obfuscation is disabled
[!] rpc error: code = Unknown desc = Failed to copy GOPATH

sliver > exit
```
**Desktop:**
 - OS: Ubuntu
 - Version: 18.04.5 LTS

**Additional context**
Here is the log:
```text
INFO[2021-02-02T22:55:35Z] [sliver/server/generate/binaries.go:507] Obfuscating source code ... 
INFO[2021-02-02T22:55:35Z] [sliver/server/gobfuscate/main.go:57] Copying GOPATH (/root/.sliver/slivers/linux/amd64/PROFITABLE_ANGLE) ... 
ERRO[2021-02-02T22:55:35Z] [sliver/server/gobfuscate/gopath-copy.go:22] Failed to build import graph: github.com/bishopfox/sliver 
ERRO[2021-02-02T22:55:35Z] [sliver/server/gobfuscate/gopath-copy.go:24]  -> Error for package: /root/.sliver/slivers/linux/amd64/PROFITABLE_ANGLE/src/github.com/bishopfox/sliver/s93.go:1:1: expected 'package', found 'EOF' 
INFO[2021-02-02T22:55:35Z] [sliver/server/generate/binaries.go:514] Error while obfuscating sliver Failed to copy GOPATH 
ERRO[2021-02-02T22:55:35Z] [github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/logging/logrus/options.go:215] finished unary call with code Unknown 
INFO[2021-02-02T22:55:38Z] [google.golang.org/grpc@v1.33.2/internal/grpclog/grpclog.go:37] [core] Channel Connectivity change to SHUTDOWN 
INFO[2021-02-02T22:55:38Z] [google.golang.org/grpc@v1.33.2/internal/grpclog/grpclog.go:37] [core] Subchannel Connectivity change to SHUTDOWN 
```

**Comment by moloch--** [comment]
If you compile a non-static server binary it will only work if you run it from the root of the git repo.

**Comment by moloch--** [comment]
Basically, the server needs access to the implant source code to compile an implant, only static builds contain the source code for the implant. Non-static builds are for development only and instead pull the files from the local file system using relative paths, so the non-static builds only work in the root of the git repo where the relative paths line up to the expected files.

**Comment by usiegl00** [comment]
Sorry, I should have been more clear.
This was executed from the root of the repo.
