### ISSUE TITLE
Proxy Authentication not applied

### ISSUE THREAD

**Issue by 0x646f6d** [BishopFox/sliver#327]
I tried to use an http implant in a network where only traffic via an http-proxy is allowed. Additionally the proxy requires authentication. The windows host has the system proxy configured - authentication set up as well. However, the implant obviously does not apply the authentication settings as it cannot connect. I can verify this in the proxy logs, the request is forbidden because of missing authentication.

**Comment by moloch--** [comment]
That's correct, we currently don't support proxy authentication.

**Comment by moloch--** [comment]
We do detect proxy settings at the system level, but since we're using Go's HTTP stack the scheme currently lacks authentication support. We'd like to add this in the future though!

**Comment by npbf** [comment]
Added in https://github.com/BishopFox/sliver/pull/647

See https://github.com/BishopFox/sliver/wiki/C2-Advanced-Options for usage

`generate --http http://example.com?driver=wininet` will authenticate to the proxy with the user's cached credentials. Use `generate --http http://example.com?driver=wininet&ask-proxy-creds=true` to prompt the user if there are no cached creds.
