### ISSUE TITLE
Manually setting the HTTP-Host-Header

### ISSUE THREAD

**Issue by 0x646f6d** [BishopFox/sliver#328]
I would like to use sliver in a Domain Fronting scenario. It doesn't seem possible currently as I cannot set the HTTP-Host-Header. Is there any work in progress?

**Comment by moloch--** [comment]
Correct, domain fronting is another unsupported technique right now. However, the code is of course open source!

**Comment by moloch--** [comment]
Duplicate of https://github.com/BishopFox/sliver/issues/140 going to close this one.
