### ISSUE TITLE
dump lsass like dumpert

### ISSUE THREAD

**Issue by timwhitez** [BishopFox/sliver#345]
use same way as https://github.com/outflanknl/Dumpert
to dump lsass for evasion.

**Comment by moloch--** [comment]
I think you should be able to use this via `spawn-dll` or `sideload`, the sRDI version can also be used via `execute-shellcod`

**Comment by timwhitez** [comment]
ok,thx

**Comment by timwhitez** [comment]
and what's the different between spawn-dll and sideload?

**Comment by moloch--** [comment]
`spawn-dll` is specific to Windows DLLs and loads the DLL into the same process using reflective DLL injection. Side load is able to load any shared library (i.e., `.so`, `.dylib`, and `.dll`) and loads the shared library using platform specific techniques into a new process.

Both commands have `help` for more details.

**Comment by rkervella** [comment]
Actually `spawn-dll` also loads a DLL into a new process (`notepad.exe` by default), the difference is that it's mainly geared towards reflective DLLs (those using the `RelfectiveLoader` project).

For dumpert, I'd recommend using: `sideload --entry-point Dump path/to/dumpert.dll`

**Comment by timwhitez** [comment]
ok thanks i will try to read the source code
