### ISSUE TITLE
download issue 

### ISSUE THREAD

**Issue by Darkcast** [BishopFox/sliver#346]
when you download the lastest Linux release 1.4.2 you get the 1.4.1

All hackers gain renown
[*] Server v1.4.1 - 7d47fe392055735d1a735fcd90ad4c4c2dc61b33 - Dirty
[*] Welcome to the sliver shell, please type 'help' for options

same thing happens when you try to update using the applications. looks like the old version got pushed.

**Comment by moloch--** [comment]
It looks like the commit `7d47fe3` is correct the version just didn't get pulled from the git tag correctly.

**Comment by moloch--** [comment]
You're using the latest code! We'll fix the version number though.

**Comment by moloch--** [comment]
Fixed.

**Comment by Darkcast** [comment]
Thank you sir for your amazing work 😊.
