### ISSUE TITLE
1.4.3 Can't create tcp-pivot or execute command on linux target 

### ISSUE THREAD

**Issue by kfken** [BishopFox/sliver#349]
**Describe the bug**
When trying to run "execute" or "tcp-pivot" on linux/amd64 implant, receive "rpc error: code = Unknown desc"

**To Reproduce**
1. generate --mtls 101.1.1:8080 --os linux -b -N test -j 60
2. upload, execute, get connect back, use 1
3.  execute ls
4. In server: "rpc error: code = Unknown desc = Cowardly refusing to terminate process without force"
5.  From implant: "sliver.go:111: [recv] sysHandler 44"
6. tcp-pivot -s 172.16.1.1 -l 9090
7. In server: "rpc error: code = Unknown desc = Unknown message type"
8. From implant: sliver.go:131: [recv] unknown envelope type 52"

**Expected behavior**
Expected ls to return results from target, tcp-pivot to create listener on target

**Desktop (please complete the following information):**
 - OS: Sever - Kali 2021.1; target: Ubuntu 16.04 (4.4.0-121)

**Comment by moloch--** [comment]
There should be some details on the error in the `~/.sliver/logs/sliver.log` file, could you send us some of those details?

**Comment by rkervella** [comment]
Did you build from source or did you use release binaries?

**Comment by kfken** [comment]
Downloaded from https://github.com/BishopFox/sliver/releases/download/v1.4.3/sliver-server_linux.zip

**Comment by kfken** [comment]
I know this problem didn't occur with v1.2.1, and I *think* 1.3.0 was also ok.  I don't have my VM for either of those, started fresh with 1.4.x, and all seem affected.

**Comment by rkervella** [comment]
Did you delete `~/.sliver` when you upgraded the server binary?

**Comment by kfken** [comment]
> Did you delete `~/.sliver` when you upgraded the server binary?

No, I hadn't, but just deleted both that and ~/.sliver-client and tried again.  That seems to have fixed it, thanks.  Wasn't aware I needed to do that at each upgrade of the server binary.

**Comment by moloch--** [comment]
You shouldn't have to ... haha, sound like there's a still a bug lurking in here.

**Comment by kfken** [comment]
Yeah, I think I had upgraded in place from 1.2.1 to 1.3.0 without any issues.

**Comment by rkervella** [comment]
`rpc error: code = Unknown desc = Unknown message type` is typical of implant code not matching the server code (can occur when new message types have been added). So I guess in this case the "new" implant code was not unpacked when the new server binary ran.

**Comment by moloch--** [comment]
ahh okay that makes sense.
