### ISSUE TITLE
Version 1.4.4 - linux generates an rpc error when generating a payload 

### ISSUE THREAD

**Issue by Darkcast** [BishopFox/sliver#353]
**Describe the bug**
running on kali latest version with all the requirements installed
when I try to generate a payload it gves me an rpc error 

**To Reproduce**
sliver > generate --mtls  LOCALIP --os Windows

[*] Generating new windows/amd64 implant binary
[*] Symbol obfuscation is enabled.
[*] This process can take awhile, and consumes significant amounts of CPU/Memory
[!] rpc error: code = Unknown desc = exit status 1

**Expected behavior**
to generate a windows payload 

**Desktop (please complete the following information):**
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.1
Codename:       kali-rolling

**Additional context**
tried the same command in mac had the same problem.

**Comment by rkervella** [comment]
Could check `~/.sliver/logs/sliver.log` for a more detailed error message and post it here?

**Comment by rkervella** [comment]
Hmm can't reproduce with v1.4.4 freshly downloaded from the releases:

```
All hackers gain vigilance
[*] Server v1.4.4 - a9639b0873dc0d6a4bb7a0156e6ff96a40ace0a4 - Dirty
[*] Welcome to the sliver shell, please type 'help' for options

sliver > generate --mtls 127.0.0.1 --os windows

[*] Generating new windows/amd64 implant binary
[*] Symbol obfuscation is enabled.
[*] This process can take awhile, and consumes significant amounts of CPU/Memory
[*] Build completed in 00:01:20
[*] Implant saved to /home/kali/downloads/LIVELY_CONSEQUENCE.exe

sliver >
````
Did you upgrade from a previous version?

**Comment by moloch--** [comment]
I suspect this may be related to the reuse of `go/modcache` across multiple versions of Go, due to the file system permissions applied by Go to the cache it's not always cleaned up in a good way, but @Darkcast if you can send us the logs we can confirm.

**Comment by Darkcast** [comment]
Sorry for the late reply, where can I find the logs ?

**Comment by moloch--** [comment]
`~/.sliver/logs/sliver.log`

**Comment by Darkcast** [comment]
Hi
heres are the logs for kali and mac both having the same issues. 

Thank you 

[sliver.log](https://github.com/BishopFox/sliver/files/6189142/sliver.log)

[sliver_darwin.log](https://github.com/BishopFox/sliver/files/6189078/sliver_darwin.log)

**Comment by rkervella** [comment]
From the `sliver_darwin.log` file:

```
INFO[2021-03-18T08:13:12-04:00] [sliver/server/gogo/go.go:203] --- stdout ---

INFO[2021-03-18T08:13:12-04:00] [sliver/server/gogo/go.go:204] --- stderr ---
go: github.com/BurntSushi/xgb@v0.0.0-20210121224620-deaf085860bc: Get "https://proxy.golang.org/github.com/%21burnt%21sushi/xgb/@v/v0.0.0-20210121224620-deaf085860bc.mod": dial tcp: lookup proxy.golang.org: no such host
```

**Comment by moloch--** [comment]
Yeap, @Darkcast the machine needs an internet connection to build the implant right now, (see #341 ).

**Comment by Darkcast** [comment]
thats strange cause I was connected and it worked previously but ill double check.
is there anyways to pass a proxy?

**Comment by Darkcast** [comment]
I was able to confirm that the payload got negerted without proxy. 
Thanks.

**Comment by moloch--** [comment]
It would probably be a good idea to add support for `GOPROXY`

**Comment by moloch--** [comment]
https://github.com/BishopFox/sliver/issues/357
