### ISSUE TITLE
HTTPS_PROXY Support for Builds

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#357]
Pass down the current env's `HTTP_PROXY` to `go mod` command during build.

**Comment by b4b857f6ee** [comment]
This is still the case? Any possibility to build it offline?

**Comment by moloch--** [comment]
This is still the case, however if you do one build it should cache the build and subsequent builds should be possible offline. Go v1.18 should be adding multiple modules per repo which should remove allow us to fix this in a good way.

**Comment by moloch--** [comment]
Implemented in v1.5.0

**Comment by kernelr0p** [comment]
Hi all, I guess it should be implemented in v1.5.0. Is still the case?. I am trying to generate implants on a server behind squid proxy and I have defined GOPROXY within server.json and HTTP_PROXY pointing out to the squid server:
`export HTTP_PROXY="http://proxy.server:3128"`
Contents of .sliver/configs/server.json:
```
{
    "daemon_mode": false,
    "daemon": {
        "host": "",
        "port": 31337
    },
    "logs": {
        "level": 4,
        "grpc_unary_payloads": false,
        "grpc_stream_payloads": false
    },
    "jobs": {
        "multiplayer": null
    },
    "watch_tower": null,
    "go_proxy": "https://proxy.golang.org"
}
```
sliver.log:
```
go: downloading inet.af/netstack v0.0.0-20210317161235-a1bf4e56ef22
go: downloading github.com/things-go/go-socks5 v0.0.3-0.20210722055343-24af464efe43
go: downloading github.com/lesnuages/go-winio v0.4.19
go: downloading github.com/stretchr/testify v1.7.0
go: downloading github.com/kbinani/screenshot v0.0.0-20191211154542-3a185f1ce18f
go: github.com/Binject/universal@v0.0.0-20210304094126-daefaa886313: Get "https://proxy.golang.org/github.com/%21binject/universal/@v/v0.0.0-20210304094126-daefaa886313.mod": dial tcp 172.217.0.49:443: i/o timeout

INFO[2022-03-21T15:54:24+01:00] [sliver/server/gogo/go.go:179] exit status 1
ERRO[2022-03-21T15:54:24+01:00] [sliver/server/generate/binaries.go:649] Go mod tidy failed:
ERRO[2022-03-21T15:54:24+01:00] [github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/logging/logrus/options.go:215] finished unary call with code Unknown
```

**Comment by moloch--** [comment]
Do a `export GOPROXY="http://proxy.server:3128"` before you run the server.

**Comment by moloch--** [comment]
https://github.com/BishopFox/sliver/wiki/Offline-Implant-Builds

**Comment by moloch--** [comment]
Fixed in `master` - https://github.com/BishopFox/sliver/commit/68a270581f376a6f7aeb409f2ff9bbee62908588

**Comment by kernelr0p** [comment]
Can you please check with latest release v1.5.9?. I am able to run 'go mod tidy' from cmd with HTTPS_PROXY variable and GOPROXY but sliver simply omits HTTP/HTTPS_PROXY variable.

**Comment by moloch--** [comment]
Only `GOPROXY` is set in v1.5.9, if you compile`master` (or wait for v1.5.10 which should be along shortly) it will support both `GOPROXY` and `HTTP_PROXY`

**Comment by bluecmd** [comment]
Since it is `https://proxy.golang.org` as the default proxy, shouldn't the variable be passed be `HTTPS_PROXY`? 

At least in v1.5.10 I cannot make sliver build behind my home proxy server I have set up for my lab environment. The closest I have come is this:

```
# /etc/systemd/system/sliver.service.d/override.conf
[Service]
Environment="HTTP_PROXY=http://x.y.z.w:3128"
Environment="GOPROXY=http://proxy.golang.org"
```

Note that I had to downgrade to `http://` on the GOPROXY or the proxy wouldn't be used (as expected, since HTTPS_PROXY controls `https://` and that isn't passed along from what I can tell)

Sadly, the build fails a bit later with being unable to verify signatures against `https://sum.golang.org/` since again no proxy is used. I could probably disable that as well with `GOSUMDB=off` but I do not want to download code over HTTP without checksums :P.

**Comment by moloch--** [comment]
Fixed in `master`
