### ISSUE TITLE
32-bit DLL builds fail on latest Kali AMI

### ISSUE THREAD

**Issue by cha0tic87** [BishopFox/sliver#358]
**Describe the bug**
32-bit DLL Slivers don't call home to a Sliver server running on the latest Kali AMI.

**To Reproduce**
1. Run Sliver server on Kali AMI
2. Start HTTP listener
3. Generate 32-bit DLL
4. Execute on 32-bit host
5. Session never calls home

**Expected behavior**
A Sliver session should be generated. EXE works fine on 32-bit, and 64-b it DLL's work fine too.

**Comment by moloch--** [comment]
Appears to be related to Kali's mingw version/config.

**Comment by moloch--** [comment]
Fixed with #1652
