### ISSUE TITLE
ps fails in linux environments using NSS

### ISSUE THREAD

**Issue by Matir** [BishopFox/sliver#359]
**Describe the bug**
When operating in an environment where users are not listed in `/etc/passwd`, running `ps` fails to show processes owned by that user.

This occurs because the pure-go `os/user.LookupId` implementation directly parses `/etc/passwd` rather than using NSS.  (Understandable.)  This results in `getProcessOwner` returning an error, which leads to [`processes()`](https://github.com/BishopFox/sliver/blob/master/implant/sliver/ps/ps_linux.go#L142) skipping listing that process.

**To Reproduce**
1. Install an implant on a linux host using LDAP/AD for usernames.
2. Run `ps` from the sliver server.
3. Notice that processes owned by users not listed in `/etc/passwd` are missing.

**Expected behavior**
Maybe display the numeric user ID instead of hiding the process?

I can send a PR in a day or two to implement using the numeric user ID instead of hiding the process, unless there's a better/faster fix.

**Comment by rkervella** [comment]
If you could submit a PR that'd be nice, as I don't have an environment with NSS configured right now.
