### ISSUE TITLE
the timeout command for 'migrate' doesnt work

### ISSUE THREAD

**Issue by Viss** [BishopFox/sliver#367]
when attempting to use the migrate command, the help says that '-t' can be used as a timeout.
However, when giving the migrate command the -t argument, the command fails and it brings up syntax.

`migrate 123 -t 300`
gives the error "you must provide a pid to migrate to"

`migrate -t 300 123`
simply outputs usage.

**Comment by rkervella** [comment]
Looks like a bug / regression. Gonna look into that one.

**Comment by rkervella** [comment]
Flags must be passed before the arguments (that's a restriction of the `grumble` lib we're using for the cli), so the first command would not work anyway. However, I can't reproduce the issue with the second command on the latest version:

```
sliver (ASHAMED_GAITERS) > migrate -t 300 7832
[*] Successfully migrated to 7832
[*] Session #2 ASHAMED_GAITERS - 172.16.20.78:52537 (windev) - windows/amd64 - Wed, 31 Mar 2021 09:21:59 CEST
```

What version of Sliver are you using?

**Comment by Viss** [comment]
this is version 1.4.6

Here's a screenshot of the behavior
![image](https://user-images.githubusercontent.com/1756255/113199449-ff4de780-921b-11eb-995a-77a0db1821b7.png)

**Comment by Viss** [comment]
so it looks like 1.4.8 was released 2 days ago - can I just drop the binary in and replace the existing c2? will things pick up where they left off, or should i expect that I should nuke my environment and start from scratch with the new version?

**Comment by Viss** [comment]
it looks like upgrading to 1.4.8 has resolved the issue
![image](https://user-images.githubusercontent.com/1756255/113201533-75ebe480-921e-11eb-815b-a55049c1308d.png)

**Comment by rkervella** [comment]
> this is version 1.4.6
> 
> Here's a screenshot of the behavior
> ![image](https://user-images.githubusercontent.com/1756255/113199449-ff4de780-921b-11eb-995a-77a0db1821b7.png)

So, the first command fails because the flag must be passed before the argument. The second command (`migrate -h 120 8264`) fails because you're passing the wrong flag to the command: `-h` is for displaying the help string, you need `-t`.

I'll try to check back on 1.4.6 to see what could cause the issue, but I don't remember modifying that code lately.

**Comment by Viss** [comment]
ohmygod.
its possible i may have done that last time and not noticed.


On April 1, 2021 12:14:01 AM PDT, Ronan Kervella ***@***.***> wrote:
>> this is version 1.4.6
>> 
>> Here's a screenshot of the behavior
>> ![image](https://user-images.githubusercontent.com/1756255/113199449-ff4de780-921b-11eb-995a-77a0db1821b7.png)
>
>So, the first command fails because the flag must be passed before the argument. The second command (`migrate -h 120 8264`) fails because you're passing the wrong flag to the command: `-h` is for displaying the help string, you need `-t`.
>
>I'll try to check back on 1.4.6 to see what could cause the issue, but I don't remember modifying that code lately.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BishopFox/sliver/issues/367#issuecomment-811699784
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Viss** [comment]
its possible i cant actually read
