### ISSUE TITLE
ProcessList with sessionID on windows

### ISSUE THREAD

**Issue by nodauf** [BishopFox/sliver#368]
Is it possible to add a new column for the `ps` command when it is executed on a windows target to include the SessionID. This field is useful when choosing in which process we want to migrate. A sessionID 0 will likely have some issues.

This field is natively returns by `tasklist` or `Get-Process`

From what I saw the function [ProcessIdToSessionId](https://github.com/golang/sys/blob/4fbd30eecc44bcbc3a049f16bad8703053ebab7c/windows/zsyscall_windows.go#L2547) may be useful

**Comment by rkervella** [comment]
Looks doable, I'll look into it when I find some time.
