### ISSUE TITLE
Sliver server crashes on large file upload through sliver session

### ISSUE THREAD

**Issue by rwincey** [BishopFox/sliver#380]
**Describe the bug**
Sliver server crashes when large file is uploaded through sliver (~25 megs)

**To Reproduce**
1. sessions -i <session number>
2. upload C:\\Users\\user\\test.zip /tmp/test.zip
3. Server crashes

**Expected behavior**
File uploads and doesn't crash the server

**Screenshots**
![image](https://user-images.githubusercontent.com/5438659/114046921-3db85780-9857-11eb-9332-9d45a4592448.png)

**Desktop (please complete the following information):**
 - OS: Linux (server)
 - Version 1.4.8

**Additional context**

**Comment by moloch--** [comment]
I'm not sure this error is related to the size of the upload but we'll take a look and see if we can reproduce.

**Comment by moloch--** [comment]
There is a limit but it's about ~2Gb

**Comment by rwincey** [comment]
HTTPS. Mentioned the file size because it appears to work with very small files ( ~10kb).

**Comment by rkervella** [comment]
I was unable to reproduce on either HTTP or mTLS transports with a 100MB file.
Upload scenario was:
- sliver-server: linux box
- sliver implant running on a Windows VM
Everything went fine.

**Comment by rwincey** [comment]
I haven't had it happen in a while so my guess is it got fixed along the
way or it was an anomaly.

**Comment by rkervella** [comment]
Closing for now, feel free to reopen if it happens again.
