### ISSUE TITLE
Linux DNS Implant TXT Record Length Check Fails Causing Implant to Fail

### ISSUE THREAD

**Issue by rwincey** [BishopFox/sliver#402]
**Describe the bug**
Linux DNS implant does not work due to what may be a bug in Go's Net DNS lib or sliver's use of up to 254 length DNS names (with the period).

**To Reproduce**
1. Generate a linux DNS implant with debug to see the error
2. Run on test system
3. See error
![nix_dns_implant_erro](https://user-images.githubusercontent.com/12126525/115463737-2a639f80-a1fa-11eb-9e04-fa66e4e456c8.png)

**Expected behavior**
DNS implant checks-in and is operational

**Screenshots**
The code responsible for this is in src/net/dnsclient_unix.go - lookup -> dnsConfig.nameList
![dnsclient_nix_go_net_254_check](https://user-images.githubusercontent.com/12126525/115464049-7d3d5700-a1fa-11eb-9656-90acf1cea707.png)

The reason Windows is unaffected is because it has entirely different code for this operation.

![win_dns_lookup_go](https://user-images.githubusercontent.com/12126525/115464113-934b1780-a1fa-11eb-9dff-c68816f6c178.png)

**Desktop (please complete the following information):**
 - OS: Linux Implant
 - Version 1.4.12

**Additional context**

**Comment by moloch--** [comment]
That's a good catch.

**Comment by rwincey** [comment]
After reviewing the comments in the code, it appears the max expected domain length is 20. After reducing the length of my callback domain it appears things work. May be simple enough to just add a check that the supplied dns domain length is less than this max value and adding some documentation/comments in the listener cli notifying the user.

![check_domain_size](https://user-images.githubusercontent.com/5438659/115560946-14e68800-a283-11eb-952a-ccf110446376.png)
