### ISSUE TITLE
Obfuscation Regression

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#404]
Several packages that were previously obfuscated are no longer obfuscated, possibly due to the WireGuard obfuscator updates?

Running strings will reveal plaintext protobuf packages:

```
RegistryType
BINARY
STRING
DWORD
QWORD
PortfwdProtocol
B/Z-github.com/bishopfox/sliver/protobuf/sliverpbb
```

**Comment by rkervella** [comment]
Need to read more on `GOPRIVATE`, because I thought `github.com/bishopfox/sliver/protobuf/sliverpbb` would be caught by `github.com/bishopfox/*`.

**Comment by moloch--** [comment]
I tried playing around with the `GOPRIVATE` setting, it seems these particular Protobufs do something that Garble can't obfuscate. Adjusting the `GOPRIVATE` to `github.com/*` for example didn't change the result.

**Comment by pooki3bear** [comment]
While this is addressed, is there a preferred tag that does not have this issue?

**Comment by lesnuages** [comment]
I think v1.4.8 leaks a lot less symbols.

**Comment by Marshall-Hallenbeck** [comment]
I can confirm v1.4.8 exes don't trigger Defender, but the newest version (v1.4.14) do.

**Comment by moloch--** [comment]
This makes me think it's related to updated version of protobuf in v1.4.12

**Comment by rkervella** [comment]
I think you're right: v1.4.11 does not seem to have the issue, but starting v1.4.12, a lot of symbols are not obfuscated anymore.

**Comment by rundx** [comment]
Listener address is not obfuscated too

**Comment by rundx** [comment]
@moloch-- https://github.com/burrowers/garble/issues/349#issuecomment-846590664

**Comment by moloch--** [comment]
As noted in the Garble bug thread, the root cause appears to be the blob of binary data included by protobuf's "rawDesc" 

https://github.com/burrowers/garble/issues/349#issuecomment-846590664

https://github.com/BishopFox/sliver/blob/master/protobuf/sliverpb/sliver.pb.go#L7068

We can probably implement our own wrapper around the protobuf code generation to add an XOR wrapper to fix the problem.

**Comment by mvdan** [comment]
FYI, `garble` does support literal obfuscation via `-literals`, but it's disabled for large literals for now as some of its behavior is currently quadratic. You could submit an issue or patch about supporting large literals like this one via simpler methods like XOR.

**Comment by moloch--** [comment]
Partial fix in `stage` by increasing max literal size in our fork of Garble, since we know ahead of time what code we're obfuscating (as apposed to upstream `garble`'s generic use case) it is easy to determine the performance impact of increasing the size limit, which based on my testing is acceptable.

Three annotations still make it through, which I need to hunt down:

```
➜  Desktop strings EXCLUSIVE_CREDIT|grep -i sliver
Zprotobuf:"varint,10,opt,name=Type,proto3,enum=sliverpb.RegistryType" json:"Type,omitempty"
dprotobuf:"varint,2,opt,name=Protocol,proto3,enum=sliverpb.PortfwdProtocol" json:"Protocol,omitempty"
dprotobuf:"varint,2,opt,name=Protocol,proto3,enum=sliverpb.PortfwdProtocol" json:"Protocol,omitempty"
```

**Comment by mvdan** [comment]
I chose the current limit very arbitrarily by the way, happy to bump it. The only point of reference I had was the added test in ba19a1d49cde5a5fb82c30b4c335133f4627d69a, where the obfuscated build got many times slower with ~128KiB string literals, enough to make the test run in >10s instead of ~1s.

Ideally, what we would do instead is have literal obfuscation mechanisms that scale a bit better with larger literals. For example, we could increase the limit from 2KiB to 128KiB by splitting the literal in chunks of 2KiB. Then it doesn't really matter if the current literal obfuscator mechanisms are quadratic. We probably still should have some total limit, because huge literals will always tend to have a high obfuscation cost either at build time or at run time.

**Comment by moloch--** [comment]
I'll probably do some more experimentation and send you a PR with a more general fix/approach. I need something quick and dirty for a time sensitive project.
