### ISSUE TITLE
O noez my shellz 😭

### ISSUE THREAD

**Issue by pooki3bear** [BishopFox/sliver#409]
**Describe the bug**
IDK broke while using portfwd to janky ccdc victim. SSH -D work just fine instead

**To Reproduce**
IDK lol I was trying to portfwd over MTLS and it all break. Here is a graphic to depict my sadness:

Target ESXi HTTPs <----- Victim (pwned, implant) <----- Ubuntu C2 -----> ME (the hacker, portfwd OSX client, firefox browser point to local port go to victim ESXi box )

Also this same thing happen when using the C2 server directly for portfwd, so the above graphic is probably superfluous. 

**Expected behavior**
Golang not panic

**Screenshots**
<img width="1675" alt="sliver" src="https://user-images.githubusercontent.com/24210410/115990565-c3871300-a578-11eb-8425-26e99723fe9f.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]
 - Macos client v1.4.13
 -  ubuntu server v1.4.14
 
**Additional context**
I love shellz, make me very sad when I lose shellz

**Comment by moloch--** [comment]
We apologize for your loss :) and will look into fixing this so that no shells are so senselessly lost in the future.

**Comment by moloch--** [comment]
I believe this has been fixed with the switch to `sync.Map` to avoid race conditions in the tunnel data buffer.
