### ISSUE TITLE
How can I add my own module to sliver? 

### ISSUE THREAD

**Issue by RedTeamWing** [BishopFox/sliver#415]
How can I add my own module to sliver? Are there any relevant development documents? For example, I want to add elevate modules or socks5 proxy modules myself.

**Comment by rkervella** [comment]
We sadly don't really have any "developer" documentation yet. You can go through the wiki to get a better understanding about the design decisions, but that's about it.

If you really want to get started, here are the main components:

- The [client](https://github.com/BishopFox/sliver/tree/master/client) package: this where all the `sliver-client` code will be. If you want to add a new command to the client, you'll need to write it in [client/command](https://github.com/BishopFox/sliver/tree/master/client/command).
- The [server](https://github.com/BishopFox/sliver/tree/master/server) package: contains all the code for `sliver-server`, which means the code where the implant connections will be handled.
- The [protobuf](https://github.com/BishopFox/sliver/tree/master/protobuf) package: communications in Sliver are all made via protobuf messages. This package contains both the protobuf definition files, the gRPC services definition.
- The [implant/sliver](https://github.com/BishopFox/sliver/tree/master/implant/sliver) package: this is the actual implant code, generated by the server when you use the `generate` command (or the `Generate` [RPC](https://github.com/BishopFox/sliver/blob/master/protobuf/rpcpb/services.proto#L39)).

I recommend going through the code base to get yourself familiarized with this structure.

Now let's say you want to add a dummy "hello" command that spawns a new process. You'll need to:

- Create the new command in the `client/command` package by adding a new file, and add your command to the [command bindings](https://github.com/BishopFox/sliver/blob/master/client/command/bind-commands.go).
- Add your protobuf messages to the `sliverpb` package
- Define your new RPC command in the [service defintion file](https://github.com/BishopFox/sliver/blob/master/protobuf/rpcpb/services.proto)
- Add the actual RPC code in the [server package](https://github.com/BishopFox/sliver/tree/master/server/rpc), usually in a new file
- Modify the implant code to implement a handler function to execute your code on the implant. There are few gotchas, so here's a list:
    - If your code is complex, add a new package under `sliver/implant/sliver`.
    - Protobuf messages are matched with message identifiers, so don't forget to add a mapping to your messages in [here](https://github.com/BishopFox/sliver/blob/master/protobuf/sliverpb/constants.go)
    - Any file you add in the implant code that is required at compile time will need to have its path added to the list in [server/generate/srcfiles.go](https://github.com/BishopFox/sliver/blob/master/server/generate/srcfiles.go). Any file not on this list will not be compiled when you generate the implant, which will probably result in an error.

And that's mostly it. I probably missed some steps, but this is the global idea about how to add a feature in the implant.

**Comment by RedTeamWing** [comment]
Thank you for your reply

**Comment by RedTeamWing** [comment]
I modified sliverpb.proto and used this command:
` protoc -- go_out = plugin = grpc:./sliverpb/sliver.proto`

However, the generated go file seems to have an error.
For example
```
type WGSocksStartReq struct {
Port int32 'protobuf:"varint,1,opt,name=Port,proto3" json:"Port,omitempty "'
Request *commonpb.Request 'protobuf:"bytes,9,opt,name=Request,proto3" json:"Request,omitempty "'
XXX_NoUnkeyedLiteral struct{} 'json :"-"'
XXX_unrecognized []byte 'json :"-"'
"Int32' JSON:"-"'
}
```
What is the right way

It should be to compile multiple files together, but worry about errors

![image](https://user-images.githubusercontent.com/25416365/116499327-81463480-a8de-11eb-838d-3e5f6ccd5f5e.png)

**Comment by rkervella** [comment]
I recommend using the `pb` target in the Makefile to generate the protobuf messages:

```shell
make pb
```
