### ISSUE TITLE
pollHandler context deadline exceeded

### ISSUE THREAD

**Issue by RedTeamWing** [BishopFox/sliver#426]
This error occurs whenever implant is executed on pollHandler, resulting in session loss.

![image](https://user-images.githubusercontent.com/25416365/117577714-7b8df180-b11d-11eb-86f2-0262fd323c44.png)

There may be problems in handling this place.

```
func (s *SliverHTTPC2) pollHandler(resp http.ResponseWriter, req *http.Request) {
	httpSession := s.getHTTPSession(req)
	if httpSession == nil {
		httpLog.Infof("No session with id %#v", httpSession.ID)
		resp.WriteHeader(403)
		return
	}

	// We already know we have a valid nonce because of the middleware filter
	nonce, _ := strconv.Atoi(req.URL.Query().Get("code"))
	_, encoder, _ := encoders.EncoderFromNonce(nonce)
	select {
	case envelope := <-httpSession.Session.Send:
		resp.WriteHeader(200)
		httpLog.Info("resp wing")
		envelopeData, _ := proto.Marshal(envelope)
		data, _ := cryptography.GCMEncrypt(httpSession.Key, envelopeData)
		resp.Write(encoder.Encode(data))
	case <-time.After(pollTimeout):
		httpLog.Debug("Poll time out")
		resp.WriteHeader(201)
		resp.Write([]byte{})
	}
}
```

**Comment by moloch--** [comment]
Are you sure you're loosing the session? These poll timeouts are part of normal operation.

**Comment by RedTeamWing** [comment]
I tried to add the domain fronting function myself. Compared with http requests, there are more Host: xx.cdn.com. I don't know why it causes blocking and then I cannot execute the command.

![image](https://user-images.githubusercontent.com/25416365/117660594-f1529580-b1cf-11eb-85a1-b097908dfdfe.png)

At first, there was no problem and i can run the command.
......
......
However, when pollhander function is executed, the "ls" command is not displayed.

![image](https://user-images.githubusercontent.com/25416365/117660761-265ee800-b1d0-11eb-8754-c609375020c5.png)

I am trying to add domain fronting technology. I don't know if this function is in your development plan.🤣🤣🤣

**Comment by RedTeamWing** [comment]
The difference is that I added a .DomainFront arg。


func (s *SliverHTTPClient) newHTTPRequest(method, uri string, encoderNonce int, body io.Reader) *http.Request {
	req, _ := http.NewRequest(method, uri, body)
	// {{if .Config.DomainFront}}
	req.Host = "{{.Config.DomainFront}}"
	// {{end}}
	req.Header.Set("User-Agent", defaultUserAgent)
	req.Header.Set("Accept-Language", "zh-CN")
	query := req.URL.Query()
	query.Set("code", fmt.Sprintf("%d", encoderNonce))
	req.URL.RawQuery = query.Encode()

	return req
}
