### ISSUE TITLE
macOS amd64 grpc error 

### ISSUE THREAD

**Issue by batuhanburakcin** [BishopFox/sliver#429]
When I tried to compile version 1.4.14 (master branch also same), then run 

darthvader@Batuhans-MacBook-Air sliver-master % ./sliver-server                                                                                            
Unpacking assets ...
panic: runtime error: index out of range [1] with length 1

goroutine 89 [running]:
github.com/bishopfox/sliver/server/rpc.(*Server).GetVersion(0xe0ecc00, 0xd8f4e20, 0xc014f29050, 0xc014f28c90, 0xe0ecc00, 0x9, 0x50ca47f)
	github.com/bishopfox/sliver/server/rpc/rpc.go:85 +0x179
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler.func1(0xd8f4e20, 0xc014f29050, 0x4f82b40, 0xc014f28c90, 0x5098e00, 0xe0ecc00, 0x0, 0x0)
	github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:1332 +0x8b
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.PayloadUnaryServerInterceptor.func1(0xd8f4e20, 0xc014f29050, 0x4f82b40, 0xc014f28c90, 0xc0149eb260, 0xc013747638, 0x0, 0x0, 0x0, 0x0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/logging/logrus/payload_interceptors.go:29 +0x251
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xd8f4e20, 0xc014f29050, 0x4f82b40, 0xc014f28c90, 0x1b, 0xc01fb72f67cb9388, 0x15ab81dee, 0xe0bda00)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.UnaryServerInterceptor.func1(0xd8f4e20, 0xc014f28f60, 0x4f82b40, 0xc014f28c90, 0xc0149eb260, 0xc0149eb280, 0xd8f4e20, 0xc014f28f60, 0xc000010dd8, 0xc014f28f30)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/logging/logrus/server_interceptors.go:31 +0x10f
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xd8f4e20, 0xc014f28f60, 0x4f82b40, 0xc014f28c90, 0x1b, 0x4f82b40, 0xc014f28c90, 0x1)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1(0xd8f4e20, 0xc014f28c60, 0x4f82b40, 0xc014f28c90, 0xc0149eb260, 0xc0149eb2a0, 0xc00bbd1500, 0x1, 0x1, 0xc00bbd1500)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/tags/interceptors.go:23 +0x8c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xd8f4e20, 0xc014f28c60, 0x4f82b40, 0xc014f28c90, 0x1, 0x0, 0x0, 0xc014f3aa60)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/bishopfox/sliver/server/transport.auditLogUnaryServerInterceptor.func1(0xd8f4e20, 0xc014f28c60, 0x4f82b40, 0xc014f28c90, 0xc0149eb260, 0xc0149eb2c0, 0x4a5d7ba, 0x4fbeda0, 0xc0149eb2e0, 0xc0149eb260)
	github.com/bishopfox/sliver/server/transport/logging.go:134 +0x277
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xd8f4e20, 0xc014f28c60, 0x4f82b40, 0xc014f28c90, 0xc000566000, 0x0, 0xc014f3ab30, 0x400f198)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0xd8f4e20, 0xc014f28c60, 0x4f82b40, 0xc014f28c90, 0xc0149eb260, 0xc013747638, 0xc014f3aba0, 0x4136366, 0x4ff1ae0, 0xc014f28c60)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:34 +0xd7
github.com/bishopfox/sliver/protobuf/rpcpb._SliverRPC_GetVersion_Handler(0x5098e00, 0xe0ecc00, 0xd8f4e20, 0xc014f28c60, 0xc014f26ea0, 0xc01337db60, 0xd8f4e20, 0xc014f28c60, 0x0, 0x0)
	github.com/bishopfox/sliver/protobuf/rpcpb/services_grpc.pb.go:1334 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc006d596c0, 0xd902558, 0xc014ea4000, 0xc014ef8b40, 0xc01337dce0, 0xe0a8040, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc006d596c0, 0xd902558, 0xc014ea4000, 0xc014ef8b40, 0x0)
	google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc014e9e020, 0xc006d596c0, 0xd902558, 0xc014ea4000, 0xc014ef8b40)
	google.golang.org/grpc@v1.37.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd

I changed grpc version, downgraded go version but same error. 

It works on linux.

**Comment by moloch--** [comment]
Looks like you may have forgotten to run the `go-assests.sh` script?

**Comment by batuhanburakcin** [comment]
I did. otherwise it won't compile. 

CGO_ENABLED=1 go build -mod=vendor -trimpath -tags osusergo,netgo,sqlite_omit_load_extension,server -ldflags "-s -w -X github.com/bishopfox/sliver/client/version.Version= -X \"github.com/bishopfox/sliver/client/version.GoVersion=go version go1.16.4 darwin/amd64\" -X github.com/bishopfox/sliver/client/version.CompiledAt=1620999490 -X github.com/bishopfox/sliver/client/version.GithubReleasesURL=https://api.github.com/repos/BishopFox/sliver/releases -X github.com/bishopfox/sliver/client/version.GitCommit= -X github.com/bishopfox/sliver/client/version.GitDirty=Dirty" -o sliver-server ./server
CGO_ENABLED=1 go build -mod=vendor -trimpath -tags osusergo,netgo,sqlite_omit_load_extension,client -ldflags "-s -w -X github.com/bishopfox/sliver/client/version.Version= -X \"github.com/bishopfox/sliver/client/version.GoVersion=go version go1.16.4 darwin/amd64\" -X github.com/bishopfox/sliver/client/version.CompiledAt=1620999490 -X github.com/bishopfox/sliver/client/version.GithubReleasesURL=https://api.github.com/repos/BishopFox/sliver/releases -X github.com/bishopfox/sliver/client/version.GitCommit= -X github.com/bishopfox/sliver/client/version.GitDirty=Dirty" -o sliver-client ./client
darthvader@Batuhans-MacBook-Air sliver-master % 

I tried to change version of go inside go-assests. nothing changes.

**Comment by moloch--** [comment]
I'd say double check the version(s) of your dependencies and ensure those versions are on your `$PATH`. My main machine is a Mac so Sliver defiantly works on MacOS :)

**Comment by batuhanburakcin** [comment]
I found it. don't install protoc via brew. Get from git and  I reinstalled it solves. I think that version is corrupt. Thank you.
