### ISSUE TITLE
`ERROR INSTALLING`

### ISSUE THREAD

**Issue by ORCA666** [BishopFox/sliver#430]
hii, i did exactly what u asked for, 
1st i cloned this repository 
i then executed "./go-assets.sh" 
everything went well (it outputted "All done" )
then i executed "make"
an error occurred:

******************************************************************************************************************************************

rm -f sliver-client_arm64 sliver-server_arm64
rm -f sliver-client sliver-server *.exe
CGO_ENABLED=1 go build -mod=vendor -trimpath -tags osusergo,netgo,sqlite_omit_load_extension,server -ldflags "-s -w -X github.com/bishopfox/sliver/client/version.Version=v1.4.14 -X \"github.com/bishopfox/sliver/client/version.GoVersion=go version go1.15.9 linux/amd64\" -X github.com/bishopfox/sliver/client/version.CompiledAt=1621064230 -X github.com/bishopfox/sliver/client/version.GithubReleasesURL=https://api.github.com/repos/BishopFox/sliver/releases -X github.com/bishopfox/sliver/client/version.GitCommit=ea6a17c3e6c51da2c89f23cc8465424e2c0f57d2 -X github.com/bishopfox/sliver/client/version.GitDirty=Dirty" -o sliver-server ./server
go: inconsistent vendoring in /home/kali/sliver:
        github.com/AlecAivazis/survey/v2@v2.2.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/Binject/binjection@v0.0.0-20200705191933-da1a50d7013d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/Binject/debug@v0.0.0-20210225042342-c9b8b45728d2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/BurntSushi/xgb@v0.0.0-20201008132610-5f9e7b3c49cd: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/Microsoft/go-winio@v0.4.16: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/alecthomas/chroma@v0.8.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/binject/go-donut@v0.0.0-20201215224200-d947cf4d090d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/cheggaaa/pb/v3@v3.0.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/desertbit/closer/v3@v3.1.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/desertbit/columnize@v2.1.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/desertbit/grumble@v1.0.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/fatih/color@v1.10.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/gen2brain/shm@v0.0.0-20200228170931-49f9650110c5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/gofrs/uuid@v3.3.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/golang/protobuf@v1.5.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/google/uuid@v1.2.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/gorilla/mux@v1.8.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/kbinani/screenshot@v0.0.0-20191211154542-3a185f1ce18f: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/lesnuages/go-socks5@v0.0.0-20210409090601-adbe23bd0194: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/lesnuages/go-winio@v0.4.19: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/lxn/win@v0.0.0-20210218163916-a377121e959e: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/mattn/go-sqlite3@v1.14.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/miekg/dns@v1.1.35: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/niemeyer/pretty@v0.0.0-20200227124842-a10e7caefd8e: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/sergi/go-diff@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/sirupsen/logrus@v1.7.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/spf13/cobra@v1.1.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        github.com/stretchr/testify@v1.6.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        golang.org/x/crypto@v0.0.0-20210317152858-513c2a44f670: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        golang.org/x/net@v0.0.0-20210410081132-afb366fc7cd1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        golang.org/x/sys@v0.0.0-20210403161142-5e06dd20ab57: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        golang.zx2c4.com/wireguard@v0.0.20200121: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        golang.zx2c4.com/wireguard/wgctrl@v0.0.0-20200609130330-bd2cb7843e1b: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        google.golang.org/genproto@v0.0.0-20210406143921-e86de6bf7a46: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        google.golang.org/grpc@v1.37.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        google.golang.org/protobuf@v1.26.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        gopkg.in/AlecAivazis/survey.v1@v1.8.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        gopkg.in/check.v1@v1.0.0-20200902074654-038fdea0a05b: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        gorm.io/driver/mysql@v1.0.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        gorm.io/driver/postgres@v1.0.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        gorm.io/driver/sqlite@v1.1.3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        gorm.io/gorm@v1.20.6: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
        golang.zx2c4.com/wireguard: is replaced in go.mod, but not marked as replaced in vendor/modules.txt

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
make: *** [Makefile:98: default] Error 1

******************************************************************************************************************************************

so i executed "go mod vendor"
the output:
github.com/bishopfox/sliver/implant imports
        embed: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)

running "-mod=mod or -mod=readonly" will output the same results,
im running kali linux

**Comment by rkervella** [comment]
You need to use Go 1.16 to build from source.

**Comment by ORCA666** [comment]
> You need to use Go 1.16 to build from source.

how to do that i just installed go, and i dont know how to code with it, so im kind of lost :(

**Comment by moloch--** [comment]
Downloading the pre-compiled version will be much easier than compiling from source, especially if you're not familiar with Go: https://github.com/BishopFox/sliver/releases/tag/v1.4.14

However, to install Go v1.16.x from https://golang.org/dl/

**Comment by ORCA666** [comment]
> Downloading the pre-compiled version will be much easier than compiling from source, especially if you're not familiar with Go: https://github.com/BishopFox/sliver/releases/tag/v1.4.14
> 
> However, you can install Go v1.16.x from https://golang.org/dl/ (we can see from the log output you have Go v1.15 installed), to check what version is installed on your machine run the `go version` command.

heyyy, i didnt know that there is a pre-compiled version... until i compile it my self, i had a simple problem in golang language directories, i had to purge it and then install it again, then execute make, however for the sake of simplicity, and because i want my "sliver" without future errors i will re-install it from the releases folder !
thanks for ur help !
