### ISSUE TITLE
Why can't i open the DNS job

### ISSUE THREAD

**Issue by timwhitez** [BishopFox/sliver#432]
![image](https://user-images.githubusercontent.com/36320909/120327628-8b63b480-c31c-11eb-8e8d-d92977b9c442.png)
![image](https://user-images.githubusercontent.com/36320909/120327678-99193a00-c31c-11eb-97d0-15023c4dd2f0.png)

I use DNS --domains c.test.com.
but sliver doesn't listen at port 53

**Comment by moloch--** [comment]
DNS runs on UDP 53, add `-u` to your `netstat` command

**Comment by timwhitez** [comment]
it works well, thanks so much!
