### ISSUE TITLE
Command asyn

### ISSUE THREAD

**Issue by RedTeamWing** [BishopFox/sliver#433]
Can impant execute the command asynchronously return the execution result? I cannot obtain the execution result in real time when using the execute command. I don't know if this function can be implemented.

All commands now get the returned results in real time, but if the executed program is blocked, the session will lag, so I want to ask if it can be asyn
![image](https://user-images.githubusercontent.com/25416365/120751545-c3e0d980-c53a-11eb-9087-d2e7ff4356ef.png)

**Comment by moloch--** [comment]
For long running commands you'll need to increase the default timeout (all commands have a default timeout of ~60 seconds), this can be done via the `--timeout` flag.

**Comment by rkervella** [comment]
Technically, the implants and server kinda support async commands, but the client does not.

**Comment by RedTeamWing** [comment]
I mean, when I execute a command, I have to wait for the result of the command to execute the next command. Can you execute multiple commands at the same time and return results one by one like cobalt strike.

**Comment by RedTeamWing** [comment]
![image](https://user-images.githubusercontent.com/25416365/128629380-8f993066-7fff-4d24-b1c4-735b4980d42b.png)

This is my solution. Is it feasible？

**Comment by moloch--** [comment]
It's more complicated than executing the command in a goroutine but something we may support in the near future. In order to have a good experience we need to integrate with timeouts, rework how data is displayed, etc.

**Comment by rkervella** [comment]
And cancellation

> It's more complicated than executing the command in a goroutine but something we may support in the near future. In order to have a good experience we need to integrate with timeouts, rework how data is displayed, etc.

**Comment by moloch--** [comment]
This will be a feature in v1.5.0
