### ISSUE TITLE
The portfwd function bug

### ISSUE THREAD

**Issue by RedTeamWing** [BishopFox/sliver#435]
The portfwd function will make cpu usage very high. Is there any way to optimize this function?

![image](https://user-images.githubusercontent.com/25416365/121542661-e8591c00-ca3a-11eb-8cec-34b1abfa3296.png)

![image](https://user-images.githubusercontent.com/25416365/121543102-3e2dc400-ca3b-11eb-8f89-8bfa081ae98f.png)

And the connection is unstable, and occasionally the connection will be lost.
![image](https://user-images.githubusercontent.com/25416365/121543677-b09ea400-ca3b-11eb-96d0-1b31d466df84.png)

**Comment by moloch--** [comment]
We recommend using `wg-portfwd` if possible, it's much more stable than the in-band `portfwd` but we'll look into why this is happening too.

**Comment by rkervella** [comment]
The high CPU usage is probably due to a bug in the tunnel code. I can observe the same issue with the `shell` command.

**Comment by rkervella** [comment]
Closed by #490
