### ISSUE TITLE
Local SOCKS proxy that forwards all traffic to specific implant

### ISSUE THREAD

**Issue by mrpentest** [BishopFox/sliver#439]
**Is your feature request related to a problem? Please describe.**
Cobaltstrike has a nice little feature that saves a lot of time during use. The ability to create really fast local SOCKS proxy to forward traffic to specific beacons. This functionality along with proxychains can essentially make all linux tools available to any implant to use.

**Describe the solution you'd like**
A functionality when you are working with an implant to create a SOCKS proxy on a custom local port. All traffic sent to that port should be forwarded to the implant.

**Comment by moloch--** [comment]
This is available via the `wg-socks` command: https://github.com/BishopFox/sliver/wiki/Reverse-SOCKS
