### ISSUE TITLE
Cannot generate shared help

### ISSUE THREAD

**Issue by foxhaunt** [BishopFox/sliver#460]
**Describe the bug**
Cannot generate shared dll output

**To Reproduce**
1. Run Sliver on (Kali, ParrotOS, Ubuntu20, Windows)
2. generate --format shared --mtls 192.168.1.10
3. [*] Generating new windows/amd64 implant binary
[*] Symbol obfuscation is enabled
[!] rpc error: code = Unknown desc = open /root/.sliver/slivers/windows/amd64/SPATIAL_BONDSMAN/bin/SPATIAL_BONDSMAN.dll: no such file or directory

**Expected behavior**
Generate a exe or service works fine but it doesn't work for DLL.

**Desktop (please complete the following information):**
 - OS:  Kali_2020, ParrotOS_4.11, Windows 10, Ubuntu20

**Comment by moloch--** [comment]
Can you post the tail of your logs `~/.sliver/logs/sliver.log`, also you may want to read https://github.com/BishopFox/sliver/wiki/Cross-Compiling-Implants you will need to have cross-compilers installed to compile shared libraries.

**Comment by foxhaunt** [comment]
> Can you post the tail of your logs `~/.sliver/logs/sliver.log`, also you may want to read https://github.com/BishopFox/sliver/wiki/Cross-Compiling-Implants you will need to have cross-compilers installed to compile shared libraries.

Attached logs.  I've just figured out on "cgo: exec /usr/bin/x86_64-w64-mingw32-gcc: fork/exec /usr/bin/x86_64-w64-mingw32-gcc: no such file or directory"

Are you meaning that?

Thanks

**Comment by foxhaunt** [comment]
Solved: apt install mingw-w64
