### ISSUE TITLE
rpc error: code = Unknown desc = open /root/.sliver/slivers/windows/amd64/firstcloud/bin/firstcloud.dll: no such file or directory

### ISSUE THREAD

**Issue by prathap903** [BishopFox/sliver#463]
Tried compiling & the complied binaries same issue ..
![image](https://user-images.githubusercontent.com/40141080/124608263-34f21480-de8c-11eb-8856-5a8429ec497a.png)

**Comment by prathap903** [comment]
I tried the complied binaries as well instead of compiling its same issue. I found out that when i am in home folder with username sliver /home/sliver/.sliver this issue is popping up when i tried other home directory these no issue.

**Comment by moloch--** [comment]
Can you post the tails of logs, `~/.sliver/logs/sliver.log`
