### ISSUE TITLE
Failed to generate an implant in Server v1.4.17

### ISSUE THREAD

**Issue by thinkycx** [BishopFox/sliver#466]
**Describe the bug**
When use sliver to geneate a implant, it failed.

**To Reproduce**
1.   generate --mtls 10.XX.XX.XX --os linux
![image](https://user-images.githubusercontent.com/13138128/125280955-3b7b0300-e348-11eb-9fc1-f384e2c4ec3e.png)

And the error log is:
```
INFO[2021-07-12T19:34:40+08:00] [sliver/server/gogo/go.go:205] --- stderr ---
go: github.com/BurntSushi/xgb@v0.0.0-20210121224620-deaf085860bc: Get "https://proxy.golang.org/github.com/%21burnt%21sushi/xgb/@v/v0.0.0-20210121224620-deaf085860bc.mod": dial tcp 172.217.160.113:443: i/o timeout

INFO[2021-07-12T19:34:40+08:00] [sliver/server/gogo/go.go:206] exit status 1
ERRO[2021-07-12T19:34:40+08:00] [sliver/server/generate/binaries.go:651] Go mod tidy failed:
ERRO[2021-07-12T19:34:40+08:00] [github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/logging/logrus/options.go:215] finished unary call with code Unknown
```

**Expected behavior**
A implant will be generated.

**Desktop**
 - OS:  Linux 
 - Version: [*] Server v1.4.17 - 410f0756d26cb279216aecde68c14e68b5c9df32

**Comment by rkervella** [comment]
Does the `sliver-server` have internet access? There is currently no possibility to build implants in offline mode, as we are fetching modules at compile time. Please see #341 for more explanation.

**Comment by thinkycx** [comment]
> Does the `sliver-server` have internet access? There is currently no possibility to build implants in offline mode, as we are fetching modules at compile time. Please see #341 and #357 for more explanation.

I think the problem is that `sliver-server` cannot connect to "https://proxy.golang.org".
Same as the problem: https://github.com/BishopFox/sliver/issues/341
Counlt you tell me how to set the `-mod=vendor`  or how to set the proxy for `sliver-server` ?
@rkervella @moloch-- 

I have tried several ways, but all failed.
- set env 
```
 setenv http_proxy socks5://xxxx
 setenv https_proxy socks5://xxxx
```
- proxychains4

**Comment by rkervella** [comment]
The proxy settings would have to be set in the server code. I'm not sure the `go` toolchain respects the `http_proxy` and `https_proxy` environment variables by default.

As for vendored builds, the solution is a bit more involved than just adding `-mod=vendor` to the compilation command arguments: we would need to push the vendored code (e,g: the `vendor` directory) with the implant code, which we currently don't do.

**Comment by thinkycx** [comment]
> The proxy settings would have to be set in the server code. I'm not sure the `go` toolchain respects the `http_proxy` and `https_proxy` environment variables by default.
> 
> As for vendored builds, the solution is a bit more involved than just adding `-mod=vendor` to the compilation command arguments: we would need to push the vendored code (e,g: the `vendor` directory) with the implant code, which we currently don't do.

`-mod vendor` Do you mean build the `sliver-server` from source code with `-mod=vendor` ? 
Is there any docs for it ?

**Comment by rkervella** [comment]
No, I mean adding a `vendor` directory [here](https://github.com/BishopFox/sliver/tree/master/implant) that would contain the implant's vendored dependencies. The way Sliver works is that the server compiles the implant code on the fly from a copy of this folder. Without vendored dependencies, you need to have internet access at build time for the embedded go toolchain to download the implant dependencies.

We haven't found a good way so far to vendor the implant code.

**Comment by moloch--** [comment]
The `generate` command basically automates interactions with the go compiler inside the sliver server to compile the implant. Due to complexities in the way this workflow is implemented it's difficult to add `-mod vendor` to it, which is why we currently just rely on the default golang behavior of fetching modules at compile time.

**Comment by moloch--** [comment]
The server should cache modules however, so if possible a work around is to compile one implant with the server connected to the internet, you should then be able to compile subsequent implants without an internet connection so long as the module cache is not invalidated.

**Comment by thinkycx** [comment]
> No, I mean adding a `vendor` directory [here](https://github.com/BishopFox/sliver/tree/master/implant) that would contain the implant's vendored dependencies. The way Sliver works is that the server compiles the implant code on the fly from a copy of this folder. Without vendored dependencies, you need to have internet access at build time for the embedded go toolchain to download the implant dependencies.
> 
> We haven't found a good way so far to vendor the implant code.

Could I download the files in vendor/ [here](https://github.com/BishopFox/sliver/tree/master/implant) so that the `sliver-server` will find the dependencies?

Where should I put the dependencies into ?  In the directory `~/.sliver/go`?   @rkervella

**Comment by moloch--** [comment]
That's not the way it works. You cannot add a `vendor/` directory to the implant build. The file system structure of the implant is built on the fly using code generation, so you'd need to modify the `generate` code to make it work.

My recommendation is to do one build with an internet connection, which should cache the modules.

Also, the `sliver-server` complication process is entirely separate from `generate`, you do not need to modify anything related to compiling `sliver-server`

**Comment by thinkycx** [comment]
> That's not the way it works. You cannot add a `vendor/` directory to the implant build. The file system structure of the implant is built on the fly using code generation, so you'd need to modify the `generate` code to make it work.
> 
> My recommendation is to do one build with an internet connection, which should cache the modules.
> 
> Also, the `sliver-server` complication process is entirely separate from `generate`, you do not need to modify anything related to compiling `sliver-server`

As you mentioned, the `sliver-server`  generate only works with an internet connection. I think it will not works in my env.

Maybe  the `generate` command should support the GOPROXY  like `go env -w GOPROXY=https://goproxy.cn,direct` and it will works.

**Comment by moloch--** [comment]
That is an open issue #357 if you implement it send us a PR :)

**Comment by thinkycx** [comment]
> That is an open issue #357 if you implement it send us a PR :)

Thank you very much.
 If I meet the problem in future, I will look up into it and study your code.
