### ISSUE TITLE
Windows Defender Regression with V1.4.19 

### ISSUE THREAD

**Issue by Laransec** [BishopFox/sliver#467]
**Describe the bug**
Windows Defender is flagging on a static series of bytes on version 1.4.19. 1
  It might be related to the Wire Guard implementation after fixing that signature in Issue #404 . 

1. generate -e -m 127.0.0.1
2. Transfer to a computer with Mid July Defender signatures. 
3. Be Sad =( 

I ran two generated binaries through RastaMouse's ThreatCheck and it flagged this area of bytes in both. It looks like it does not get garbled differently per binary. 
![ThreatCheck](https://user-images.githubusercontent.com/25284456/125372395-03c48900-e351-11eb-933c-407d6e043fab.PNG)

**Comment by moloch--** [comment]
We'll look into it, Garble doesn't obfuscate object code only symbols so if the signature isn't a symbol it's not really expected to change... until Go 1.17 comes out and changes the Go ABI ;)

**Comment by rkervella** [comment]
On a side note, I've been looking at what gets flagged, and the section displayed here (and the offset) lands in the runtime code, more specifically, the [runtime.newosproc](https://cs.opensource.google/go/go/+/refs/tags/go1.16.6:src/runtime/os_windows.go;l=831) function.

Here's the obfuscated function:
![image](https://user-images.githubusercontent.com/44028017/125432774-1c6e7acb-a573-49c1-a59e-dcae2b07133b.png)

Here's the same from a non obfuscated build:

![image](https://user-images.githubusercontent.com/44028017/125432876-018c974c-8da5-43fd-9368-cfe0b50f5ef1.png)

So I would suspect that Sliver executable binaries are not the only Go binaries getting flagged by this rule.

**Comment by Laransec** [comment]
Thanks for checking it out! That's not a good signature if it's flagging right there. I can see some very innocent binaries getting eaten.

**Comment by rkervella** [comment]
Ok so my suspicions  were correct: I just compiled another of my personal projects with `garble -tiny -literals` (same options as Sliver), and Defender flags it on the same function:

![image](https://user-images.githubusercontent.com/44028017/125437062-d91eaabd-d203-46e3-bf5b-6fc678b8f3eb.png)

In the screenshot, `aa.exe` is an obfuscated Sliver build, `aws2.exe` is a build of [aws-info](https://github.com/lesnuages/aws-info) which is a benign program.

**Comment by rkervella** [comment]
More tests: looks like it's the `-tiny` option from garble that generate the flagged portion of the code. Removing it from the command line [here](https://github.com/BishopFox/sliver/blob/master/server/gogo/go.go#L140) will generate a Sliver binary that is not flagged anymore.
