### ISSUE TITLE
Nicer article for begineers  :)

### ISSUE THREAD

**Issue by Darkcast** [BishopFox/sliver#469]
I found that the wiki is very well written but some people me included are a bit more visual and step by step learners so I found this article and I thought someone else would benefit from it and cut down on question for the tool 
[](https://vk9-sec.com/how-to-set-up-use-c2-sliver/)

ps. awesome work guys at this rate youll be putting other c2 out of business

**Comment by rkervella** [comment]
@Darkcast which article are you referring to?

**Comment by Darkcast** [comment]
> @Darkcast which article are you referring to?

I am deeply sorry my brain wasnt working 
i found this article althought not perfect it would help begginers to set up sliver since its structured step by step
yes I know some of us want our hands to be held throught out the process ( we are lonely hahahaha)
hope this gives you an idea of what I mean
https://vk9-sec.com/how-to-set-up-use-c2-sliver/
Ps. amazing work on the tool, thank you for all the hard work

**Comment by moloch--** [comment]
https://github.com/BishopFox/sliver/wiki/Community-Guides
