### ISSUE TITLE
Windows Defender detecting payloads with v1.4.20

### ISSUE THREAD

**Issue by hardwaterhacker** [BishopFox/sliver#481]
Windows Defender is alerting on payloads exe implants.  After talking with @moloch-- , it may be related to a previous issue, #467.  Generating implants with `generate -e -f exe -H https://foo.tld` results in detection by Windows Defender as of 7/27/21 (see image below, generated by DefenderCheck).  Appears to be detecting `sliverpb` in the implant.  I generated several payloads and all were detected with the same signature, so this appears to be consistent across repeated generation.

![image](https://user-images.githubusercontent.com/8193110/127254956-e1b3c1eb-884c-4da4-8ce8-a24390f41d9a.png)

**Comment by rkervella** [comment]
@hardwaterhacker are you sure you're on 1.4.20 / that obfuscation is enabled? I can't reproduce on 1.4.20 or later. The strings are not even present in the final binary, and `ThreatCheck` returns `no threat` when I scan the generated implant.

**Comment by hardwaterhacker** [comment]
So, apparently I'm a moron.  I built several different sliver server versions yesterday trying to test that and another issue, and apparently I never went back to 1.4.20.  picardfacepalm.gif.

**Comment by rkervella** [comment]
Glad you sorted things out :)
