### ISSUE TITLE
Shell command is some way broken?

### ISSUE THREAD

**Issue by h0nus** [BishopFox/sliver#488]
**Describe the bug**
When using "shell" command, the tunnel just won't open and die

**To Reproduce**
1. use 6 (number of shell)
2. shell
3. tunnel die

**Expected behavior**
To open a shell, old version was working

**Screenshots**
![image](https://user-images.githubusercontent.com/23401728/127861963-661e258f-e738-4c9a-ac60-b9c70b937dc1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (client) | server 
 - Version : v1.4.20

**Additional context**
Tried on server and client aswell, same issue.

**Comment by h0nus** [comment]
I don't understand lol restarting the server, fixed this O.o

**Comment by hayasec** [comment]
The same problem is again.
