### ISSUE TITLE
Show file/directory/etc permissions when using 'ls' command (like ls -l)

### ISSUE THREAD

**Issue by 0xhaggis** [BishopFox/sliver#498]
**Permissions make life easier on unix platforms**
This type of output:

`-rwsr-xr-x. 1 root root 27856 Mar 31  2020 /usr/bin/passwd`

is more useful than this type of output:

`passwd                              27.2 KiB`

It would be nice to have an optional flag for 'ls' to see permissions, user/group data, etc. I know we can use `execute ls -l /path/to/foo`, but I'm lazy and don't like typing.

**Comment by rkervella** [comment]
I just merged #497 today into master, it should solve that and add a few more feature like sorting by date or size.

**Comment by rkervella** [comment]
One thing to note though, we don't extract the user/group info, but the perms are present. On Linux and Unix systems it shouldn't be too difficult, on Windows it's going to require a bit more code though.
