### ISSUE TITLE
Support stdout/stderr redirection with the "execute" command

### ISSUE THREAD

**Issue by 0xhaggis** [BishopFox/sliver#499]
**I learned the hard way that redirection doesn't work with 'execute'**
I tried to issue a command like this: `execute find / -perm -4000 2>/dev/null` only to find that redirection didn't work and Sliver funneled a million lines of "permission denied" from my implant to my server!

Dropping to a shell makes redirection possible, but dropping to a shell should be a last resort wherever possible.

Can 'execute' be updated to do stdout/stderr redirection on the implant side?

**Comment by rkervella** [comment]
Shell redirection is currently not supported. There's probably a way to use `Cmd.StdoutPipe` and `Cmd.StderrPipe` to handle that, but that will require some custom parsing on the client side to make the implant aware of the syntax.

The ugly workaround would be `execute bash -c 'find / -perm -4000 2>/dev/null'`.

**Comment by moloch--** [comment]
Yea @0xhaggis `execute` is basically Popen so fancy bash redirects like `2>/dev/null` would be complicated to implement, but could potentially add redirect flags like `--stdout=/dev/null`

**Comment by 0xhaggis** [comment]
In C it's pretty easy because popen(3) passes user-supplied commands to "sh -c", which honors redirection. I haven't looked at Go's implementation, I'm guessing it doesn't pass to "sh -c" because cross-platform reasons, which... ok, yeah I see. I'll close this one for now until I fancy a bit of a project.

**Comment by rkervella** [comment]
Yeah it's not that straightforward in Go. `Cmd.Run` is basically a wrapper around the `execve` syscall on Unix/Linux, and `CreateProcessA` on Windows, which gives us on one hand the advantage of not having to execute bash/sh/cmd.exe/whatever (so nothing in the user's history), with the disadvantage of not supporting more complex interpreter semantics out of the box, like input/output redirection.

**Comment by moloch--** [comment]
I think it would be simple to add cross-platform execute flags for `--stdout` and `--stderr` instead of using [`CombinedOutput`](https://github.com/BishopFox/sliver/blob/master/implant/sliver/handlers/handlers.go#L380). We should be able to pass in any `io.writer` to the subprocess.

**Comment by rkervella** [comment]
Yeah doing it that way is easy. Supporting the common shells redirection syntax won't be, and I don't think we should aim for it.

**Comment by 0xhaggis** [comment]
Using `--stdout` and `--stderr` arguments to `execute` is the cleanest and most Sliver-consistent way of doing it. And it's super useful!

**Comment by rkervella** [comment]
@0xhaggis so I made some changes, and now we automatically capture stderr and stdout, and send the info back to the client. It's up to the client whether it wants to print out stderr or not, which results in this kind of output:

```
[server] sliver (OPEN_RIFLE) > execute find /usr -perm -4000

[!] Exited with status 1!
[*] Stdout:
/usr/bin/top
/usr/bin/atq
/usr/bin/crontab
/usr/bin/atrm
/usr/bin/newgrp
/usr/bin/su
/usr/bin/batch
/usr/bin/at
/usr/bin/quota
/usr/bin/sudo
/usr/bin/login
/usr/libexec/security_authtrampoline
/usr/libexec/authopen
/usr/sbin/traceroute6
/usr/sbin/traceroute

[*] Stderr:
find: /usr/sbin/authserver: Permission denied


[server] sliver (OPEN_RIFLE) > execute --ignore-stderr find /usr -perm -4000

[!] Exited with status 1!
[*] Stdout:
/usr/bin/top
/usr/bin/atq
/usr/bin/crontab
/usr/bin/atrm
/usr/bin/newgrp
/usr/bin/su
/usr/bin/batch
/usr/bin/at
/usr/bin/quota
/usr/bin/sudo
/usr/bin/login
/usr/libexec/security_authtrampoline
/usr/libexec/authopen
/usr/sbin/traceroute6
/usr/sbin/traceroute
```

Would that work for you?

**Comment by moloch--** [comment]
I think there's also a use case for the request to specify alternate stdout/stderr streams, for example to output to a file on the remote system (though `--ignore-stderr` is certainly nice to have baked in).

**Comment by rkervella** [comment]
Yeah I was wondering whether it would be a good idea or not. Can definitely add that though.

**Comment by moloch--** [comment]
Operationally probably not a good idea, but I think it would still be useful. The Conti Ransomware book showed them constantly dumping commands to local files, so would be useful for emulating certain actors.

**Comment by rkervella** [comment]
Alright, here's the new output:

```
[server] sliver (ELABORATE_QUILT) > execute --stderr '/dev/null' --stdout '/tmp/out' find /usr -perm -4000

[*] StdOut saved at /tmp/out
[*] Stderr saved at /dev/null
[!] Exited with status 1!

[server] sliver (ELABORATE_QUILT) > rm /tmp/out

[*] /tmp/out

[server] sliver (ELABORATE_QUILT) > execute --stderr '/dev/null' find /usr -perm -4000

[*] Output:
/usr/bin/top
/usr/bin/atq
/usr/bin/crontab
/usr/bin/atrm
/usr/bin/newgrp
/usr/bin/su
/usr/bin/batch
/usr/bin/at
/usr/bin/quota
/usr/bin/sudo
/usr/bin/login
/usr/libexec/security_authtrampoline
/usr/libexec/authopen
/usr/sbin/traceroute6
/usr/sbin/traceroute
[*] Stderr saved at /dev/null
[!] Exited with status 1!

[server] sliver (ELABORATE_QUILT) > execute find /usr -perm -4000

[*] Output:
/usr/bin/top
/usr/bin/atq
/usr/bin/crontab
/usr/bin/atrm
/usr/bin/newgrp
/usr/bin/su
/usr/bin/batch
/usr/bin/at
/usr/bin/quota
/usr/bin/sudo
/usr/bin/login
/usr/libexec/security_authtrampoline
/usr/libexec/authopen
/usr/sbin/traceroute6
/usr/sbin/traceroute
[*] StdErr:
find: /usr/sbin/authserver: Permission denied
[!] Exited with status 1!

[server] sliver (ELABORATE_QUILT) > execute --stdout '/tmp/out.log' find /usr -perm -4000

[*] StdOut saved at /tmp/out.log
[*] StdErr:
find: /usr/sbin/authserver: Permission denied
[!] Exited with status 1!
```

**Comment by moloch--** [comment]
Looks good to me, @0xhaggis does this meet your use case?
