### ISSUE TITLE
Add a proxy option to HTTPS implants?

### ISSUE THREAD

**Issue by blahblah5555** [BishopFox/sliver#507]
I think it would be nice to have a --proxy option when using https listeners along with a lets encrypt implementation whereby starting a listener would look like the following:

```
https --proxy --target-domain google.com --listener-domain example.com --lets-encrypt
```

This should have similar functionality to evilginx whereby it's possible to proxy a target website via the https listener.

**Comment by rkervella** [comment]
That's probably something you want to handle with a redirector in from of your Sliver server.

**Comment by blahblah5555** [comment]
i'll give it a go thanks for the quick response :)
