### ISSUE TITLE
Implant - Proxy Aware

### ISSUE THREAD

**Issue by b4b857f6ee** [BishopFox/sliver#511]
**Describe the bug**
Hello,
Quick question, after i've read the documentation and try to find the info in this issues, i can't find if the implants are proxy aware?
I think they are not right?

Thank you for your answer

**Comment by moloch--** [comment]
Implants are proxy aware in most cases, internally we use https://github.com/rapid7/go-get-proxied to determine the proxy settings.

**Comment by b4b857f6ee** [comment]
Ok, great, i've read one line about this go, but i was not sure if this was effective or not.
Thank you for your very QUICK answer :D!!
BTW : If i configure multiple domain, the implant is going to check each one at the start or just the first and if it's work, stay with it?
I got this problem with poshC2 so during readteam exercice they can see all the domain in the first communication ^^.

Thank you for you answer.

**Comment by moloch--** [comment]
In the current release version (v1.4.21) the implant will only fallback on connection errors, in the upcoming v1.5.0 release we're adding support for different types of connection strategies that are configurable.

**Comment by b4b857f6ee** [comment]
> 
> 
> In the current release version (v1.4.21) the implant will only fallback on connection errors, in the upcoming v1.5.0 release we're adding support for different types of connection strategies that are configurable.

Waou, this is F**** awesome.
Keep the good work!
