### ISSUE TITLE
DNS named configuration + HTTP implant issue

### ISSUE THREAD

**Issue by b4b857f6ee** [BishopFox/sliver#514]
Hello,

I'm trying to configure the DNS : https://github.com/BishopFox/sliver/wiki/DNS-C2

Ubuntu 18.04 and last sliver

I'm in a virtual systeme. I got a fake IT system and a fake internet docker using inetsim and a named DNS.
I configure the named.conf file with :
mysliverdomain IN A MySliverIP
ns1.mysliverdomain IN A MySliverIP
1.mysliverdomain IN A MySliverIP

but i don't have any answer when i start the DNS payload :/
I generate it with --dns 1.mysliverdomain.
My fake IT systeme use a dns forwarder and i can see _6938IE.NAME_PAYLOAD._domainkey.1.mysliverdomain but nothing seems to reach my sliver VM... I don't get what i'm missing.
Thank you for your help.

With an http implant, it's work. Even if i got multiple shell pop up instead of 1 i got one new every 3 min ^^.

**Comment by moloch--** [comment]
Check the logs `~/.sliver/logs/sliver.log` for errors, some DNS resolvers simply don't work well with the current DNS tunnel implementation but this should hopefully be addressed in v.1.5.0 later this year.

**Comment by hayasec** [comment]
Hello, moloch-- 
When will v.1.5.0 be released?

**Comment by moloch--** [comment]
Hopefully by EOY, just finishing up the last major feature today.

**Comment by moloch--** [comment]
v1.5 is out!
