### ISSUE TITLE
https listener question

### ISSUE THREAD

**Issue by every1110** [BishopFox/sliver#520]
Hi, Can someone please help? when i try to run https listener i get:
[*] Starting HTTPS :443 listener ...

[*] Successfully started job #1

[!] Job #1 stopped (tcp/https)

[!] Job #1 stopped (tcp/https)

On 443 port i have apache web server, any ideas how to use https listener in this case? TNX

**Comment by moloch--** [comment]
If you already have a web server running on port 443 you'll be unable to bind any other program to the port (including Sliver). You can bind to an alternate port using the `--lport` flag.
