### ISSUE TITLE
Desactivate Anti-forensics

### ISSUE THREAD

**Issue by b4b857f6ee** [BishopFox/sliver#521]
Hello,

This is possible to desactivate the anti-forensics during the payloads generation?

Thank you :)

**Comment by rkervella** [comment]
What are you specifically referring to?

**Comment by b4b857f6ee** [comment]
> 
> 
> What are you specifically referring to?

Thank you for your answer,

In the Features "Anti-anti-anti-forensics"

**Comment by rkervella** [comment]
Oh, well in that case you might just want to build an implant in `--debug` mode:

```
generate --debug --mtls whatever.com
```

I think this feature just refers to a specific check on Windows to see if a debugger is attached, nothing crazy. It is disabled in debug mode, as well as obfuscation of the payload. If you need something in between, you'll need to modify the implant code to remove what you don't want to appear in the final binary.

The relevant code is [here](https://github.com/BishopFox/sliver/blob/master/implant/sliver/limits/limits_windows.go#L48-L59).

**Comment by rkervella** [comment]
Heh strike that, looks like it's not disabled in debug, you'll need to edit the implant code to remove it / comment it first.

**Comment by moloch--** [comment]
`generate --skip-symbols` will also disable the obfuscation while still removing some of the debug print statements, which could be good for students.

**Comment by b4b857f6ee** [comment]
OHHHHHHHHHHH Great!!

Thank you all :D!!!!

**Comment by b4b857f6ee** [comment]
> 
> 
> `generate --skip-symbols` will also disable the obfuscation while still removing some of the debug print statements, which could be good for students.

I remember now to read it somewhere on this github.
Any way thank you!!
