### ISSUE TITLE
Align portfwd and wg-portfwd semantics

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#537]

**Comment by a3sroot** [comment]
1、I suggest that if socks5 is available, the wireguard feature is too obvious.
2、Multi level agent can be considered. The agent forwards the server port to the local implementation with less code.
3、Has the communication of 1.5 been completed?

**Comment by moloch--** [comment]
Almost done, just sorted out the big problems with DNS :) sorry about the delays but been busy at work!
