### ISSUE TITLE
[!] rpc error: code = InvalidArgument desc = Missing session request field

### ISSUE THREAD

**Issue by um3ha4a** [BishopFox/sliver#539]
**Describe the bug**
execute-assembly faces "[!] rpc error: code = InvalidArgument desc = Missing session request field" error

**To Reproduce**
1.use 1
2.execute-assembly c#/SharpSMBExec.exe

**Expected behavior**
Run successful.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: server on linux, client tried both
 - Version 1.5.0 beacon

**Additional context**
Tried some c# exe, tried -a x64, -a x86, full or short exe path, but all return Missing session request field

**Comment by um3ha4a** [comment]
by th way the help message retrurns -a default "x84"

execute-assembly -h

Command: execute-assembly [local path to assembly] [arguments]
About: (Windows Only) Executes the .NET assembly in a child process.


Usage:
======
  execute-assembly [flags] filepath [arguments...]

Args:
=====
  filepath   string         path the assembly file
  arguments  string list    arguments to pass to the assembly entrypoint (default: [])

Flags:
======
  -d, --app-domain string    AppDomain name to create for .NET assembly. Generated randomly if not set.
  -a, --arch       string    Assembly target architecture: x86, x64, x84 (x86+x64) (default: x84)
  -c, --class      string    Optional class name (required for .NET DLL)
  -h, --help                 display help
  -X, --loot                 save output as loot
  -m, --method     string    Optional method (a method is required for a .NET DLL)
  -p, --process    string    hosting process to inject into (default: notepad.exe)
  -s, --save                 save output to file
  -t, --timeout    int       command timeout in seconds (default: 60)

**Comment by rkervella** [comment]
Should be fixed in 77ddf23.
