### ISSUE TITLE
Umlauts and invalid UTF-8

### ISSUE THREAD

**Issue by cmprmsd** [BishopFox/sliver#544]
**Describe the bug**
When we try commands and the command output contains umlauts, we get an error about invalid UTF8 in the output string.

**To Reproduce**
1. Run e.g. the following on a Windows implant on a German Windows: `execute -o -t 3 cmd /c "net user"` (same for `execute -o net user`)
2. See the error `[!] rpc error: code = Unknown desc = string field contains invalid UTF-8`

Then when we use cat to output the file invalid UTF-8 strings will be stripped:
`Der Befehl wurde erfolgreich ausgefhrt.`
the correct text would be:
`Der Befehl wurde erfolgreich ausgeführt.`

**Expected behavior**
The output should be converted and umlauts should be displayed correctly.

**Desktop (please complete the following information):**
 - OS: Windows implant
 - Version stage v1.4.22 - 03d1f92441f3a0105abdeccec1596bda56fcc55c dirty

**Additional context**
This should make problems in many languages not only German.

**Comment by moloch--** [comment]
@rkervella should we make stdout/stderr `bytes` instead of `string`? This sounds like a limitation in the protobuf?

**Comment by rkervella** [comment]
Yeah I looked that up and it seems to be the only solution I can find.

**Comment by cmprmsd** [comment]
Hey hey, it seems the fix works partially.

Output is now working. But the characters are still removed from the output:

```shell
Anforderungen fr Hyper-V
# instead of
Anforderungen für Hyper-V

Maximale Gr�:
# instead of 
Maximale Größe:

```

This might be an issue in file paths as well :man_shrugging:

**Comment by rkervella** [comment]
Not sure if we'll be able to fix that, I need to investigate more on why protobuf has such limitations in the first place.

**Comment by cmprmsd** [comment]
Thank you for investigating the issue. 

It seems protobuf does handle data streams as bytes and not as strings, so all data would have to be base64 encoded. Maybe you assume it's able to handle UTF-8 text transports. 

https://stackoverflow.com/questions/14189808/when-using-google-protocol-buffers-to-transfer-string-character-got-messy-code

**Comment by rkervella** [comment]
> Thank you for investigating the issue.
> 
> It seems protobuf does handle data streams as bytes and not as strings, so all data would have to be base64 encoded. Maybe you assume it's able to handle UTF-8 text transports.
> 
> https://stackoverflow.com/questions/14189808/when-using-google-protocol-buffers-to-transfer-string-character-got-messy-code

Yes that was mainly our assumption. Encoding prior to serializing would probably work indeed. I'll give it a shot.

**Comment by cmprmsd** [comment]
What... the.. Today I learned, there is codepages in Windows: https://stackoverflow.com/questions/16598785/save-text-file-in-utf-8-encoding-using-cmd-exe

I tried to copy some umlauts text into a textfile with notepad, which works as you showed.

Then I went back to run `systeminfo` and it swallowed the umlauts again.

I redirected `systeminfo > output` to a file and saw the are missing there too. So this is no issue of Sliver.

I chose a shorter command as this issue happens with all commands on a German Windows
```shell
sliver (TENDER_RUTH) > execute -o net user

[*] Output:

Benutzerkonten fr \\DESKTOP-VQMVTED

-------------------------------------------------------------------------------
Administrator            DefaultAccount           Gast
user                     WDAGUtilityAccount
Der Befehl wurde erfolgreich ausgefhrt.


sliver (TENDER_RUTH) > execute -o cmd /c "net user"

[*] Output:

Benutzerkonten fr \\DESKTOP-VQMVTED

-------------------------------------------------------------------------------
Administrator            DefaultAccount           Gast
user                     WDAGUtilityAccount
Der Befehl wurde erfolgreich ausgefhrt.


sliver (TENDER_RUTH) > execute -o cmd /c "chcp 65001 && net user"

[*] Output:
Aktive Codepage: 65001.

Benutzerkonten fr \\DESKTOP-VQMVTED

-------------------------------------------------------------------------------
Administrator            DefaultAccount           Gast
user                     WDAGUtilityAccount
Der Befehl wurde erfolgreich ausgefhrt.

```
The upper should all contain `für` amd `ausgeführt`.

All these variants will not output the umlauts correctly.
I wondered why this is and found out that windows commands behave differently.

```shell
sliver (TENDER_RUTH) > execute -o cmd /c "chcp 65001 && systeminfo"

[*] Output:
Aktive Codepage: 65001.
...
Anforderungen für Hyper-V:                     Es wurde ein Hypervisor erkannt. Features, die für Hyper-V erforderlich sind, werden nicht angezeigt.
```

When I run an interactive shell I also will lose umlauts only with `net user` but not with `systeminfo`. :nauseated_face: 

I have not idea how this could be solved in any feasible way as this is a Microsoft issue. :(
I see that other repositories also had similar issues (https://github.com/SecureAuthCorp/impacket/issues/708) 

Thank you for investigating this with me and at least for "updated" commands like `systeminfo` we can use the chcp 65001 (UTF-8) workaround. :smile:

**Comment by rkervella** [comment]
Yeah I was about to say it's something about Windows and codepoints, but I was expecting something like "we're running the sliver client on Windows" which could have explained the output. Turns out it's even weirder than I first thought.

I'm not sure we can do much here, should I re-close this one?

**Comment by cmprmsd** [comment]
Sure let me close it :)
