### ISSUE TITLE
Process List with CmdLine

### ISSUE THREAD

**Issue by cmprmsd** [BishopFox/sliver#546]
**Describe the bug**
Currently on Windows 20H2 at least (language independent) the `ps -c` command does not list the cmdline.

**To Reproduce**
1. connect a Windows implant
2. `ps -c` or `ps --print-cmdline`
4. See same output with and without `-c`

**Expected behavior**
Full list of cmdlines if possible from the implants user context

**Desktop (please complete the following information):**
 - OS: Windows implant
 - Version v1.4.22

**Additional context**
A possible workaround for the moment is to `execute powershell Get-WmiObject Win32_Process | select name, commandline`.
It seems `get-process` does not provide the commandline option so you'd have to use Get-WmiObject or `gwmi` in short.
I'm not sure how Go accesses the Windows API natively but that's some hints for other red teamers. :)

**Comment by lesnuages** [comment]
Yeah I haven't implemented that yet.

**Comment by usiegl00** [comment]
I would like to take a look at implementing this one.
Should I use wmi with github.com/mattn/go-ole?
Or should I use OpenProcess as in https://stackoverflow.com/a/37408846?

**Comment by moloch--** [comment]
ideally we'd like to avoid additional dependencies, so if possible we'd want to call into the win32 APIs directly.

**Comment by usiegl00** [comment]
In that case, which is less detectable?
WMI is more likely to trigger logging in my opinion.

**Comment by moloch--** [comment]
Is there really no way in Windows other than calling OpenProcess on every proc? What a joke of an OS.

**Comment by usiegl00** [comment]
I found one project using CreateToolhelp32Snapshot with Module32FirstW.
What do you think?

**Comment by moloch--** [comment]
Sounds good!

**Comment by moloch--** [comment]
Branch from `stage` to make merging easier

**Comment by usiegl00** [comment]
I went all the way through using Module32FirstW until I found that it only gets the executable path.
I'll have to use OpenProcess then... :-P

**Comment by moloch--** [comment]
As long as we don't need `PROCESS_ALL_ACCESS` we should be fine

**Comment by usiegl00** [comment]
Yes, I am using `PROCESS_QUERY_INFORMATION` and `PROCESS_VM_READ`.
I've decided to keep the `Module32FirstW`, because it is the best way to get the executable path.

**Comment by rkervella** [comment]
Fixed in #549 , I will close this one once 1.5 is released.
Thanks @usiegl00 !

**Comment by cmprmsd** [comment]
@usiegl00 Thank you. This was fast 😆

**Comment by moloch--** [comment]
Nice work!
