### ISSUE TITLE
dns c2 Failed to decrypt session init msg

### ISSUE THREAD

**Issue by um3ha4a** [BishopFox/sliver#556]
**Describe the bug**
dns c2 don't work.

**To Reproduce**
generate -d 1.mydomain.com.
dns -d 1.mydomain.com.
version is v1.5.0_beacon

**Expected behavior**
dns c2 connect propertly

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10

**Additional context**
tail -f /root/.sliver/logs/sliver.log
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:169] '9h5wxb6544fhy9qk1e1ubw14dpmrhu41386bd7qh132cpu6k5fykarkxzt77pvz.xpar764x0vybv5ccytnxne3vg8gb2gt90r6g3cxf7a487kyud44pmdwhrq147ht.475g6ze954tuna1ztz28u64faqjq26ywbk5ynpuckwxr.aaaaaaa.b4q8ngldyr._.si.1.mydomain.com.' is subdomain of '1.mydomain.com.'
DEBU[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:150] '9h5wxb6544fhy9qk1e1ubw14dpmrhu41386bd7qh132cpu6k5fykarkxzt77pvz.xpar764x0vybv5ccytnxne3vg8gb2gt90r6g3cxf7a487kyud44pmdwhrq147ht.475g6ze954tuna1ztz28u64faqjq26ywbk5ynpuckwxr.aaaaaaa.b4q8ngldyr._.si.1.mydomain.com.' is subdomain of c2 parent '1.mydomain.com.'
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:183] processing req for subdomain = 9h5wxb6544fhy9qk1e1ubw14dpmrhu41386bd7qh132cpu6k5fykarkxzt77pvz.xpar764x0vybv5ccytnxne3vg8gb2gt90r6g3cxf7a487kyud44pmdwhrq147ht.475g6ze954tuna1ztz28u64faqjq26ywbk5ynpuckwxr.aaaaaaa.b4q8ngldyr._.si
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:377] [start session] fields = []string{"9h5wxb6544fhy9qk1e1ubw14dpmrhu41386bd7qh132cpu6k5fykarkxzt77pvz", "xpar764x0vybv5ccytnxne3vg8gb2gt90r6g3cxf7a487kyud44pmdwhrq147ht", "475g6ze954tuna1ztz28u64faqjq26ywbk5ynpuckwxr", "aaaaaaa", "b4q8ngldyr", "_", "si"}
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:369] Domain contains 3 subdata fields
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:169] 'b4q8ngldyr._._si.1.mydomain.com.' is subdomain of '1.mydomain.com.'
DEBU[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:150] 'b4q8ngldyr._._si.1.mydomain.com.' is subdomain of c2 parent '1.mydomain.com.'
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:183] processing req for subdomain = b4q8ngldyr._._si
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:377] [start session] fields = []string{"b4q8ngldyr", "_", "_si"}
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:392] Complete session init message received, reassembling ...
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:408] Failed to decrypt session init msg
INFO[2021-12-28T09:34:51+07:00] [sliver/server/c2/dns.go:283] Error during session init: decryption failed

**Comment by moloch--** [comment]
Use `stage` (the latest in the v1.5 branch) there was a bug fixed in the dns channel since `v1.5.0_beacons`

**Comment by um3ha4a** [comment]
But the payload from stage branch generated is flagged by anti-virus, v1.5.0_beacons not. Is there another branch works fine with dns c2?

**Comment by moloch--** [comment]
Not really tbh, you should use a loader or stager to avoid Anti-virus. While we try to minimize our exposure to AV it's a specific goal of this project.
