### ISSUE TITLE
Shell Command Adult flag or configuration

### ISSUE THREAD

**Issue by kernelzeroday** [BishopFox/sliver#564]
**Is your feature request related to a problem? Please describe.**
When spawning a shell in sliver the C2 asks if I am an adult before allowing me to spawn a shell. 

**Describe the solution you'd like**
Disable this feature through configuration or a flag

**Describe alternatives you've considered**
Add a (Y/n/always) option or something please

**Additional context**
I understand that opening a shell on the system can be a visible action, however the shell is great and very useful and it's possible to act in a responsible manner while using it.  Pressing Y manually every time is less fun when the rest of sliver is very quick to interact with.

**Comment by moloch--** [comment]
There's a setting for this in v1.5 (see `settings` cmd)
