### ISSUE TITLE
Can not kill jobs in v1.5

### ISSUE THREAD

**Issue by dhauenstein** [BishopFox/sliver#575]
**Describe the bug**
Can not kill jobs

**To Reproduce**
1. Create a job, for instance: `dns -d hax0r.domain`
2. List jobs:
```
sliver > jobs 

 ID   Name   Protocol   Port 
==== ====== ========== ======
 1    dns    udp        53   

```
3. Kill job 1 with `job -k 1`
4. Error is `[!] rpc error: code = Unknown desc = invalid Job ID`. Same is true for `jobs -K`

**Expected behavior**
I expect jobs to be killed, either by job id and/or all jobs. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.5

**Comment by moloch--** [comment]
Lol, funny how flipping a boolean value the wrong way can cause problems hehe.

**Comment by moloch--** [comment]
Going to wait a bit to mint a v1.5.1 in case other bugs pop up, fix is in `master` for now.
