### ISSUE TITLE
use command busted in v1.5

### ISSUE THREAD

**Issue by pooki3bear** [BishopFox/sliver#576]
**Describe the bug**
`sessions -i abcdefg` works fine
`use abcdefg` no longer works

**To Reproduce**

**Expected behavior**
`sessions -i` and `use` should perform the same function

**Screenshots**
<img width="500" alt="Screen Shot 2022-01-24 at 8 15 25 AM" src="https://user-images.githubusercontent.com/24210410/150821351-6344aea4-694e-4441-8823-cbcb155c245f.png">

**Desktop (please complete the following information):**
 - OS: linux
 - Version [e.g. v0.0.5]

**Comment by moloch--** [comment]
Weird ... must be related to the type change, does the tab complete work?

**Comment by pooki3bear** [comment]
Tab complete expands to the full UUID and works
<img width="706" alt="Screen Shot 2022-01-24 at 8 22 33 AM" src="https://user-images.githubusercontent.com/24210410/150822342-18d49ccd-e2a0-4e82-950b-bce4232b028c.png">

**Comment by moloch--** [comment]
Figured it out there was a separate code path for `use`, fixed in `master`

**Comment by pooki3bear** [comment]
Thanks, the changes work as expected!
