### ISSUE TITLE
Server-side Flag to Disable DNS TOTP Validation

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#577]
Add a flag to DNS and HTTP/S listeners to disable TOTP validation for instances where the remote system's clock may be inaccurate.

**Comment by 0xjbb** [comment]
Would this be why I'm getting this error by any chance?

```
[2022-02-16T20:36:22Z] [sliver/server/c2/http.go:321] Checking for valid OTP code ... 
[2022-02-16T20:36:22Z] [sliver/server/c2/http.go:336] OTP code (05481150) is invalid 
```
Victim time is a few hours behind my kali time.. (although I just changed the time on my kali host to match the victim and sliver logs still give correct local time )

**Comment by moloch--** [comment]
Yes, I basically just need to add this flag to the UI.

**Comment by rkervella** [comment]
Going back to this, looks like it's already implemented: https://github.com/BishopFox/sliver/blob/c876f34cd0f5aecf29d30570a67bda9bfa501152/client/command/jobs/http.go#L55

Can we close this one?

**Comment by moloch--** [comment]
Oh, is there a cli flag for it? Maybe I did implement it lol

**Comment by moloch--** [comment]
Looks like it, `http --disable-otp` for anyone in the future.

**Comment by hayasec** [comment]
Hi,moloch-,I found the dns tunnel have the same problem.

error:
Invalid query, no DNS response
'xxxxxxxxxxx.xx.xxxx.com.' is subdomain of 'xx.xxxx.com.'
totp request invalid (<nil>)

**Comment by moloch--** [comment]
I don't think there's a flag for DNS C2 at present.
