### ISSUE TITLE
sharp-wmi fails to install via armory 

### ISSUE THREAD

**Issue by dhauenstein** [BishopFox/sliver#579]
**Describe the bug**
When trying to install `sharp-wmi` via the armory tool, installation fails with following error:

```
sliver (ORIGINAL_COMPLAINT) > armory install sharp-wmi

[!] 
Failed to install file: empty file /Certify.exe
[!] Failed to install alias 'sharp-wmi': failed to install alias
sliver (ORIGINAL_COMPLAINT) >  

```

**To Reproduce**
1. In sliver execute `armory install sharp-wmi`

**Expected behavior**
Sharp-wmi gets installed as a sliver extension. no error should occur. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.5.2

**Additional context**
It seems the shar-wmi `armory.json` file has an error, see also https://github.com/sliverarmory/SharpWMI/blob/master/alias.json:
```
...
    "files": [
        {
            "os": "windows",
            "arch": "amd64",
            "path": "Certify.exe"
        },
        {
            "os": "windows",
            "arch": "386",
            "path": "Certify.exe"
        }
    ]
...

```
It looks like a copy/paste error.

**Comment by moloch--** [comment]
Yup ...

**Comment by moloch--** [comment]
Fixed.
