### ISSUE TITLE
rpc error received after upgrade from v.1.4.22 to v.1.5.*

### ISSUE THREAD

**Issue by S4kur4** [BishopFox/sliver#582]
**Describe the bug**
Hey dude, I upgrade silver to v1.5.2 from v1.4.22 (both client and server) and then I received an error when I startup client with `./sliver-client` in multiplayer mode:

```shell
$ ./sliver-client
Connecting to *.*.*.*:50000 ...
panic: rpc error: code = Unauthenticated desc = Authentication failure

goroutine 1 [running]:
github.com/bishopfox/sliver/client/console.(*SliverConsoleClient).PrintLogo(0xc0000ac040)
	github.com/bishopfox/sliver/client/console/console.go:348 +0x4d9
github.com/bishopfox/sliver/client/console.Start.func1(0xc000536840)
	github.com/bishopfox/sliver/client/console/console.go:129 +0x1d
github.com/desertbit/grumble.(*App).SetPrintASCIILogo.func1(0xc00057e000)
	github.com/desertbit/grumble@v1.1.1/app.go:186 +0x77
github.com/desertbit/grumble.(*App).Run(0xc00057e000)
	github.com/desertbit/grumble@v1.1.1/app.go:389 +0x532
github.com/bishopfox/sliver/client/console.Start({0x1f9fa40, 0xc0000a6100}, 0x1b8de48, 0x1b8d860, 0x0)
	github.com/bishopfox/sliver/client/console/console.go:142 +0x526
github.com/bishopfox/sliver/client/cli.StartClientConsole()
	github.com/bishopfox/sliver/client/cli/cli.go:100 +0x1b1
github.com/bishopfox/sliver/client/cli.glob..func1(0x25110e0, {0x18e0ade, 0x0, 0x0})
	github.com/bishopfox/sliver/client/cli/cli.go:74 +0x76
github.com/spf13/cobra.(*Command).execute(0x25110e0, {0xc0001162f0, 0x0, 0x0})
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x25110e0)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/bishopfox/sliver/client/cli.Execute()
	github.com/bishopfox/sliver/client/cli/cli.go:105 +0x25
main.main()
	github.com/bishopfox/sliver/client/main.go:43 +0x17
```
I also tried v1.5.1 and v1.5.0, this error prompted as well, unless I rollback to v1.4.22 and everything runs well.
I'm not good at Go, pls take a look and expecting your reply. Thanks so much!

**To Reproduce**
1. Upgrade sliver server and client from v1.4.22 to v.1.5.2
2. Run command `./sliver-server daemon -p 50000` in server side
3. Run command  './sliver-client' in client side
4. See error in client terminal

**Expected behavior**
Connecting server successfully and then enter into client interactive command mode.

**Screenshots**
No need.

**Desktop (please complete the following information):**
 - Client OS: macOS Montery 12.0.1, amd64
 - Server OS: Ubuntu 16.04.7
 - Version: sliver v1.5.0, v1.5.1, v1.5.2

**Additional context**
No.

**Comment by S4kur4** [comment]
I have found the root cause, looks new version of v1.5.* changed the player key (add a new field `token`) and I didn't notice this. So if we use old player key which only can be used in v1.4.22, we would receive this error.

**Comment by moloch--** [comment]
Yes, v1.5 is not backwards compatible. Sorry there's not a smoother upgrade experience!
