### ISSUE TITLE
Session kills (forced) do not properly terminate host process

### ISSUE THREAD

**Issue by cha0tic87** [BishopFox/sliver#586]
**Describe the bug**
A Sliver implant spawned from a sideloaded DLL does not properly terminate the host process when ``sessions -K`` or ``kill -f`` commands are issued.

**To Reproduce**
1. Inject Sliver DLL as part of another process (e.g. use LMNE to inject into Office process)
2. Observe session callback
3. Issue ``sessions -K`` or ``kill -f`` on session object
3. Observe host process is closed on victim machine (visually, at least)
4. Observe host process is actually still running in Process Explorer

**Expected behavior**
The host process should be fully terminated an not visible in Process Explorer.

**Desktop**
 - OS: Windows 10

**Comment by moloch--** [comment]
Should we be killing the whole process, or just the thread @rkervella ?

**Comment by rkervella** [comment]
Sounds like a regression, it should kill the host when we use `--force`. I'll look into it.

**Comment by moloch--** [comment]
Okay fixed at least one issue: the `kill` RPC was removing the session from core state before sending the kill msg to the implant, thus the session was removed regardless if the underlying connection was terminated (or if the process actually died).

**Comment by moloch--** [comment]
Okay, after more research it's never safe to call `os.exit` from a module (DLL), so I think if we want a force kill command we'd need to under the hood use `terminate` and point it at our current PID. However, there's no cross-platform way to do this, so we probably want to implement something that falls back to `os.exit` if we don't have a `terminate` option

**Comment by moloch--** [comment]
We probably want to require the `--force` flag when compiled as a shared lib.

**Comment by rkervella** [comment]
That's also the thing: we're already doing that check, so I need to debug live to see what's going on. See https://github.com/BishopFox/sliver/blob/4ad1f1a561c209313a771b9a08f12b6ac44183b7/implant/sliver/handlers/special-handlers_windows.go#L50-L76

**Comment by rkervella** [comment]
@cha0tic87 I can't seem to reproduce this one :(

**Comment by moloch--** [comment]
I was able to with rundll32

**Comment by rkervella** [comment]
Hmm even with:

```
rundll32.exe hello.dll,StartW
```

When I run either `sessions -K` or `kill --force` from the session, it properly kills `rundll32.exe`.

**Comment by moloch--** [comment]
Weird, maybe another race?

**Comment by cha0tic87** [comment]
I don't think so, let me try and replicate what I did before

**Comment by cha0tic87** [comment]
Well i'll be damned. Working fine again.

**Comment by cha0tic87** [comment]
Closing for now - will keep an eye on this if it resurfaces.
