### ISSUE TITLE
Add linux-arm64 support for sliver client/server

### ISSUE THREAD

**Issue by cr7pt0pl4gu3** [BishopFox/sliver#607]
Would be really nice if you could add linux-arm64 arch support for client/server. Currently it was not possible for me to build sliver client/server from source for that architecture

**Comment by rkervella** [comment]
@moloch-- wasn't the plan to ditch CGO and use the pure Go implementation of sqlite? That would solve this kind of problems methinks.

**Comment by moloch--** [comment]
Yes, but I ran into db lock issues with GORM/pure go SQLite so I reverted to CGO by default.

@cr7pt0pl4gu3 in the short term you should be able to manually compile a linux/arm version by doing the following:

- Download a copy of golang linux/arm and add it to `/server/assets/fs` (see `go-assets.sh for details)
- Compile using `TAGS=-tags osusergo,netgo,gosqlite,sqlite_omit_load_extension make` (note the use of `gosqlite` instead of the default `cgosqlite`

You may encounter some of the same compatibility problems I encountered with the pure Go version of sqlite, but it should mostly work

**Comment by cr7pt0pl4gu3** [comment]
@moloch-- 
I think I need garble to compile successfully, there is no ARM64 version as far as I understand though:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/43863412/154813907-7d73d7b1-e090-4242-b90c-31e738fcb2e6.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/43863412/154813950-26b4ad00-fc75-4134-b523-0e8923cd17c0.png">
Do I also compile it from source?

**Comment by lesnuages** [comment]
Yes sounds like you need to compile garble from source too

**Comment by cr7pt0pl4gu3** [comment]
Thank you, built successfully:
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/43863412/154820477-32041bff-6310-4d7c-9ae3-b664a38572df.png">
Also had to create this file:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/43863412/154820515-af08495f-3e4e-4478-a60c-cf0f7e8c6b69.png">
However, when generating implant:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/43863412/154820552-c398416a-322e-4161-9322-08634de9bcd5.png">

**Comment by cr7pt0pl4gu3** [comment]
Fixed with those commands, after that implant generated successfully:
<img width="455" alt="image" src="https://user-images.githubusercontent.com/43863412/154821311-6b338c93-2511-4ae5-9ebf-61435bfa769a.png">

**Comment by moloch--** [comment]
Awesome! Like I said, we'll have an official version once we sort out some of the quirks with the pure Go SQLite dependency.

**Comment by valy0** [comment]
It's available in kali repo btw for both amd64 and arm64 and works great (at least as of the writing of this comment - https://www.kali.org/tools/sliver/

**Comment by moloch--** [comment]
Yes, the makefiles and everything now support ARM64, however the ARM64 version uses the pure Go version of Sqlite3 which we've encountered a couple bugs with in the past so there's no "official" release yet, but it should compile and (mostly) work.
