### ISSUE TITLE
Clearing dead sessions causes sliver to hang

### ISSUE THREAD

**Issue by darionreyes** [BishopFox/sliver#608]
**Describe the bug**
When a session is being cleared (either via -C, --clean, prune, or even killing the dead session while using it) it just hangs and nothing happens. Have to ctrl+c to kill the client and restart it.

**To Reproduce**
1. With a dead sessions in place
2. run sessions -C

**Expected behavior**
Clears all dead sessions.

**Screenshots**
![image](https://user-images.githubusercontent.com/69286736/154753257-c48583f6-962b-477f-a3d8-16b1d84c70c7.png)
![image](https://user-images.githubusercontent.com/69286736/154753313-18eec171-68d5-4633-9551-bcd385bbdf41.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Version v1.5.5

**Comment by rkervella** [comment]
I noticed the same issue with `sessions -K` and `beacons -K` on `stage` before the 1.5 merge, pretty sure it's the same issue.
