### ISSUE TITLE
Provide filter functionality to sessions command

### ISSUE THREAD

**Issue by pooki3bear** [BishopFox/sliver#609]
Text filter is great when executing the `use` command, but console messages do not come in properly if I leave the `use` context up. 

A similar text filter should be available for `sessions`, preferably with multiple `-f` arguments. E.g. `sessions -f .30.30 -f SYSTEM`

Scroll is inevitable with many shells 😿 

<img width="1538" alt="Screen Shot 2022-02-20 at 3 25 35 PM" src="https://user-images.githubusercontent.com/24210410/154869096-4573f708-ecb8-49d6-a63f-311ebe3790cf.png">

**Comment by moloch--** [comment]
CCDC problems hehe :D shuld be easy to add

**Comment by ahhh** [comment]
![ccdc_problems](https://user-images.githubusercontent.com/836166/154869392-70ce957d-e182-455c-826a-8e310f11dfda.jpeg)

**Comment by moloch--** [comment]
@pooki3bear @ahhh if you run `use` with no args, it'll start an interactive menu --if you type at that interactive menu it will fuzzy filter

**Comment by pooki3bear** [comment]
Yes, I was using that during comp. It would be nice if `use` had a configurable length for scrolling as well for larger lists. 

The one rough part with `use` fuzzy filter was ability to filter multiple terms like in my example.

**Comment by moloch--** [comment]
Yea, I just figured I'd point to that as an interim solution.
