### ISSUE TITLE
Screenshot not working.

### ISSUE THREAD

**Issue by hayasec** [BishopFox/sliver#610]
**Describe the bug**
Screenshot not working in win10.

**To Reproduce**
1.use a windows active session
2.screenshot

**Expected behavior**
error：
[server] sliver (INDIVIDUAL_CARAVAN) > screenshot

[!] rpc error: code = Internal desc = Database operation failed

**Screenshots**
![image](https://user-images.githubusercontent.com/36404088/155059771-684d4d98-fdc7-4f94-a5ff-d2cf66f81e78.png)

**Desktop (please complete the following information):**
 - Version v1.5.4 v1.5.5

**Additional context**
implant OS : windows 10 10.0.19042.572

Screenshot command work fine in 1.4.22.

**Comment by Werew1942** [comment]
Same issue here

**Comment by moloch--** [comment]
It's a bug, @rkervella is on the case!

**Comment by rkervella** [comment]
Yup gonna look into it more today, I spotted this one last week.
