### ISSUE TITLE
Why implant not online when I changed control VPS. 

### ISSUE THREAD

**Issue by opensesamedoors** [BishopFox/sliver#625]
I download and deploy the Sliver-server on a server A,then generate a implant with http option,OK,It's online.Few days later I changed the server address to B,and the dns changed to B too,but I cann't got the implant online anymore, why? Is the implant check server'key cause this problem?

**Comment by moloch--** [comment]
It should be able to connect so long as you keep the `~/.sliver` directory, which contains the encryption keys.

**Comment by opensesamedoors** [comment]
I lost ~/.sliver directory files means I lost the Implant forever?

**Comment by moloch--** [comment]
Yes, by design. Sorry!
