### ISSUE TITLE
DNS C2 -  rpc error: code = Unknown desc = implant timeout

### ISSUE THREAD

**Issue by kernelr0p** [BishopFox/sliver#639]
**Describe the bug**
DNS implants/beacons timeouts immediately right after going online. 

**To Reproduce**
1. Generate dns beacon: 
generate --dns subdomain.redacted.com. --os linux -d
2. Run dns server: 
dns -d subdomain.redacted.com., subdomain2.redacted.com. -c
3. It successfully goes online for few seconds:
[*] Session 82af90d3 GOVERNING_SCIMITAR - n/a (REDACTED) - linux/amd64 - Mon, 21 Mar 2022 10:53:06 CET
4. /root/.sliver/logs/sliver.log
ERRO[2022-03-21T10:34:12+01:00] [sliver/server/c2/dns.go:382] [dns] error decoding subdata: invalid dns message
INFO[2022-03-21T10:34:12+01:00] [sliver/server/c2/dns.go:366] '3eHUYakFNLRxUbo1t9N9EZNxhYuDqvpsWuNHm76Ca45JXgqvFdJrUDWHRCKXrmh.zB7fok8bQnV1F4YWGaGNsgBHGYYLLay2D4KHDssYr6R6QcyG87YWj6w6TnfQS3r.TzDdp7qnE78R4YPsVxz2Syi4NPwV5rE.redacted.com.' is subdomain of 'redacted.com.'
INFO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:366] '5uaePmYJLndHDXUn5ZaEEeoxKuMQ1HrPTjjzN.redacted.com.' is subdomain of 'redacted.com.'
ERRO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:382] [dns] error decoding subdata: invalid dns message
INFO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:366] 'hjUzDYonjCV3hYeDFR2NEtQeuJ836v5GXLZzV43WRvGRgACUBsEjGcS.redacted.com.' is subdomain of 'redacted.com.'
ERRO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:382] [dns] error decoding subdata: invalid dns message
INFO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:366] 'Y8BWt9MybR1uGDewPPj9BTQmrEpcNNHghHsGdwX2SucvfNTzrj1c6E8Fui4e6kh.9ksURF2jfdeQLnHaBRyPWnWLLLQ7aWtk59pkm1u3H7gEUoMjKZKsrdTrZJt1oAC.H7xZKTunaYa1rYF2UY7bjk6oiznSf45t8BRSzEy1wy6uL3u5ZjjKSmTBY4dNfpq.5uaePmYJLndHDXUn5ZaEEeoxKuMQ1HrPTjjzN.redacted.com.' is subdomain of 'redacted.com.'
INFO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:366] 'QJmiLDThFecGiH6WkhZtTyBa1bnUGnWd1xzC2K4XNoHjvQ9ysbHMVWdMbY7y92X.J55YRyBAsax1Wy18phapd7p7HQs8VNDh1bGnPdsQAsA6AQWMDUenNH3k5FymoCu.hjUzDYonjCV3hYeDFR2NEtQeuJ836v5GXLZzV43WRvGRgACUBsEjGcS.redacted.com.xyz.' is subdomain of 'redacted.com.'
INFO[2022-03-21T10:34:14+01:00] [sliver/server/db/logger.go:20] github.com/bishopfox/sliver/server/db/helpers.go:241 record not found
[0.345ms] [rows:0] SELECT * FROM `hosts` WHERE `hosts`.`host_uuid` = "3cba74a2-eb6a-5f3f-a59e-b833a7e9c631" ORDER BY `hosts`.`id` LIMIT 1
INFO[2022-03-21T10:34:14+01:00] [sliver/server/core/hosts.go:64] Session e526c068-4027-450e-b333-247bd0ee51bd is from a new host
INFO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:366] '6Ngv1zDL9Yjmq1ETU9E1QLx.redacted.com.' is subdomain of 'redacted.com.'
INFO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:366] '6Ngv1zDL9Yjmq1ETU9E1QLx.redacted.com.' is subdomain of 'redacted.com.'
INFO[2022-03-21T10:34:14+01:00] [sliver/server/c2/dns.go:366] '6Ngv1zDL9Yjmq1ETU9E1QLx.redacted.com.' is subdomain of 'redacted.com.'`

5. Implant's debug:6. 
`2022/03/21 02:43:49 sliver.go:95: Hello my name is GOVERNING_SCIMITAR
2022/03/21 02:43:49 limits.go:52: Limit checks completed
2022/03/21 02:43:49 sliver.go:113: Running in session mode
2022/03/21 02:43:49 session.go:144: Starting interactive session connection loop ...
2022/03/21 02:43:49 transports.go:41: Starting c2 url generator () ...
2022/03/21 02:43:49 transports.go:87: Return generator: (chan *url.URL)(0xc000082660)
2022/03/21 02:43:49 transports.go:75: Yield c2 uri = 'dns://REDACTED.COM.'
2022/03/21 02:43:49 transports.go:75: Yield c2 uri = 'dns://REDACTED.COM.'
2022/03/21 02:43:49 session.go:161: Next CC = dns://REDACTED.COM.
2022/03/21 02:43:49 session.go:161: Next CC = dns://REDACTED.COM.
2022/03/21 02:43:49 transports.go:75: Yield c2 uri = 'dns://REDACTED.COM.'
2022/03/21 02:43:49 session.go:252: Attempting to connect via DNS via parent: REDACTED.COM.
2022/03/21 02:43:49 dnsclient.go:150: DNS client connecting to 'REDACTED.COM.' (timeout: 5s) ...
2022/03/21 02:43:49 dnsclient.go:295: [dns] found resolvers: [X.X.X.X]
2022/03/21 02:43:49 crypto.go:190: TOTP Code: 91531497
2022/03/21 02:43:49 dnsclient.go:713: [dns] Fetching dns session id via 'baakbu7ku4n8.REDACTED.COM.' ...
2022/03/21 02:43:49 resolver-generic.go:92: [dns] X.X.X.X:53->A record of baakbu7ku4n8.REDACTED.COM. ?
2022/03/21 02:43:50 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 259.39556ms (err: <nil>)
2022/03/21 02:43:50 resolver-generic.go:109: [dns] answer (a): 116.141.33.1
2022/03/21 02:43:50 dnsclient.go:734: [dns] dns session id: 2198900
2022/03/21 02:43:50 dnsclient.go:810: [dns] Fingerprinting 1 resolver(s) ...
2022/03/21 02:43:50 resolver-generic.go:92: [dns] X.X.X.X:53->A record of 1cufnb8b3421v0d607j0qkwf.REDACTED.COM. ?
2022/03/21 02:43:50 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 260.589131ms (err: <nil>)
2022/03/21 02:43:50 resolver-generic.go:109: [dns] answer (a): 237.230.67.77
2022/03/21 02:43:50 resolver-generic.go:92: [dns] X.X.X.X:53->A record of 1cufnb8b3426y1061ufmqttb.REDACTED.COM. ?
2022/03/21 02:43:50 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 232.018931ms (err: <nil>)
2022/03/21 02:43:50 resolver-generic.go:109: [dns] answer (a): 56.194.32.15
2022/03/21 02:43:50 resolver-generic.go:92: [dns] X.X.X.X:53->A record of 1cufnb8b342f8g6u7gucdc4n.REDACTED.COM. ?
2022/03/21 02:43:50 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 260.69681ms (err: <nil>)
2022/03/21 02:43:50 resolver-generic.go:109: [dns] answer (a): 83.140.98.244
2022/03/21 02:43:50 resolver-generic.go:92: [dns] X.X.X.X:53->A record of 1cufnb8b342eak23eghjjj7k.REDACTED.COM. ?
2022/03/21 02:43:51 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 234.519941ms (err: <nil>)
2022/03/21 02:43:51 resolver-generic.go:109: [dns] answer (a): 37.214.40.50
2022/03/21 02:43:51 resolver-generic.go:92: [dns] X.X.X.X:53->A record of UWkhC3d8DxckBTKd4G14.REDACTED.COM. ?
2022/03/21 02:43:51 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 232.645624ms (err: <nil>)
2022/03/21 02:43:51 resolver-generic.go:109: [dns] answer (a): 46.166.34.86
2022/03/21 02:43:51 resolver-generic.go:92: [dns] X.X.X.X:53->A record of UWkhC3d8eQ8f73M8KkEf.REDACTED.COM. ?
2022/03/21 02:43:51 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 232.151389ms (err: <nil>)
2022/03/21 02:43:51 resolver-generic.go:109: [dns] answer (a): 192.118.35.186
2022/03/21 02:43:51 resolver-generic.go:92: [dns] X.X.X.X:53->A record of UWkhC3d8Dp88aUAkHDXg.REDACTED.COM. ?
2022/03/21 02:43:51 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 231.960384ms (err: <nil>)
2022/03/21 02:43:51 resolver-generic.go:109: [dns] answer (a): 197.142.211.191
2022/03/21 02:43:51 resolver-generic.go:92: [dns] X.X.X.X:53->A record of UWkhC3d8DvsYdETEcP9K.REDACTED.COM. ?
2022/03/21 02:43:52 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 234.306007ms (err: <nil>)
2022/03/21 02:43:52 resolver-generic.go:109: [dns] answer (a): 151.56.100.148
2022/03/21 02:43:52 dnsclient.go:830: [dns] X.X.X.X:53: avg rtt 239.861027ms, base58: true, errors 0
2022/03/21 02:43:52 dnsclient.go:649: [dns] encoded: 0, subdata space: 226 | stop: 103, len: 104
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:104] of 104
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 157 (max: 227)
2022/03/21 02:43:52 dnsclient.go:690: [dns] subdata 0 (0->104): 104 bytes
2022/03/21 02:43:52 dnsclient.go:693: [dns] original data: 104 bytes
2022/03/21 02:43:52 dnsclient.go:694: [dns] total subdata: 104 bytes
2022/03/21 02:43:52 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 469.801425ms (err: <nil>)
2022/03/21 02:43:52 resolver-generic.go:152: [dns] answer (txt): [Bek1SWB_h3FDSOR8lwuoVc8biAADAT2+eFHf2MjLe8li0oFtwDWs3VJSWpvxIWWfs6R7kKqbjjG]
2022/03/21 02:43:52 dnsclient.go:355: [dns] key exchange was successful!
2022/03/21 02:43:52 dnsclient.go:359: [dns] starting worker(s) ...
2022/03/21 02:43:52 dnsclient.go:235: [dns] starting worker #0
2022/03/21 02:43:52 dnsclient.go:235: [dns] starting worker #0
2022/03/21 02:43:52 session.go:260: Starting new session with id = &{[0xc0000722d0] 0xc0000622a0 map[X.X.X.X:53:0xc0000b05c0] .REDACTED.COM. 1000000000 3 5000000000 false  227 2198900 1 false 0xc00016e9f0 0xc0000ae840 0xc0000ae8a0 [0xc0000b75a0 0xc0000b75c0] 2 {} {} true}
2022/03/21 02:43:52 sliver.go:281: Host Uuid: b4663eac-a277-4b1e-9d3a-435854742c7a
2022/03/21 02:43:52 dnsclient.go:428: [dns] read envelope ...
2022/03/21 02:43:52 dnsclient.go:441: [dns] poll msg domain: 6Ngv5ecbPGd5jyPWWb1zzfb.REDACTED.COM.
2022/03/21 02:43:52 dnsclient.go:408: [dns] write envelope ...
2022/03/21 02:43:52 tun-handlers.go:57: [tunnel] Tunnel handlers map[20:0xa31a40 22:0xa30a00 23:0xa307a0 80:0xa328c0 82:0xa33880]
2022/03/21 02:43:52 dnsclient.go:649: [dns] encoded: 0, subdata space: 226 | stop: 112, len: 320
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:113] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 170 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:114] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 172 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:115] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 173 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:116] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 174 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:117] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 176 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:118] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 177 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:119] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 179 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:120] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 180 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:121] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 181 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:122] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 183 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:123] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 184 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:124] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 185 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:125] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 187 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:126] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 188 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:127] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 189 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:128] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 192 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:129] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 194 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:130] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 195 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:131] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 196 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:132] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 198 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:133] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 199 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:134] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 200 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:135] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 202 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:136] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 203 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:137] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 204 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:138] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 206 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:139] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 207 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:140] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 209 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:141] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 210 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:142] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 211 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:143] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 213 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:144] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 214 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:145] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 215 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:146] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 217 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:147] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 218 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:148] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 220 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:149] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 221 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:150] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 222 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:151] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 224 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:152] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 225 (max: 227)
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [0:153] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 226 (max: 227)
2022/03/21 02:43:52 dnsclient.go:649: [dns] encoded: 0, subdata space: 226 | stop: 302, len: 320
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [153:303] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 226 (max: 227)
2022/03/21 02:43:52 dnsclient.go:649: [dns] encoded: 0, subdata space: 226 | stop: 319, len: 320
2022/03/21 02:43:52 dnsclient.go:655: [dns] shave data [303:320] of 320
2022/03/21 02:43:52 dnsclient.go:661: [dns] encoded length is 43 (max: 227)
2022/03/21 02:43:52 dnsclient.go:690: [dns] subdata 0 (0->153): 153 bytes
2022/03/21 02:43:52 dnsclient.go:690: [dns] subdata 1 (153->303): 150 bytes
2022/03/21 02:43:52 dnsclient.go:690: [dns] subdata 2 (303->320): 17 bytes
2022/03/21 02:43:52 dnsclient.go:693: [dns] original data: 320 bytes
2022/03/21 02:43:52 dnsclient.go:694: [dns] total subdata: 320 bytes
2022/03/21 02:43:52 dnsclient.go:250: [dns] #0 work: &{1 Y8BXHBxdPNzijVLYCQEAq54iaLMyQQreJj1puaPJGaPHMEiD5yWqDs9ucfaNX8g.EjqsdpMquVdxadR3BjtdrKxrZBMhgNGNH5R9NtfHSkQbjKd8EyxUgNLrVSjiSZc.phibahTTSGSTTET3DyZPFu6YDGnFafTGGwmRGJ2LkgupXvE5gTn2AR9xRrXwARx.pZrgm1EyPQcrVfxsmGT5jWRrcpMfRxngVAyra.REDACTED.COM. 0xc0000b92c0 <nil>}
2022/03/21 02:43:52 resolver-generic.go:92: [dns] X.X.X.X:53->A record of Y8BXHBxdPNzijVLYCQEAq54iaLMyQQreJj1puaPJGaPHMEiD5yWqDs9ucfaNX8g.EjqsdpMquVdxadR3BjtdrKxrZBMhgNGNH5R9NtfHSkQbjKd8EyxUgNLrVSjiSZc.phibahTTSGSTTET3DyZPFu6YDGnFafTGGwmRGJ2LkgupXvE5gTn2AR9xRrXwARx.pZrgm1EyPQcrVfxsmGT5jWRrcpMfRxngVAyra.REDACTED.COM. ?
2022/03/21 02:43:52 dnsclient.go:250: [dns] #0 work: &{1 Y8BXHBxdPVSwjiztz6f9LkjQ8rti92zn9AgrMwHev6q8qQ65MhS4GuyRzvLxJo7.H4GQyJY6D2D1rYJxorMJffC2gEsFjStqyAmcxghqy8dynkeFVm4NLtLUq8Np5uL.3Yw4vrtArLSpDSwNoEaoXnkD7ezkEpcJeQTXNZAyKtBa7yAuS4UCW47wSkeVZic.jE6qAUSfDN5hn7Z3eeDzyDJwan98pBXT1zbBG.REDACTED.COM. 0xc0000b92c0 <nil>}
2022/03/21 02:43:52 resolver-generic.go:92: [dns] X.X.X.X:53->A record of Y8BXHBxdPVSwjiztz6f9LkjQ8rti92zn9AgrMwHev6q8qQ65MhS4GuyRzvLxJo7.H4GQyJY6D2D1rYJxorMJffC2gEsFjStqyAmcxghqy8dynkeFVm4NLtLUq8Np5uL.3Yw4vrtArLSpDSwNoEaoXnkD7ezkEpcJeQTXNZAyKtBa7yAuS4UCW47wSkeVZic.jE6qAUSfDN5hn7Z3eeDzyDJwan98pBXT1zbBG.REDACTED.COM. ?
2022/03/21 02:43:53 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 463.42944ms (err: <nil>)
2022/03/21 02:43:53 resolver-generic.go:109: [dns] answer (a): X.X.X.X
2022/03/21 02:43:53 dnsclient.go:250: [dns] #0 work: &{1 YMPw84nwf1aw3FpTWCLHbue2WatDHYvnDRqJxucFuBF.REDACTED.COM. 0xc0000b92c0 <nil>}
2022/03/21 02:43:53 resolver-generic.go:92: [dns] X.X.X.X:53->A record of YMPw84nwf1aw3FpTWCLHbue2WatDHYvnDRqJxucFuBF.REDACTED.COM. ?
2022/03/21 02:43:53 resolver-generic.go:175: [dns] rtt->10.70X.X.X.X80.54:53 464.716021ms (err: <nil>)
2022/03/21 02:43:53 resolver-generic.go:109: [dns] answer (a): X.X.X.X
2022/03/21 02:43:53 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 231.667252ms (err: <nil>)
2022/03/21 02:43:53 resolver-generic.go:109: [dns] answer (a): X.X.X.X
2022/03/21 02:43:57 resolver-generic.go:175: [dns] rtt->X.X.X.X:53 5.001561153s (err: read udp X.X.X.X:39791->X.X.X.X:53: i/o timeout)
2022/03/21 02:43:57 resolver-generic.go:128: [dns] query error: read udp X.X.X.X:39791->X.X.X.X:53: i/o timeout (retry wait: 1s)`
**Expected behavior**
Go online and become interactive.

**Desktop (please complete the following information):**
 - OS: Linux redacted 5.4.0-1066-xxxx #71~18.04.1-Ubuntu SMP Wed Mar 2 15:30:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Version: Server v1.5.8

**Comment by moloch--** [comment]
I'll see if I can reproduce but based on the logs it looks like the resolver may be rate limiting you or something.

**Comment by kernelr0p** [comment]
Any idea to customise implant/beacon to possibly bypass the rate limitation?. Just in case this is the case.

**Comment by moloch--** [comment]
You can limit the number of worker threads or try to force the use of other resolvers.

**Comment by moloch--** [comment]
These are "advanced options" which are passed as URL arguments, e.g. `generate beacon --dns dns://1.example.com?workers-per-resolver=1`

**Comment by moloch--** [comment]
Verified code is working with public resolver 8.8.8.8 with the default config on MacOS->linux server. It's likely either your config, or your resolver (which may be detecting the queries as malicious or rate limiting them).

**Comment by kernelr0p** [comment]
Closing this from my side as it was just a port exhaustion scenario due to my reverse proxies. It's not related to sliver.
