### ISSUE TITLE
Sliver server crash when connecting to port forwarded sockets

### ISSUE THREAD

**Issue by precurse-bf** [BishopFox/sliver#651]
**Describe the bug**
Sliver server is crashing on me when attempting to connect to Sliver tunneled TCP sockets. Accessing the socket with a command, such as curl, results in the crash.  This has been confirmed running Sliver server and implant on Linux, using the HTTPS C2 protocol.

**To Reproduce**
1. Run sliver server: `./sliver-server`
2. Enable HTTPS listener: `https`
3. Generate Linux HTTPS implant:
    `generate -o linux -b example.com:443`
4. Run implant on target server and receive connection back.
5. Enable port forwarding: `portfwd add  -r [REDACTED]:443`
    `[*] Port forwarding 127.0.0.1:8080 -> [REDACTED]:443`
6. Interfacing with the listening socket causes Sliver to crash. It sometimes crashes after 1 request, but sometimes it takes 2-3 requests before it does:
    `curl -H "Host: real-host.example.com" -kv https://127.0.0.1:8080`

The Sliver server then crashed with the following stack trace:
```
goroutine 230 [running]:
    github.com/bishopfox/sliver/client/core.(*tunnels).Close(0xb0c1820, 0x408578?)
            github.com/bishopfox/sliver/client/core/tunnel.go:69 +0x106
    github.com/bishopfox/sliver/client/core.(*ChannelProxy).HandleConn.func1()
            github.com/bishopfox/sliver/client/core/portfwd.go:128 +0x99
    github.com/bishopfox/sliver/client/core.(*ChannelProxy).HandleConn(0xc000ce2c80, {0xa7cec78?, 0xc0004ae178})
            github.com/bishopfox/sliver/client/core/portfwd.go:140 +0x328
    github.com/bishopfox/sliver/client/tcpproxy.(*Proxy).serveConn(0xc0005b78c0?, {0xa7cec78?, 0xc0004ae178}, {0xc001000800, 0x1, 0xc00033bd40?})
            github.com/bishopfox/sliver/client/tcpproxy/tcpproxy.go:240 +0x448
    created by github.com/bishopfox/sliver/client/tcpproxy.(*Proxy).serveListener
            github.com/bishopfox/sliver/client/tcpproxy/tcpproxy.go:222 +0x45
```

**Expected behavior**
I'd expect the tunnel to continue to work for subsequent requests.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux (Server AND implant)
 - Version: `Server v1.5.10 - 3cc982068a8317853b67c082f24e45cc8df976cf`

**Additional context**

While this was a less common failure, the implant also died during my testing this bug.

The implant resulted in the following stack trace: 
```panic: send on closed channel

goroutine 5342 [running]:
VrfpxYIS.tz8mJnDe.Write({0xc00032e7c0, 0xc000400180}, {0xc0004f0000, 0x4d, 0x8000})
        HsjiKI_m.go:9 +0x12c
dtBol7f3.biBmZvKu({0xdab500, 0xc000336910}, {0xda9a40, 0xc0002523c0}, {0x0, 0x0, 0x0})
        OwlxD0f0.go:1 +0x204
dtBol7f3.GMKhamhS(...)
        MY4H5q4J.go:1
VrfpxYIS.biEBzZam.func4()
        nZ9zLM2u.go:1 +0x8c
created by VrfpxYIS.biEBzZam
        H6fnhYvs.go:11 +0x43d
```

Followed by the Sliver Server crashing as well:
```
goroutine 90 [running]:
github.com/bishopfox/sliver/client/core.TunnelLoop({0xa803670, 0xc0001da540})
        github.com/bishopfox/sliver/client/core/tunnel.go:141 +0x335
created by github.com/bishopfox/sliver/client/console.Start
        github.com/bishopfox/sliver/client/console/console.go:140 +0x50a
```

**Comment by RafBishopFox** [comment]
I wanted to add some more information since I am not sure how long I will have to work on this. From my limited understanding, it looks like the receive channel of the tunnel is closed before the `Close()` function is called. When `Close()` is called, it tries to close the `Recv` channel, and Go panics because the `Recv` channel was already closed.

Here is a visual representation:
![image](https://user-images.githubusercontent.com/84349012/161097905-1c40e7d8-49db-4bf6-8d61-ea204459c37d.png)

I have attached a quick patch to stop the panics. I have not figured out the underlying cause of why the tunnel gets closed prematurely, though.
[tunnel_panic_hotfix.patch.txt](https://github.com/BishopFox/sliver/files/8391129/tunnel_panic_hotfix.patch.txt)

**Comment by moloch--** [comment]
We probably need to add a `sync.Once` wrapper, since either side can close the tunnel we can't predict which will be close first.

**Comment by rkervella** [comment]
Yeah I was about to say my naive `tunnel.IsOpen` is prone to race conditions.
