### ISSUE TITLE
Why the binaryis is really big ? 

### ISSUE THREAD

**Issue by omerqw23451** [BishopFox/sliver#657]
how i can generate binaryis more small ? the binaryis is really big 
i use the flag --skip-symbols but i need more small bin file

**Comment by rkervella** [comment]
Go binaries include the Go runtime and all external libraries used by the code at compile time to build one unique static binary (well, mostly static). If you want to avoid dropping big binaries to disk, you can still stage the implant through a smaller sized stager.

**Comment by moloch--** [comment]
Please see the wiki https://github.com/BishopFox/sliver/wiki/Getting-Started
