### ISSUE TITLE
Wireguard “beacon” Never Registers

### ISSUE THREAD

**Issue by r00t0v3rr1d3** [BishopFox/sliver#670]
**Describe the bug**
I am unable to get wireguard beacon to work on a windows target. Session mode works fine. For beacon attempts, Sliver log shows:
Accepted connection to wg key exchange listener
Handling connection to key exchange listener
Generating wg keys
Saving wg keys
Getting wg keys for wg server
Successfully generated new wg keys
New WG peers. Updating Wireguard config
Old WG config for peers:
New WG config for peers: public_key=blah

then it dumps the public keys and allowed IPs. This just repeats over and over and the list gets longer and longer and a beacon never appears.

**To Reproduce**
1. Listener: wg -l 51820
2. Implant generate: generate beacon —wg ip:51820 —seconds 30 —jitter 30

**Expected behavior**
A beacon to appear.

**Desktop (please complete the following information):**
 - Target OS: Windows 10 21H2 x64
 - Server OS: Kali 2022.1 x64
 - Version: v1.5.12 release

**Comment by moloch--** [comment]
WG Beacon Implants confirmed working on MacOS, likely a Windows specific issue. Still investigating.
