### ISSUE TITLE
 rpc error: code = Unknown desc = exit status 1

### ISSUE THREAD

**Issue by K8723** [BishopFox/sliver#697]
1. rpc error: code = Unknown desc = exit status 1

**Comment by rokups** [comment]
I have same issue. This is what i did:
```sh
./go-assets.sh
make
./sliver-server
```
In console:
```sh
generate beacon --mtls 127.0.0.1 --save ./beacon-test --os linux
generate --name foo --http 127.0.0.1 --save ./implant-test
```
Both commands result in same error in the end.
```
[*] Generating new linux/amd64 beacon implant binary (1m0s)
[*] Symbol obfuscation is enabled
[!] rpc error: code = Unknown desc = exit status 1
```

**Comment by moloch--** [comment]
This is a generic error message you need to provide more details such as the log files.

**Comment by rokups** [comment]
This is what i find in the log:
```
[sliver/server/gogo/go.go:141] --- stderr ---
go list error: exit status 1: error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
```
I have built sliver from a cloned git repo.

**Comment by moloch--** [comment]
Does the same error occur when using the pre-built binaries from Github?  - https://github.com/BishopFox/sliver/releases/tag/v1.5.16

**Comment by rokups** [comment]
Getting same error. I placed downloaded executable to same dir of cloned git repo in case it matters.. Also when i run server (self-compiled or not) i do get git commit id printed.

**Comment by moloch--** [comment]
The git id in the version should be embedded at compile time, is there anything odd about your setup that you know about? Are there multiple versions of go installed on the system (this shouldn't* matter unless there's a bug in our code).

**Comment by rokups** [comment]
I am not really aware of anything. Go is pretty new to me, so exploring how everything works. I am testing this on archlinux. Had `gccgo` installed, replaced with `go` package and thats that, my understanding is i have only one go compiler. At least no other versioned go binary appears in `/usr/bin/`.
