### ISSUE TITLE
Use a readline that respects .inputrc (allows for Vim keybindings)

### ISSUE THREAD

**Issue by justinsteven** [BishopFox/sliver#711]
**Is your feature request related to a problem? Please describe.**

I would like to be able to have Sliver's UI respect my `.inputrc` which is set up to have Vim keybindings

**Describe the solution you'd like**

There is hopefully a Go readline that respects `.inputrc` and also satisfies any other needs of a readline

**Describe alternatives you've considered**

Not having Vim keybindings in Sliver :(

**Additional context**

**Comment by rkervella** [comment]
This might not be feasible without switching to an entirely different CLI library. Right now we're using grumble, and [apparently they don't intend to support vi mode](https://github.com/desertbit/grumble/issues/8).

**Comment by justinsteven** [comment]
Ahh okay, so grumble is giving the readline that doesn't support `.inputrc`. I don't love the chances of this being fixed, but I think it's worth keeping open.

**Comment by moloch--** [comment]
Both @rkervella and I are ardent vim users and would like to have this type of feature but it would require a fairly significant overall of the shell as far as I know.

**Comment by rkervella** [comment]
Looks like it might be doable after all: https://github.com/desertbit/grumble/pull/47

**Comment by rkervella** [comment]
Pushed a solution that doesn't rely on `.inputrc` but will allow you to enable vim mode via the client's configuration file (`$HOME/.sliver-client/tui-settings.json`):
```json
{
  "tables": "SliverDefault",
  "autoadult": false,
  "beacon_autoresults": true,
  "small_term_width": 170,
  "always_overflow": false,
  "vim_mode": true
}
```
