### ISSUE TITLE
ps should show architecture of each process

### ISSUE THREAD

**Issue by justinsteven** [BishopFox/sliver#714]
**Is your feature request related to a problem? Please describe.**

When doing things such as migrating it is important to know the architecture of processes. `ps` doesn't currently list the architecture of processes.

**Describe the solution you'd like**

`ps` should list architecture of each process

**Describe alternatives you've considered**

None :(

**Comment by moloch--** [comment]
I'm not sure the recent MacOS versions allow any 32-bit processes.
