### ISSUE TITLE
back does not work (Incorrect command)

### ISSUE THREAD

**Issue by trickster0** [BishopFox/sliver#726]
**Describe the bug**
back does not work (Incorrect command)

**To Reproduce**
Generated beacon with mtls for Linux , after use xxxxxxxxxxxxxxxxxxxxx to interact with the beacon i could not go back

**Expected behavior**
Should go back to the main menu

**Screenshots**
![image](https://user-images.githubusercontent.com/20028117/175130032-7f0be5b6-dfc6-4cdd-a55e-2b4fbdd43691.png)

**Desktop (please complete the following information):**
 - OS: POPOS based on ubuntu 22.04

**Comment by trickster0** [comment]
I used the latest release version.

**Comment by moloch--** [comment]
you're looking for `background` i think.

**Comment by trickster0** [comment]
Yea i figured now, It didn't feel very intuitive sorry about that :D
