### ISSUE TITLE
Length restriction enforced on Arguments for Execute-Assembly

### ISSUE THREAD

**Issue by Dauth** [BishopFox/sliver#729]
While using the execute-assembly functionality, there is a length restriction enforced on the arguments which is passed to the executable. Failure to pass in the complete arguments would result in an executable throwing syntax error.

**Command which meets the length restriction**
`execute-assembly SQLQuery.exe -server 127.0.0.1 -query \"    exec (\'xp_cmdshell \'\'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -nop -w hidden -enc dwBoAG8AYQBtAGkAOwBoAG8AcwB0AG4AYQBtAGUAOwBpAHAAYwBvAG4AZgBpAGcAOwB3AGgAbwBhAG0AaQA7AA==\'\' \') AT [m3sqlw.m3c.local]; \"`

**Command which did not meet the length restriction**
`execute-assembly SQLQuery.exe -server 127.0.0.1 -query \"    exec (\'xp_cmdshell \'\'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -nop -w hidden -enc dwBoAG8AYQBtAGkAOwBoAG8AcwB0AG4AYQBtAGUAOwBpAHAAYwBvAG4AZgBpAGcAOwB3AGgAbwBhAG0AaQA7AGgAbwBzAHQAbgBhAG0AZQA7AA==\'\' \') AT [m3sqlw.m3c.local]; \"`

**Expected behavior**
The arguments passed to the argument should not be stripped because of a length restriction as it would cause incomplete commands to be passed to the executable

**Screenshots**
**Command which meets the length restriction**
![2](https://user-images.githubusercontent.com/10680613/177577653-dd082948-720e-4963-bcff-2407169d507b.PNG)
**Command which did not meet the length restriction**
![3](https://user-images.githubusercontent.com/10680613/177577677-13933be3-7d54-4e74-ad0b-2740b8dcbf30.PNG)

**Comment by kNgF** [comment]
I was also facing same related issues with the execute-assembly and even with the inbuilt rubeus command as you can see in the provided screenshot
<img width="724" alt="Screenshot 2022-07-07 014856" src="https://user-images.githubusercontent.com/38097025/177635804-0ddcb4f7-2111-4008-8a5f-5c25e8cb9647.png">

**Comment by rkervella** [comment]
Yeah that's the issue I faced a few weeks ago, it was working fine last year.

**Comment by kNgF** [comment]
Can it be fixed as it makes things harder for us as I have to put the ticket into a file on the disk and then use it, kinda hard, better would have been if Sliver had implemented a kerberos_ticket_use functionality just like we have it in cobalt

**Comment by wavvs** [comment]
> Can it be fixed as it makes things harder for us as I have to put the ticket into a file on the disk and then use it, kinda hard, better would have been if Sliver had implemented a kerberos_ticket_use functionality just like we have it in cobalt

Wrote a BOF which supports Sliver and can ptt (https://github.com/wavvs/nanorobeus), not s4u though. Let me know if there are any issues.

**Comment by rkervella** [comment]
Looks like it's restriction in the Donut loader: https://github.dev/TheWover/donut/blob/dafea1702ce2e71d5139c4d583627f7ee740f3ae/include/donut.h#L430
`DONUT_MAXNAME` is set to 256.

We probably need to fork https://github.com/binject/go-donut and update the loader to fix that.

**Comment by rkervella** [comment]
> I just found out that using the "inline-execute-assembly" option allows to circumvent the problem: ![image](https://user-images.githubusercontent.com/32550820/179766093-f9920ae0-70f0-4e1d-b1a2-839167d033f9.png)
> 
> PS: data shown on the screenshot are from an internal lab, no data leak here.

Yup it's because `execute-assembly` uses go-donut, which relies on the Donut loader, and the loader fixes the max param size to 256 characters. `inline-execute-assembly` implements its own way of loading assemblies, and doesn't seem to have the same limitations.

**Comment by rkervella** [comment]
Closing as "wontfix" since it's kinda out of our control (a limitation of a dependency we use, Donut). We have alternatives which are:

- the `inline-execute-assembly` extension
- the incoming `--in-process` flag for the `execute-assembly` command once #803 will be merged

I know this issue also affects `sideload`, but it is what it is I guess. Unless someone wants to tackle the issue and update the Donut loader to support arbitrary sized arguments, there's nothing we can do right now.

**Comment by moloch--** [comment]
@rkervella maybe we should add a warning when we detect input that's too long?

**Comment by rkervella** [comment]
Yes, I'll document it in the wiki too.
