### ISSUE TITLE
[SMB Named Pipe] ACL is too restrictive on pivot named pipe

### ISSUE THREAD

**Issue by Ottersec** [BishopFox/sliver#732]
**Is your feature request related to a problem? Please describe.**
The current implementation of the named pipe pivot within Sliver is using the default ACL security descriptor which is the following :
```
- RW for the named pipe creator
- RW for the Administrators
- RW for the  LocalSystem account
- R for Everyone
```
Unfortunately from time to time some edge cases arrise and *prevent* the smb pivot listener to connect back to the initial beacon. I'll provide two example :

**Example 1 : Privilege escalation on a IIS**

As an operator you  find a share writable by everyone which happened to be the webroot of an IIS server "IIS1.  As things goes well you privesc using JuicyPotato on that web server and you're now NT SYSTEM on that server.

If you upload your named pipe pivot to that web server and run it as NT SYSTEM, this beacon won't be allowed to connect back to the initial beacon as he would authenticate as **IIS1$** which has **no permission** to *WRITE* on that named pipe :(

**Example 2 : Opsec operations within narrowed down ingress/egress network access**

As an operator you managed to find an account which is local administrator on 200 servers but you don't want to use it to perform your lateral movement. As such you're dumping the SAM base (SAMR) and using the NT hash of the computer account to create your silver ticket and add the right permissions to be local administrator.
If you want to run an smb beacon on that server with let's say services.py , it's going to be ran as NT SYSTEM and has such the beacon won't be able to connect back to the named pipe (same problem as example 1)

**Describe the solution you'd like**
Add the option to allow the created named pipe to be more permissive such as adding the "Everyone" group within the ACL or narrow it down to some specific user/computer.

Here is two examples that i have in mind :
```
# Add the Write ACL for the Everyone group
pivots named-pipe --bind foobar --allow-all
# Add the ACL for a specific user
pivots named-pipe --bin foobar --allow-user "SRV1$"
```
That would be represented as something like this : 

```
Start a named pipe pivot listener

Usage:
======
  named-pipe [flags]

Flags:
======
  -b, --bind    string    name of the named pipe to bind pivot listener
  -h, --help              display help
  -t, --timeout int       command timeout in seconds (default: 60)
  -a, --allow-all    allow the write permission on the named pipe for the "Everyone" group
  -u, --allow-user   allow the Read and Write permission for the specified user
```

**Additional context**
It is quite common in engagement to have a beacon running as NT SYSTEM, especially for the SMB pivot listener which will thus authenticate against our listener as the computer account (ex: SRV1$) which is a pain since he is not allowed to connect to our named pipe!

**Note** : I beleive that is why the named pipe of Cobalt Strike has an RW ACL for the "Everyone" group 
**Note 2** : This also may be way the **getsystem** command do not work within an smb session

**Comment by rkervella** [comment]
Yeah it's a known issue, gonna look into it. I think we can safely make the pipe open to all since we're checking the communications for replay attacks.

**Comment by rkervella** [comment]
Alright got a fix working, I'll push it when I get home.

**Comment by Ottersec** [comment]
> Alright got a fix working, I'll push it when I get home.

You guys rock ! Thanks for this speed implementation.

**Comment by moloch--** [comment]
Probably still a good idea to make it configurable.

**Comment by rkervella** [comment]
That means resolving the username/group to SID and then craft a proper SDDL string, which is going to be a bit more complex.

**Comment by rkervella** [comment]
Let's do YOLO and default for now, I'll see to add configurable users/SIDs later.
