### ISSUE TITLE
Shell does not return output for errors

### ISSUE THREAD

**Issue by Dauth** [BishopFox/sliver#736]
In a shell, when an error is encountered, it is not shown on screen

**Expected behavior**
Output and errors should be displayed to a user

**Screenshots**
Left screen shows sliver and the right screen shows metasploit
![image](https://user-images.githubusercontent.com/10680613/178110082-e1fa729a-e1a9-4aff-9b41-6e5f0f252df1.png)

**Comment by rkervella** [comment]
@moloch-- I have a fix in the `fix/shell-stderr` branch but I don't like it:
https://github.com/BishopFox/sliver/blob/e7284b5880e69e122ef1c162459b3d68aa6f9982/implant/sliver/handlers/tunnel_handlers/shell_handler.go#L103-L127

Ideally I would prefer to have the `transports.Tunnel` struct to have a `Readers []io.Reader` member and iterate over those in a goroutine to copy back data to the tunnel. However, I'm not sure how that would work with the whole sequencing stuff in `data_handler.go`.

**Comment by rkervella** [comment]
Hm I might have another solution with an `io.MultiReader`.

**Comment by rkervella** [comment]
Got a working fix in #740
