### ISSUE TITLE
[Tunnel/bug] Missing parameter, IncWriteSequence does not take effect,Two bugs that can affect operation 

### ISSUE THREAD

**Issue by a3sroot** [BishopFox/sliver#741]
https://github.com/BishopFox/sliver/blob/68b129acaabd5e05dc2e8bb247f781f8d3ea118c/implant/sliver/shell/shell-pty.go#L118-L123

Missing Stderr: term.

I also found a bug.
go version: go version go1.18.2 darwin/amd64
When compiling to darwin, the i++ in implant/sliver/transports/tunnel.go:56 does not work, even if a lock is used.

**Comment by rkervella** [comment]
> When compiling to darwin, the i++ in implant/sliver/transports/tunnel.go:56 does not work, even if a lock is used.

Can you post an example so we can reproduce on our side?

**Comment by a3sroot** [comment]
> > When compiling to darwin, the i++ in implant/sliver/transports/tunnel.go:56 does not work, even if a lock is used.
> 
> Can you post an example so we can reproduce on our side?

darwin implant When using the shell function, implant/sliver/handlers/tunnel_handlers/tunnel_writer.go:30, there are two seq: 0 cases.

**Comment by a3sroot** [comment]
linux implant When using the shell function, IncWriteSequence causes the seq to be loaded out of order and the shell data cannot be returned.

**Comment by a3sroot** [comment]
commit 68b129acaabd5e05dc2e8bb247f781f8d3ea118c
implant/sliver/handlers/tunnel_handlers/tunnel_writer.go:32
I logged the output before calling IncWriteSequence and found that there is a certain chance that IncWriteSequence does not take effect without the add operation, however, the subsequent display is back to normal. However, because of the lack of a Sep caused Tunnel data error can not be cached properly.

The data will be presented as.

Request
Sep 0 Sep 0 Sep 2 Sep 3

Response infinite stored in Tunnel cannot loop properly
Sep 0 Sep 0 Sep 2 Sep 3

Translated with www.DeepL.com/Translator (free version)

**Comment by a3sroot** [comment]
Sorry it was my modification of the ptyShell return that caused this.
<img width="367" alt="截屏2022-07-19 16 55 40" src="https://user-images.githubusercontent.com/81551286/179710252-3e9448a5-0a81-413b-a93a-5b67f94643aa.png">
l
