### ISSUE TITLE
ps shows processes as being x86_64 on an x86 installation of Windows

### ISSUE THREAD

**Issue by justinsteven** [BishopFox/sliver#751]
**Describe the bug**

#745 added architecture information to the `ps` listing

Windows process architecture is done using `IsWow64Process()`. If a process is detected as being a wow64 process it's determined to be x86, else it's determined to be x86_64. `IsWow64Process()` seems to always return false on x86 installations of Windows. This causes sliver to falsely identify all processes on an x86 Windows installation as being x86_64 processes.

**To Reproduce**

Get a session on an x64 Windows 10 system. Have an x86 process running (e.g. notepad.exe from syswow64) Do `ps`. Note that all native processes are listed with architecture being x86_64 while the x86 process is listed as x86 :+1: 

```raw
[server] sliver (SOCIAL_GRIT) > info

        Session ID: 39f0b19d-b266-4d06-85ff-94c894cccd82
... SNIP ...
                OS: windows
           Version: 10 build 19044 x86_64
              Arch: amd64
... SNIP ...

[server] sliver (SOCIAL_GRIT) > ps
... SNIP ...
1124   6404   AERITH\justin   x86_64   msedge.exe                    1
 992    6404   AERITH\justin   x86_64   msedge.exe                    1
 424    4412   AERITH\justin   x86_64   win64.exe                     1
 7296   648                             svchost.exe                   -1
 7784   4412   AERITH\justin   x86      notepad.exe                   1
 7424   648                             svchost.exe                   -1
... SNIP ...
```

Get a session on an x86 Windows 10 system. Do `ps`. Note that all processes are listed with architecture being x86_64, which is incorrect.

```raw
[server] sliver (CONSTITUTIONAL_PUDDING) > info

        Session ID: edfd2940-8fd3-4758-8fde-2416dd25f352
... SNIP ...
                OS: windows
           Version: 10 build 19043 x86
              Arch: 386
... SNIP ...

[server] sliver (CONSTITUTIONAL_PUDDING) > ps
... SNIP ...
 2920   620                               svchost.exe                   -1
 3972   760    AERITH86\justin   x86_64   UserOOBEBroker.exe            1
 3376   760    AERITH86\justin   x86_64   ShellExperienceHost.exe       1
 4064   760    AERITH86\justin   x86_64   RuntimeBroker.exe             1
 2704   620                               MsMpEng.exe                   -1
 500    3640   AERITH86\justin   x86_64   msedge.exe                    1
 6104   500    AERITH86\justin   x86_64   msedge.exe                    1

... SNIP ...
```

**Expected behavior**

x86 processes are detected as being x86 when running on an x86 Windows installation

**Additional information**

If `IsWow64Process()` uses https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process under the hood, there are also caveats regarding ARM systems. Could this affect sliver in the future? If so we should annotate the use of `IsWow64Process()` with a warning that it might not be appropriate to use on ARM systems.

**Comment by moloch--** [comment]
Sliver will technically run `windows/arm` though it's considered a "generic" platform so only the "pure go" implementations _should_ be used, but now that I'm writing this I think of the build constraints are only `_windows` ...
