### ISSUE TITLE
Download command not working between Client 1.5.12 and 1.5.18/19

### ISSUE THREAD

**Issue by r0pchain** [BishopFox/sliver#758]
**Describe the bug**
Downloads appear to be broken between client 1.5.12 and 1.5.18 and 1.5.19. I noticed this issue last week and assumed it was a random bug that would get fixed in 1.5.19 or something, but tried again today with 1.5.19 and it's still presenting. Running client as root. Implants were generated with 1.5.12. 

**To Reproduce**
1. Initiate session with implant on client 1.5.19
2. download c:\\temp\\file.txt
   [!] No files downloaded from the implant - check permissions, path, and / or filters.
3. cd c:\\temp
4. download file.txt
   [!] No files downloaded from the implant - check permissions, path, and / or filters.
5. Initiate session with same implant on client 1.5.12 in same local shell instance
6. download c:\\temp\\file.txt
  [*] Wrote 492 bytes to blahblahblah
7. cd c:\\temp
8. download file.txt
   [*] Wrote 492 bytes to blahblahblah

**Expected behavior**
The file to download 

**Screenshots**
![image](https://user-images.githubusercontent.com/95697211/180469843-e11014e0-3514-41ac-aa28-8b8fa463e4dc.png)

**audit.json**
Client v1.5.19 download command
`{"level":"info","msg":"{\"request\":\"{\\\"Path\\\":\\\"c:\\\\\\\\temp\\\\\\\\httpupload.vbs\\\",\\\"Request\\\":{\\\"Timeout\\\":60000000000,\\\"SessionID\\\":\\\"6e3d704f-XXXX-XXXX-XXXX-XXXXXXXXXXXX\\\"}}\",\"method\":\"/rpcpb.SliverRPC/Download\"}","time":"2022-07-22T15:03:22Z"}`

Client v1.5.12 download command
`{"level":"info","msg":"{\"request\":\"{\\\"Path\\\":\\\"c:\\\\\\\\temp\\\\\\\\httpupload.vbs\\\",\\\"Request\\\":{\\\"Timeout\\\":60000000000,\\\"SessionID\\\":\\\""6e3d704f-XXXX-XXXX-XXXX-XXXXXXXXXXXX\\\"}}\",\"method\":\"/rpcpb.SliverRPC/Download\"}","time":"2022-07-22T15:04:04Z"}`

**Desktop (please complete the following information):**
 - OS: Target is Windows, Client is Ubuntu 20 on Windows Subsystem for Linux
 - Version **Server** 1.5.18, 1.5.19, **Client** 1.5.18, 1.5.19

**Additional context**
Tried on multiple target versions of Windows, all giving this error on client 1.5.18 and 1.5.19 but work fine with the exact commands on 1.5.12

**Comment by rkervella** [comment]
> Implants were generated with 1.5.12

That's basically your issue. Looks like the protobuf definition for the download RPC changed in 1.15.13, which is why we don't recommend to use implants generated with older versions of the framework alongside with newer server/client versions.

Try running an implant generated with v1.5.19 with v1.5.19 of the server and client, if the issue is still present, then we'll investigate.

**Comment by r0pchain** [comment]
That's definitely what it is - turns out I just suck 👍
