### ISSUE TITLE
Adding loot cred with empty username and password crashes client

### ISSUE THREAD

**Issue by AdnaneKhan** [BishopFox/sliver#759]
**Describe the bug**

When using the `loot creds` command to add a USER_PASSWORD credential, if the user and password is empty, then the client will crash on subsequent commands that query the loots database.

**To Reproduce**

1. Start sliver client
2. Run 'loot creds -n somename'
3. Select USER_PASSWORD
4. Press enter for an empty username
5. Press enter for an empty password
6. Receive success message for loot added
7. Type in one of the following commands: 'loot creds', 'loot rm', or 'loot' (any command that lists loot in server's db)

```
sliver > loot creds -n credname

? Choose a credential type: USER_PASSWORD
? Username:
? Password:

[*] Successfully added loot to server (2aa0c04c-715e-4204-a97a-f38f92239194)
```

**Expected behavior**

Client should handle empty credentials gracefully or empty credentials should be rejected when added.

**Screenshots**

```
sliver > loot

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc56769]

goroutine 1 [running]:
github.com/bishopfox/sliver/client/command/loot.PrintAllLootTable({0x1988780, 0xc000758ea0}, 0xc0007f2780)
	github.com/bishopfox/sliver/client/command/loot/loot.go:170 +0x3a9
```

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS] Debian Linux
 - Version [e.g. v0.0.5] 5.10.127-1

**Additional context**

In my environment, there were no other loot entries in the database. The server did not crash so I believe this issue is limited to the client.

**Comment by AdnaneKhan** [comment]
I was able to recover from the error state by using an SQLite3 client and running `DELETE FROM loots` on the server's DB, but there didn't seem to be a way to fix the issue from the client.

**Comment by rkervella** [comment]
Correct, it's an oversight, I'm working on a fix right now.

**Comment by rkervella** [comment]
@AdnaneKhan fixed in https://github.com/BishopFox/sliver/releases/tag/v1.5.20
