### ISSUE TITLE
Misleading Wiki configuration

### ISSUE THREAD

**Issue by thehackerish** [BishopFox/sliver#765]
**Describe the bug**
The Wiki states in the http-c2 config the following for the `headers` attribute:

```
A list of objects that contain a name and value to add as request headers (default: null)
```

When using the name and value attributes only, we receive no callbacks from the implant.
The configuration requires an additional attribute `probability`, which the wiki does not mention. After adding this attribute, everything works as expected.

**To Reproduce**
1. Edit the file `/root/.sliver/configs/http-c2.json` 
2. Under `implant_config` > `headers`, put `[{"name":"blah", "value":"blah"}]`
3. Generate an implant
4. No callbacks will be received
5. Edit the same file by adding the attribute `probability`. Like this `[{"name":"blah", "value":"blah", "probability": 100}]`
6. Regenerate the implant and run it. You should receive a callback with the correct HTTP header.

**Expected behavior**
Nothing, the Wiki should be more precise.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.5.19

**Additional context**
N/A

**Comment by rkervella** [comment]
@moloch-- do we actually need the `probability` field in this structure for the implant side, or was is it just because we reuse the same structure for the `server_config.headers` that requires this `probability` field?

**Comment by moloch--** [comment]
it's nice to have on the implant-side to add configuration to the egress traffic methinks.

**Comment by rkervella** [comment]
Fixed the wiki entry.
