### ISSUE TITLE
About using Sliver-Gui

### ISSUE THREAD

**Issue by secfb** [BishopFox/sliver#775]
Hi
I want to use the program through the gui, but I could not adjust it. I looked through the application documentation but couldn't find anything. Can you help me with this?

![iShot_2022-08-01_10 32 01](https://user-images.githubusercontent.com/38748801/182096952-907b473c-f86c-4450-a997-13e68c759849.png)

**Comment by moloch--** [comment]
The GUI is experimental (see read me) and for developers only. Once we have a more functional release I'll create tutorials/etc. for using the GUI. Please avoid opening any tickets for the GUI.

That said, it uses the same [multiplayer](https://github.com/BishopFox/sliver/wiki/Multiplayer-Mode) profiles as the console client.
