### ISSUE TITLE
/server/assets.go   Unresolved reference 'assetsFs'

### ISSUE THREAD

**Issue by xiaoheiwo** [BishopFox/sliver#777]
I try to debug the program, but I get an error in the /server/assets.go file

cannot find assetsfs method

how to solve。 thinks

<img width="629" alt="image" src="https://user-images.githubusercontent.com/37685546/182285857-2f4d69e2-e839-4773-bd0c-9efbbd356939.png">

**Comment by moloch--** [comment]
Check your version of Go, you need to use Go v1.18 or later.

**Comment by xiaoheiwo** [comment]
I'm already using 1.8 do， I need a higher version ？
<img width="337" alt="image" src="https://user-images.githubusercontent.com/37685546/182289232-8d75cc9c-509f-4bd5-94e4-c559f070180c.png">

**Comment by xiaoheiwo** [comment]
Before this, I have run the go-assets.sh and make commands according to the wiki documentation and successfully built the project

**Comment by xiaoheiwo** [comment]
I try to upgrade to 1.8.5 and still get an error
<img width="494" alt="image" src="https://user-images.githubusercontent.com/37685546/182290227-b7788147-3f1a-4723-8632-836510d895c7.png">

**Comment by moloch--** [comment]
You may need to set GOOS and GOARCH in your code editor to tell `gopls` which file to include. 

https://stackoverflow.com/questions/66188534/how-to-get-vscode-to-use-different-go-env-vars-for-different-directories-in-the

**Comment by xiaoheiwo** [comment]
I am using the goland editor. I don't know if there is a configuration method for goland, my goos and goarch are configured

<img width="396" alt="image" src="https://user-images.githubusercontent.com/37685546/182295713-86dca04f-6700-406f-a430-61f39eff5602.png">

**Comment by xiaoheiwo** [comment]
I solved the problem, I didn't configure compile parameters in editor - tags thinks

**Comment by PromiseNoDieForever** [comment]
Can you tell me how solved the problem,  I use vscode  and  go1.18.5
