### ISSUE TITLE
Mutliple domains and ports for  mtls

### ISSUE THREAD

**Issue by cmprmsd** [BishopFox/sliver#788]
**Describe the bug**
When you specify multiple mtls or https ports e.g. always the latest occurence will take affect.

**To Reproduce**
```bash
generate ... --mlts domain:80 --mlts domain:443 --mlts anotherdomain:443 -wg ... -wg ....
```

**Expected behavior**
All C2 uris should take affect and be chosen with regards to the connection strategy. (order for same protocols would be the argument order I'd suggest).

** Context **
When having implants on red team engagements copied to usb sticks e.g. that will be dropped on unknown infrastructure the implant should be able to connect to multiple ports of the same protocols.
As you can't know the open ports I'd just choose several common ports.

I'm not sure if grumble can handle multiple of the same arguments though or if you have to create some taxonomy like `--mtls=domaina:53,domaina:123,domainb:500`. :cold_sweat: 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.5.22

**Comment by cmprmsd** [comment]
sometimes... you have implemented it already.. :rofl: at least for http I see the format in the [wiki](https://github.com/BishopFox/sliver/wiki/HTTP(S)-C2#multiple-domains) 

for `--mtls a:80,a:443,b:8080` however, I get the following: 
![image](https://user-images.githubusercontent.com/73472903/185424725-8c64af4d-30f4-4ab5-b08e-7c982b49190c.png)

**Comment by moloch--** [comment]
This _should_ work for any protocol so it's a bug.

**Comment by cmprmsd** [comment]
PEBKAC

Seems it was my issue.. I expected more output coming after the connection establishment message ("Connecting...") as the debug did not say "yup connected". However, the connection was established and worked.
