### ISSUE TITLE
db returns wrong beacon object if BeaconID is empty string

### ISSUE THREAD

**Issue by daddycocoaman** [BishopFox/sliver#813]
**Describe the bug**
While troubleshooting an issue in [moloch--/sliver-py#3](https://github.com/moloch--/sliver-py/issues/3), discovered a lack of check of empty strings when searching the database for beacons. Passing an empty string appears to return the first beacon known to that user's RPC session. There's an issue to fix on the sliver-py side with passing the correct field but I also don't think that the database should search for empty strings and still return a valid beacon.

https://github.com/BishopFox/sliver/blob/4ffb75fa153a2230cd6cec86afadec44142f1d6f/server/rpc/rpc.go#L139-L151

**To Reproduce**
- Connect to server via RPC
- Launch multiple beacons
- Send any request to `asyncGenericHandler` with BeaconID set to an empty string
- Get incorrect result

**Expected behavior**
The RPC call should probably fail if the beacon ID isn't valid.

**Screenshots**
Grabbed from sliver-py issue:
![image](https://user-images.githubusercontent.com/21189155/187652729-68bf4dca-fccd-4455-9b76-d6d718b13a3a.png)

**Comment by moloch--** [comment]
Interesting GORM behavior here, good to know.

**Comment by moloch--** [comment]
Should be fixed in `master`
