### ISSUE TITLE
Cannot connect with beacon with https and http

### ISSUE THREAD

**Issue by DwiyanTech** [BishopFox/sliver#828]
**Describe the bug**
Cannot connect with beacon with https and http

**To Reproduce**
1. Go to sliver-server
2. generate https
3.https
4. put on virtualbox
5. in log it tels 404 not found

**Expected behavior**
Can connect beacon

**Scree
![abc](https://user-images.githubusercontent.com/47693495/188288419-7066355b-8fec-4c77-a06f-ace8912bb12a.png)
nshots**
![Screenshot at 2022-09-03 21-34-12](https://user-images.githubusercontent.com/47693495/188288420-0a1771d3-4623-49ed-8df0-a584ffcf58e1.png)

**Desktop (please complete the following information):**
- Sliver server (Linux)
- Target windows

**Additional context**

**Comment by moloch--** [comment]
Looks like a host based firewall may be blocking the connection.

**Comment by DwiyanTech** [comment]
@moloch-- thanks for answering, i already turned off the all firewal then i try mtls connection and it's work what i've must checl next ?

**Comment by moloch--** [comment]
Can you should me the `generate` command you used?

**Comment by DwiyanTech** [comment]
> Can you show me the `generate` command you used?

@moloch-- here my command 

generate beacon -a amd64 -b http://172.16.66.1/dwyn-test/ -o windows

**Comment by moloch--** [comment]
Use:

```
generate beacon -a amd64 -b https://172.16.66.1/dwyn-test -o windows
```

Note the omission of the trailing `/` in the C2 URL, looks like we have a parsing bug that doesn't join the URL prefix properly when there's a trailing `/`

**Comment by DwiyanTech** [comment]
Thanks for answering and guide @moloch--  i try it but it still won't work. any i've missed ?
![engga bisa](https://user-images.githubusercontent.com/47693495/188324907-8c975f4c-3a29-4943-b879-1157e6edd1bc.png)
![engga bisa 2](https://user-images.githubusercontent.com/47693495/188324910-1bad4735-6ab6-44e8-aa6b-a4635e0c9f18.png)


> Use:
> 
> ```
> generate beacon -a amd64 -b https://172.16.66.1/dwyn-test -o windows
> ```
> 
> Note the omission of the trailing `/` in the C2 URL, looks like we have a parsing bug that doesn't join the URL prefix properly when there's a trailing `/`

**Comment by moloch--** [comment]
It looks like you still have a firewall or network error, "actively refused" means the underlying TCP connection cannot be established because something (like a firewall) rejected the connection.

**Comment by moloch--** [comment]
Also, check your clocks (the target and server clocks need to be aligned), the key exchange uses TOTP you can disable this in the listener via a flag.

**Comment by DwiyanTech** [comment]
> Also, check your clocks (the target and server clocks need to be aligned), the key exchange uses TOTP you can disable this in the listener via a flag.

hey @moloch-- thanks for guide, i disable totp with disable totp flag on listener it works but why it can happen ? is it firewall issue ? or network issue with has any requests authentication if you want to explain me i give my big thanks

**Comment by moloch--** [comment]
It just means the clock on the target machine is configured incorrectly, this is uncommon (most OS's sync via NTP automatically) but can happen. It's an opsec feature to make the server harder to detect.
