### ISSUE TITLE
Possible issue with dynamic code generation/compile-time obfuscation

### ISSUE THREAD

**Issue by Mister-Joe** [BishopFox/sliver#833]
**Describe the bug**
Windows Defender has established a signature for Sliver binaries, but Sliver is described as having dynamic code generation & compile-time obfuscation capabilities. AV evasion is out of scope for this project, but considering Sliver binaries are being detected based on a static signature, it might be an in-scope issue.

**To Reproduce**
1. generate beacon --http <IP>
2. generate beacon --mtls <IP>
3. Run generated binaries through ThreatCheck (https://github.com/rasta-mouse/ThreatCheck)
4. See signature

**Expected behavior**
Generated binaries should evade static analysis.

**Screenshots**

![image](https://user-images.githubusercontent.com/16895391/188396894-a3992941-9619-4dae-a0b8-b209b7cb66ee.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 19044

**Additional context**

The functions in question all seem to be DNS related. File: sliver.pb.go around line 5000.

![image](https://user-images.githubusercontent.com/16895391/188400489-f4ab4736-6da6-4558-8101-c3f6f821a8b4.png)
![image](https://user-images.githubusercontent.com/16895391/188400380-4abd8969-882d-4613-b965-7581a8c74c93.png)
![image](https://user-images.githubusercontent.com/16895391/188400219-6fc34a48-b699-4631-99e3-ee091595d554.png)
![image](https://user-images.githubusercontent.com/16895391/188400171-579a7317-1ae5-43b5-9b7f-36021d40e331.png)

**Comment by moloch--** [comment]
Obfuscation is incomplete, this is a known issue. However, the obfuscator is also always improving!

**Comment by rkervella** [comment]
What version of Sliver are you using?

**Comment by rkervella** [comment]
Looks like something's changed in the protobuf package and a bunch of new symbols/strings are added now. I'll have a look.

**Comment by Mister-Joe** [comment]
Hi @rkervella I am using v1.5.24. Thanks for looking into this!

**Comment by rkervella** [comment]
Ran a few tests, looks like garble is missing out a bunch of stuff on the protobuf generated files. Probably due to an update in either Go, Garble (regression?) or the protobuf package itself. Not sure what we can do at this point apart from pinging mvdan.

**Comment by moloch--** [comment]
Let me fix the garble unit tests before we invest more time.

**Comment by rkervella** [comment]
> Let me fix the garble unit tests before we invest more time.

I already tested with upstream Garble, no difference.

**Comment by moloch--** [comment]
We should file a ticket with upstream Garble then while we sort out the details.

**Comment by moloch--** [comment]
https://github.com/BishopFox/sliver/pull/916

**Comment by Mister-Joe** [comment]
Does not look like this has been fixed yet @moloch-- . Tested on v1.5.29. ``generate beacon --http 127.0.0.1``

![image](https://user-images.githubusercontent.com/16895391/194737402-17415ae2-885b-4116-858d-ddca8e89a8d1.png)

**Comment by moloch--** [comment]
Ah okay, at this point it's an upstream garble issue (I think these are pb struct json annotations not strings), though we may be able to do an ad-hoc patch.

**Comment by moloch--** [comment]
Reflections is a known limitation of the obfuscator though, so not sure there's much we can do.

**Comment by moloch--** [comment]
@rkervella do you think we can strip these?

**Comment by rkervella** [comment]
No, it's a garble issue. These are not annotations in the protobuf, but the types and function names, so we can't really replace them after code generation (or we'll end up the goobfuscate route again).

**Comment by moloch--** [comment]
Okay we'll have to file a bug with garble.

**Comment by moloch--** [comment]
https://github.com/BishopFox/sliver/pull/1215
