### ISSUE TITLE
Implants die after prolonged server connectivity issues

### ISSUE THREAD

**Issue by pb376** [BishopFox/sliver#852]
I have had a handful of instances where our team's C2 server went down for 24-48 hours during an engagement, and in almost every case only a subset of implants reconnected after we brought the server back up. Yesterday we had a similar issue that lasted approximately 22h, and when we finally noticed and brought the server back up only one of our nine active implants checked back in. We are using mtls as the transport, and all machines are linux.

As far as I can tell there isn't a configured maximum number of connection retries, but please correct me if I am wrong. Otherwise, it seems there is a bug that emerges after a long sequence of failed reconnection attempts. We've also confirmed with the client that there are no endpoint agents or network controls in place that could have resulted in the process being killed or traffic being blocked due to excessive failed connections.

**Comment by moloch--** [comment]
There is are setting in the `generate` command that can be used to control this, `--max-errors` which controls how many reconnection attempts the implant will attempt and the `--reconnect` flag controls the amount of time between each reconnection attempt.

By default this is 1,000 attempts at a 1 minute interval (~16hrs).
