### ISSUE TITLE
--in-process Flag for Execute-Assembly

### ISSUE THREAD

**Issue by cmprmsd** [BishopFox/sliver#858]
**Describe the bug**
When I try to run the --in-process flag I noticed the following error message:

```bash
# client
[!] rpc error: code = Unknown desc = unknown message type
# logs
[sliver/server/rpc/rpc-tasks.go:140] Executing assembly in-process
[github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/logging/logrus/options.go:215] finished unary call with code Unknown
```

**To Reproduce**
1. Execute `sharp-hound-3 -i`

**Expected behavior**
in-process execution

**Desktop (please complete the following information):**
 - OS: Linux, Implant: Windows
 - Version: 
 Client v1.5.26 - 312f133f1e0a31f714eb7635299d34ce9e694374 - linux/amd64
 Server v1.5.26 - 312f133f1e0a31f714eb7635299d34ce9e694374 - linux/amd64

**Comment by rkervella** [comment]
What version did you use to generate the implants? There's been an update in the protobuf definitions, the old implants won't be compatibles.

**Comment by cmprmsd** [comment]
Oh man.. Makes sense. I'll check it out tomorrow!

**Comment by cmprmsd** [comment]
You were correct. My implant was built with an old version. Got it working :+1:

**Comment by jas594** [comment]
I'm having a different issue using the "--in-process" flag. For example, running Seatbelt or SharpUp results in the following:

Command: execute-assembly --in-process Seatbelt.exe "-group=user"
Output: Blank

Command 2: execute-assembly --in-process SharpUp.exe audit
Output: The MethodInfo::Invoke_3 method returned an error: The system cannot find the path specified.

Client Version: 1.5.26
Server Version: 1.5.26
Implant: Windows
