### ISSUE TITLE
Obfuscation Performance Improvement 

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#88]
The current obfuscation process is very slow, taking about 15min on my MacBook.

**Comment by C-Sto** [comment]
Just pasting the ramblings I had in slack to keep track better:

> I haven't been able to dive in _too_ deeply, but those performance metrics I collected seem to indicate that it's the initial parsing of the src that takes all the time, so if you can cache the parsed src somehow it will speed up agent generation muchly
presumably that's all on the gobfuscate side, though
bonus points if you can work out how to store it in the static binary

>https://github.com/BishopFox/sliver/blob/master/server/gobfuscate/strings.go#L23-L55 yeah I reckon this can be sped up a fair bit by re-architecting gobfuscate a little (or a lot)

>pre-compute the parsing and whatnot, you will lose the ability to modify the agent on-the-fly (ish), but presumably if it's a packed asset anyway that isn't super easy either

> though actually, you can probably do that at runtime, spin off an obfuscation init routine that loads up all the files and parses them then notify the user when obfuscation is ready 

>a few other easy wins - remove `map[string]blah`, they are significantly slower than basically anything else
>rather, any struct that has pointer members is real bad for map keys
