### ISSUE TITLE
No Matching File Found - Docker Build Issues

### ISSUE THREAD

**Issue by gso-trifork-security** [BishopFox/sliver#896]
**Describe the bug**
When I try to build the docker image i get this error:
```
#0 0.932 server/assets/assets_linux_amd64.go:8:36: pattern fs/*.zip: no matching files found
#0 0.936 make: *** [Makefile:107: default] Error 1
------
failed to solve: executor failed running [/bin/sh -c make clean-all     && make     && cp -vv sliver-server /opt/sliver-server     && /opt/sliver-server unpack --force]: exit code: 2
```

I have tried to build from the sourcecode on master and release v. 1.5.27

**Comment by moloch--** [comment]
Oh this is my fault, i'm an idiot.

**Comment by moloch--** [comment]
Updated Dockerfile here, will be merged shortly: https://github.com/BishopFox/sliver/blob/0f53c7ca119e8d31f9c36946d621bf173c9ce926/Dockerfile
