### ISSUE TITLE
rportfwd interface resolution issue

### ISSUE THREAD

**Issue by m3rcer** [BishopFox/sliver#897]
**rportfwd ethernet interface resolution issue**
The `rportfwd` command works well on the `eth0` interface but doesn't port forward to other interfaces like `tun0`

**To Reproduce**
1. Gain a session bound in the `eth0` subnet (Here: 192.168.x.x subnet)
 - `rportfwd` works in this case.
2. Gain a session bound in the `tun0` subnet (Here: 172.16.x.x subnet)
 - `rportfwd` doesn't work in this case with an error: `rpc error: code = Unknown desc = unknown message type`.

**Plausible Fix**
Automatically resolve the subnet/interface or create an option to select another interface.

**Screenshots**
![image](https://user-images.githubusercontent.com/81712403/191497429-e526c6c0-9abf-4f73-925c-796b365556ee.png)

**Desktop:**
 OS: Kali Linux 2022.1

**Comment by moloch--** [comment]
Interesting, I'm not sure what's causing this ... 0.0.0.0 should bind to all interfaces.

**Comment by MrAle98** [comment]
@m3rcer the two sessions you spawned are on the same machine?

**Comment by m3rcer** [comment]
> @m3rcer the two sessions you spawned are on the same machine?

Nope, in short got 2 separate sliver sessions on 2 different machines. Ones a machine in my home lab, and the other one is over a vpn connection (tun0). Maybe binding or connecting back to a vpn interface could be the issue?

**Comment by MrAle98** [comment]
Both of them are HTTP sessions?

**Comment by m3rcer** [comment]
Yep, https listening on port 443 to be precise

**Comment by m3rcer** [comment]
Seems like I had a VMWare issue. The same setup worked fine on my VirtualBox VM :|. 
Anyways well done with the **rportfwd** command, it was a must need.👍
