### ISSUE TITLE
Inconsistent Terminology

### ISSUE THREAD

**Issue by dan-bishopfox** [BishopFox/sliver#92]
The terminology of components seem inconsistent and unintuitive. There's three main components:

- Sliver Server. But sometimes called Sliver Hive
- Sliver Client. But sometimes called a "Player"
- Slivers. But sometimes called an "Implant". Also, just calling this "a sliver" is sort of unintuitive since that's the name of the whole project. 

This was very confusing for me on first read. The distinction between a "sliver client" and "a sliver" was not obvious. A "client" (just from the name) could very well mean the thing you run on the target machine. 

FWIW, I like leaning into the MtG references. "Hive" is a pretty good description of the server, even if you don't know Magic. Similarly, a "Player" is pretty clear that it means "you, the user" (as opposed to the implant). "Implant" isn't a bad name, but is off-theme. But calling the implants just "slivers" (like "generate a sliver) is kind of confusing since that's the name of the whole project. 

Thoughts?

**Comment by moloch--** [comment]
Addressed as part of `grpc` refactor.
