### ISSUE TITLE
Cursed Chrome could not find Chrome executable

### ISSUE THREAD

**Issue by TheWebWraith** [BishopFox/sliver#939]
When trying to use Cursed Chrome on an active target session where Chrome is installed, I receive the following error:

![image](https://user-images.githubusercontent.com/88548351/194890761-b47d648a-3c23-4d84-ab23-779e6487d6ef.png)

As you can see from the screenshot, the target session has the Chrome default path as required by cursed-chrome.go which is:

`defaultChromePath := "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"`

Any ideas as to why the executable path is not being recognized?

**Comment by TheWebWraith** [comment]
@moloch-- 

This is what happens when trying your suggestion:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/88548351/195102041-7d23fb2b-aeff-434f-b01e-3ce8bd9c5de6.png">

**Comment by moloch--** [comment]
Are you sure the version information you posted is accurate? Did you compile the server yourself? I have no idea why "unknown command" is showing up.

**Comment by moloch--** [comment]
Does `cursed --help` so anything?

**Comment by TheWebWraith** [comment]
@moloch-- 

Just checked the version info again, it's the same as above, so that's accurate there. As for compiling the server, my team and I just updated the version from the previous one without any compiling. 

When I run `cursed --help` I receive the following:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/88548351/195106257-da151448-8c98-4a47-a751-94b106c94d45.png">

**Comment by moloch--** [comment]
Very odd, i'm kinda at a loss what's going on tbh. Does `cused chrome --help` also show the help output?

**Comment by TheWebWraith** [comment]
@moloch-- 

It does, check it out:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/88548351/195107475-0e600eae-6f5e-4bea-ae92-4a131abfea81.png">

**Comment by moloch--** [comment]
Was the implant your interacting with generated by this version of the server?

**Comment by TheWebWraith** [comment]
That worked! Maybe the mismatch of the versions did it? Not sure, but at least it's remedied now.

**Comment by TheWebWraith** [comment]
@moloch-- 

Appreciate your help!
