### ISSUE TITLE
Unknown desc = fork/exec /root/.sliver/go/bin/garble

### ISSUE THREAD

**Issue by bcdlbgm** [BishopFox/sliver#942]
Describe the bug
Error when generating  implant ，Windows also exists

`rpc error: code = Unknown desc = fork/exec /root/.sliver/go/bin/garble: no such file or directory
`
To Reproduce

Launch v1.5.29 of ./sliver-server
Command: generate  --mtls 127.0.0.1
See error `rpc error: rpc error: code = Unknown desc = fork/exec /root/.sliver/go/bin/garble: no such file or directory`

```
[server] sliver > generate  --mtls 127.0.0.1 

[*] Generating new windows/amd64 implant binary
[*] Symbol obfuscation is enabled
[!] rpc error: code = Unknown desc = fork/exec /root/.sliver/go/bin/garble: no such file or directory

[server] sliver >  
```

Desktop (please complete the following information):

OS: Ubuntu 22.04.1 (server)

**Comment by moloch--** [comment]
try `sudo sliver unpack --force`
