### ISSUE TITLE
[UX] Boolean flags overwritten when passed a string value

### ISSUE THREAD

**Issue by moloch--** [BishopFox/sliver#963]
```
execute-assembly --save foo.txt --in-process foo.exe
```

Calls `InvokeExecuteAssembly` instead of `InvokeInProcExecuteAssembly`

**Comment by rkervella** [comment]
`--save` is a boolean, not a string. Passing up a string for this flag messes up all the other boolean flags, including `--in-process` (basically sets them to `false`).

**Comment by rkervella** [comment]
Keeping this one open in case someone makes the same mistake.
