### ISSUE TITLE
[Licensing Request] Using Sliver in training material

### ISSUE THREAD

**Issue by HuskyHacks** [BishopFox/sliver#973]
Hello,
I'm currently writing a free course on Responsible Red Teaming and I plan on releasing it soon. I wanted to include Sliver in the practical lab section that deals with safe and secure C2 infrastructure. Sliver is included in the last section of the lab as the best current example of a C2 that has been built from the ground up for safety and operational security. I'm including a copy of the Sliver license in the course materials and pointing the students towards the main repo for more information about the project.

Is this OK in the eyes of the dev team? I wanted to check first as a matter of professional courtesy. I can provide the lab material for review if you'd like. Thanks!

Husky

**Comment by moloch--** [comment]
Absolutely okay!

**Comment by HuskyHacks** [comment]
Thank you!
