### ISSUE TITLE
make-token does not work

### ISSUE THREAD

**Issue by ziyishen97** [BishopFox/sliver#983]
**Describe the bug**
Impersonating a user by executing **make-token** command does not work as expected.

**To Reproduce**
1. Execute ```make-token``` command and provide with credentials of a privileged domain user ```make-token -u svc_sql -d . -p jkhnrjk123!```
2. Execute ```whoami``` command
3. Try to access **C$** of a host which the user **svc_sql** has access to: ```execute -o powershell ls \\\\srv01.child.red.local\\c$```
4. Results are not expected

**Expected behavior**
Expected output of whoami:
```
Logon ID: CHILD\eric
[*] Current Token ID: CHILD\svc_sql

```
Actual output of whoami
```
Logon ID: CHILD\eric
[*] Current Token ID: CHILD\eric

```

Expected result of C$ access: 
**Can list C:\ on host SRV01.**
Actual result:
```
[server] sliver (DEFENSIVE_WASHER) > execute -o powershell ls \\\\srv01.child.htb.local\\c$

[*] Output:
[*] Stderr:
ls : Access is denied
At line:1 char:1
+ ls \\srv01.child.red.local\c$
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (\\srv01.child.red.local\c$:String) [Get-ChildItem], UnauthorizedAcces 
   sException
    + FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand
 
ls : Cannot find path '\\srv01.child.red.local\c$' because it does not exist.
At line:1 char:1
+ ls \\srv01.child.red.local\c$
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\srv01.child.red.local\c$:String) [Get-ChildItem], ItemNotFoundExcepti 
   on
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 
[!] Exited with status 1!

```

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022
 - Version 15.30

**Additional context**
CHILD\eric is the current user, I tried to impersonate svc_sql. This user can access C$ of SRV01.

**Comment by ziyishen97** [comment]
I noticed the issue: https://github.com/BishopFox/sliver/issues/635. Even if I changed the logontype and recompile Sliver, it still does not work.

**Comment by rkervella** [comment]
The `whoami` command won't display the proper information. Try to use `execute` with the `--token` command to tell the implant to use the created token.

**Comment by ziyishen97** [comment]
I got this error. The same error if I enter interactive shell.
```
[server] sliver (DEFENSIVE_WASHER) > execute --token -o powershell ls \\\\srv01.child.htb.local\\c$ 

[!] rpc error: code = Unknown desc = fork/exec C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe: A required privilege is not held by the client.
[server] sliver (DEFENSIVE_WASHER) > execute --token -o whoami

[!] rpc error: code = Unknown desc = fork/exec whoami.exe: A required privilege is not held by the client.

```

**Comment by rkervella** [comment]
This actually work as intended:

```
[server] sliver > use c1136213-ef17-45c6-96f2-54a7d90faf9b

[*] Active session CERTAIN_BANQUETTE (c1136213-ef17-45c6-96f2-54a7d90faf9b)

[server] sliver (CERTAIN_BANQUETTE) > ls //srv-dc01/c$/

\\srv-dc01\c$\ (0 items, 0 B)
=============================


[server] sliver (CERTAIN_BANQUETTE) > make-token -d centrallab.local -u administrator -p SuperAdmin123


[*] Successfully impersonated centrallab.local\administrator. Use `rev2self` to revert to your previous token.
[server] sliver (CERTAIN_BANQUETTE) > ls //srv-dc01/c$/

\\srv-dc01\c$\ (15 items, 384.4 MiB)
====================================
drwxrwxrwx  $Recycle.Bin                        <dir>      Sun May 26 01:54:18 -0700 2019
-r--r--r--  bootmgr                             375.3 KiB  Sat Jul 16 06:18:08 -0700 2016
-rw-rw-rw-  BOOTNXT                             1 B        Sat Jul 16 06:18:08 -0700 2016
drwxrwxrwx  Config.Msi                          <dir>      Sun Mar 28 05:12:50 -0700 2021
Lrw-rw-rw-  Documents and Settings -> C:\Users  0 B        Mon May 20 01:14:44 -0700 2019
drwxrwxrwx  Logs                                <dir>      Mon Sep 12 04:34:59 -0700 2016
-rw-rw-rw-  pagefile.sys                        384.0 MiB  Fri Oct 21 20:14:19 -0700 2022
drwxrwxrwx  PerfLogs                            <dir>      Mon May 20 20:15:22 -0700 2019
dr-xr-xr-x  Program Files                       <dir>      Sun Mar 28 03:18:23 -0700 2021
drwxrwxrwx  Program Files (x86)                 <dir>      Sat Jul 16 06:23:24 -0700 2016
drwxrwxrwx  ProgramData                         <dir>      Wed Nov 10 09:10:40 -0700 2021
drwxrwxrwx  Recovery                            <dir>      Mon May 20 01:14:45 -0700 2019
drwxrwxrwx  System Volume Information           <dir>      Sun May 26 02:04:44 -0700 2019
dr-xr-xr-x  Users                               <dir>      Sun May 26 01:53:57 -0700 2019
drwxrwxrwx  Windows                             <dir>      Wed Sep 29 19:15:54 -0700 2021


[server] sliver (CERTAIN_BANQUETTE) > execute --token -o powershell -c 'ls \\\\srv-dc01\\c$'

[!] rpc error: code = Unknown desc = fork/exec C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe: A required privilege is not held by the client.
[server] sliver (CERTAIN_BANQUETTE) >  
```

You cannot create a new process with the impersonated token, but you can use it to access network resources like shown above.

**Comment by rkervella** [comment]
Now as a side note: it will sometime fail due to the way we're impersonating the token obtained by calling make token. To use it, we're calling `ImpersonateLoggedOnUser`, which will grant the current Windows thread temporary access to this user's credentials via the created token.
The thing is the Sliver implant will execute each task in a separate goroutine, and there is no guaranteed mapping between goroutines and system threads.
To work around that, we placed a call before every task to `ImpersonateLoggedOnUser`, but even this approach is not bulletproof and might result in an access denied. In my local tests, around 90% of the commands execute correctly (with the impersonated credentials) whereas 10% of the time it just fails. If that happens to you, try to execute the command multiple times.

**Comment by rkervella** [comment]
@ziyishen97 the PR #986 will probably introduce the feature you're looking for though: running an arbitrary process under a different user by supplying credentials.

**Comment by ziyishen97** [comment]
It works! Thanks for your explaination!

**Comment by Cyb3rC3lt** [comment]
> This actually work as intended:
> 
> ```
> [server] sliver > use c1136213-ef17-45c6-96f2-54a7d90faf9b
> 
> [*] Active session CERTAIN_BANQUETTE (c1136213-ef17-45c6-96f2-54a7d90faf9b)
> 
> [server] sliver (CERTAIN_BANQUETTE) > ls //srv-dc01/c$/
> 
> \\srv-dc01\c$\ (0 items, 0 B)
> =============================
> 
> 
> [server] sliver (CERTAIN_BANQUETTE) > make-token -d centrallab.local -u administrator -p SuperAdmin123
> 
> 
> [*] Successfully impersonated centrallab.local\administrator. Use `rev2self` to revert to your previous token.
> [server] sliver (CERTAIN_BANQUETTE) > ls //srv-dc01/c$/
> 
> \\srv-dc01\c$\ (15 items, 384.4 MiB)
> ====================================
> drwxrwxrwx  $Recycle.Bin                        <dir>      Sun May 26 01:54:18 -0700 2019
> -r--r--r--  bootmgr                             375.3 KiB  Sat Jul 16 06:18:08 -0700 2016
> -rw-rw-rw-  BOOTNXT                             1 B        Sat Jul 16 06:18:08 -0700 2016
> drwxrwxrwx  Config.Msi                          <dir>      Sun Mar 28 05:12:50 -0700 2021
> Lrw-rw-rw-  Documents and Settings -> C:\Users  0 B        Mon May 20 01:14:44 -0700 2019
> drwxrwxrwx  Logs                                <dir>      Mon Sep 12 04:34:59 -0700 2016
> -rw-rw-rw-  pagefile.sys                        384.0 MiB  Fri Oct 21 20:14:19 -0700 2022
> drwxrwxrwx  PerfLogs                            <dir>      Mon May 20 20:15:22 -0700 2019
> dr-xr-xr-x  Program Files                       <dir>      Sun Mar 28 03:18:23 -0700 2021
> drwxrwxrwx  Program Files (x86)                 <dir>      Sat Jul 16 06:23:24 -0700 2016
> drwxrwxrwx  ProgramData                         <dir>      Wed Nov 10 09:10:40 -0700 2021
> drwxrwxrwx  Recovery                            <dir>      Mon May 20 01:14:45 -0700 2019
> drwxrwxrwx  System Volume Information           <dir>      Sun May 26 02:04:44 -0700 2019
> dr-xr-xr-x  Users                               <dir>      Sun May 26 01:53:57 -0700 2019
> drwxrwxrwx  Windows                             <dir>      Wed Sep 29 19:15:54 -0700 2021
> 
> 
> [server] sliver (CERTAIN_BANQUETTE) > execute --token -o powershell -c 'ls \\\\srv-dc01\\c$'
> 
> [!] rpc error: code = Unknown desc = fork/exec C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe: A required privilege is not held by the client.
> [server] sliver (CERTAIN_BANQUETTE) >  
> ```
> 
> You cannot create a new process with the impersonated token, but you can use it to access network resources like shown above.

Apologies I realise this is closed but I wonder could you advise on this question as I struggled with it today. I impersonated a DA and I tried to open a shell as that DA but I assume your explanation above is the reason the shell fails and that's what is occurring her too?

https://github.com/BishopFox/sliver/issues/1065

If we couldn't use psexec (which did work via impersonated token to get me to the DC) because it was blocked, what is the best way to use Sliver to get onto the DC with a token in your opinion? I struggled with ideas today. Thanks
