### ISSUE TITLE
I can't seem to make a darwin / mac binary

### ISSUE THREAD

**Issue by jayhill365** [BishopFox/sliver#988]
**Describe the bug**

1. Go into aws instance, generating windows implants works fine.
2. This actually wasn't an issue previously but now I can't seem to make a darwin / mac binary, the file finishes compiling but when i view it, it isn't an executable file, it looks blank.
3. <img width="313" alt="Screen Shot 2022-11-03 at 12 29 20 PM" src="https://user-images.githubusercontent.com/19259608/199816401-6b335721-81d5-46ea-803c-e6604a66acfa.png">
4. Wondering why I'm getting this error, currently in aws ec2 debian instance, its working when creating windows but not with mac.

**Comment by rkervella** [comment]
What do you mean by "it looks blank"? What command did you type? What was the output?

**Comment by jayhill365** [comment]
the command I ran was:
<img width="417" alt="Screen Shot 2022-11-03 at 1 15 46 PM" src="https://user-images.githubusercontent.com/19259608/199825067-1e3e462a-1c5e-4b66-836d-b42283815fd7.png">

I got


<img width="375" alt="Screen Shot 2022-11-03 at 1 16 42 PM" src="https://user-images.githubusercontent.com/19259608/199825234-e22ab082-d5e8-4a0b-a56c-60e19fbb4c9c.png">

Then when i navigate to file its just white not an executable 
<img width="472" alt="Screen Shot 2022-11-03 at 1 17 06 PM" src="https://user-images.githubusercontent.com/19259608/199825414-fa7de7bb-5a40-4b75-862b-dd913bc3a34b.png">

**Comment by rkervella** [comment]
Looks like you're confused. This file is a mach-o executable. You can run `file UPSET_TRICK` to check yourself.

**Comment by jayhill365** [comment]
Yeah a bit confused so UPSET_TRICK should be able to run on a mac laptop right? I'll try again but no new sessions spawned for this implant the last time.

**Comment by jayhill365** [comment]
<img width="248" alt="Screen Shot 2022-11-03 at 1 34 46 PM" src="https://user-images.githubusercontent.com/19259608/199828557-3b75caf4-3ff0-466d-9d66-bd8efc8ce6be.png">

**Comment by rkervella** [comment]
> Yeah a bit confused so UPSET_TRICK should be able to run on a mac laptop right?

Yes and it will, the prompt you're getting is from Gatekeeper telling you the binary is not signed. Plus, it probably has the quarantine extended attribute since, from your screenshot, you downloaded it from a web browser.

Removing the quarantine bit and running the binary from a regular shell will get you a session.

**Comment by jayhill365** [comment]
Okay I can try,  not sure if this adds context but when i opened the file this is what i got.
<img width="653" alt="Screen Shot 2022-11-03 at 1 41 28 PM" src="https://user-images.githubusercontent.com/19259608/199829754-b822e989-1680-4dbb-b3bf-4180e26322b2.png">

**Comment by rkervella** [comment]
> Thank @rkervella how can I take out the quarantine bit?

```
xattr -r -d com.apple.quarantine /path/to/file
```

**Comment by jayhill365** [comment]
Thanks again @rkervella

**Comment by jayhill365** [comment]
still no success running the mach-o executable, im sure im doing something wrong

<img width="350" alt="Screen Shot 2022-11-03 at 2 26 49 PM" src="https://user-images.githubusercontent.com/19259608/199837507-e9bccc06-bd73-4842-bb06-5debda4ad4d1.png">

**Comment by rkervella** [comment]
Is the file marked as executable? What does `ls -l DARK_FRIDGE` outputs?

**Comment by jayhill365** [comment]
Yes it seems to be
<img width="258" alt="Screen Shot 2022-11-03 at 2 30 28 PM" src="https://user-images.githubusercontent.com/19259608/199838076-dae44971-c4d7-4856-b555-e13d0e2daac1.png">
<img width="341" alt="Screen Shot 2022-11-03 at 2 30 41 PM" src="https://user-images.githubusercontent.com/19259608/199838128-648286e2-0cbb-449c-b080-1b870747b448.png">

**Comment by rkervella** [comment]
I meant what are the flags on the file? Can you post the full `ls -l` output?

**Comment by jayhill365** [comment]
<img width="406" alt="Screen Shot 2022-11-03 at 2 50 33 PM" src="https://user-images.githubusercontent.com/19259608/199841229-27b091c7-89b3-4c25-8a7a-ebebc474a83e.png">

**Comment by rkervella** [comment]
That's what thought, the file is not marked executable. Run `chmod +x` on it, it should work after that.

**Comment by jayhill365** [comment]
I can confirm it works now thanks
